### ISSUE TITLE
PolygonSockClient Connection Error

### ISSUE THREAD

**Issue by apfitzge** [alpacahq/alpaca-trade-api-csharp#104]
Trying to follow the brokerage account example and establish a connection through the PolygonSockClient. Minimal example below:
```
var pc = new PolygonSockClient(key);
pc.OnError += (err) => Console.WriteLine("Encountered error: " + err);
await pc.ConnectAsync();
```
This results in the following errors being written (both during or after market-hours):
```
Encountered error: System.InvalidOperationException: Unexpected message type 'status' received.
Encountered error: System.InvalidOperationException: Unexpected message type 'status' received.
```

**Comment by OlegRa** [comment]
@apfitzge I'll try to fix it today and prepare build with hotfix after PR review.

**Comment by OlegRa** [comment]
@apfitzge PR #105 still under review but I've prepared [3.2.1-alpha](https://www.nuget.org/packages/Alpaca.Markets/3.2.1-alpha) version for you. Please, test it and report any new problems relate to this version in this issue.

**Comment by apfitzge** [comment]
@OlegRa Thanks for the quick turn around on this.

I've tested on 3.2.1-alpha and the reported error seems to be resolved.
I can successfully establish a connection.

Trying to continue follow the usage example, and subscribing to a data stream:
```
var pc = new PolygonSockClient(key);
pc.OnError += (err) => Console.WriteLine("Encountered error: " + err);
pc.Connected += (status) => Console.WriteLine("Connected with status: " + status);
await pc.ConnectAsync();
pc.SecondAggReceived += (agg) => Console.WriteLine("SecondAggReceived: " + agg);
pc.SubscribeSecondAgg("AAPL");
```
This resulsts in the following output:
```
Encountered error: System.Exception: You must send data by websocket after websocket is opened!
Connected with status: Authorized
```

The order on this seems to be the opposite of what I'd expect from wating for the connection.
The connection status is reported after the error from subscribing is thrown.
If I add a `await Task.Delay(1000);` before subscribing, there is no error.
It seems that `await pc.ConnectAsync();` may not be waiting for the connection to be fully established before proceeding (or I am misinterpreting this).

**Comment by OlegRa** [comment]
@apfitzge You are right, current behavior of `ConnectAsync()` method is not very clear from documentation. It returns promise for channel-level connection event not for application level 'connected and authorized' state. You have to wait for `Connected` event with `Authorized` state before your subscription requests will be processed correctly on server side.

You can check PR #105 - `PolygonSockClientTest.cs` contains helper method `connectAndAuthenticate` which implements this logic.

Maybe in future releases we will change `ConnectAsync()` method behavior or will add new `ConnectAndAuthenticateAsync()` helper method which will hide all these details from user. I'll open new issue for this improvement.

**Comment by apfitzge** [comment]
@OlegRa Thanks, that makes sense. The added `ConnectAndAuthenticateAsync()` improvement/issue will make this easier in the future.

**Comment by OlegRa** [comment]
Please @apfitzge close it if all works fine in final [3.2.1](https://www.nuget.org/packages/Alpaca.Markets/3.2.1) version available on NuGet,

**Comment by apfitzge** [comment]
Confirmed to work on 3.2.1 version on NuGet, closing this issue.
