### ISSUE TITLE
Change configuration approach for clients

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#106]
In current implementation we pass all configuration options as configuration parameters. It makes extension harder and in most cases user have to duplicate code with initialization parameters. All configuration options can be placed into a single class and this class can be used as single argument for initializing all clients.
Because this is a breaking change so it can be done only in scope of major release.

**Comment by ttt733** [comment]
Please note pull #113 when considering this - authentication will in the future be available either via key pair or a single OAuth token.

**Comment by OlegRa** [comment]
@OlegRa I want to add new constructors and related configuration objects into the upcoming 3.5.0 release and mark old constructors with the `Obsolete` attribute (warning level) for a more smooth transition.
