### ISSUE TITLE
Unprocessable Entity errors

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#119]
Is there a list of supported stock symbols that alpaca deals with? I haven't been able to find anything so far. Or even better yet is there a method yet that can check a symbol to see if it returns true or false if it is a supported symbol on alpaca?

I'm getting this error for symbol ELC which is found here on yahoo finance:
https://finance.yahoo.com/quote/ELC?p=ELC&.tsrc=fin-srch

**Comment by OlegRa** [comment]
@ooples According to [this](https://docs.alpaca.markets/market-data/) Alpaca documentation page:

> Currently, we only provide data for U.S. listed equities

This contract (ELC) is ETF so it's not possible to use it via Alpaca API. For brief checks you can get full list of supported assets using `ListAssetsAsync` method and populate in-memory `HashSet` with asset symbols. Or just use `GetAssetAsync` method and check return value/exception.
