### ISSUE TITLE
Feature request: Include day trading buying power and/or correct account buying Power

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#124]
According to the details on the alpaca documentation found below:

https://docs.alpaca.markets/user-protections/#day-trade-margin-call-dtmc-protection-at-alpaca

If a user is marked for dmtc protection, the user's true buying power is the day trading buying power and so the value that you receive using the api isn't the accurate buying power so if you try to buy stocks using the max buying power you have, you will receive an error stating you have insufficient day trading buying power. 

I would like to either have the day trading buying power variable for each user account accessible by the api or correct the existing buying power that is accessible to reflect the actual buying power each user has

**Comment by OlegRa** [comment]
@ooples You can check new properties of `IAccount` interface in [3.2.4](https://www.nuget.org/packages/Alpaca.Markets/3.2.4) or [3.3.0-beta](https://www.nuget.org/packages/Alpaca.Markets/3.3.0-beta) packages available on NuGet.

**Comment by ooples** [comment]
I'm already checking that now actually lol. I'm loving the quick turnaround on bug fixes. I really appreciate it!

**Comment by ooples** [comment]
I have seen one issue but I'm not sure if the problem lies on your end or the data you are pulling from the socket api. 

According to this link: https://docs.alpaca.markets/user-protections/#day-trade-margin-call-dtmc-protection-at-alpaca

> Users only receive day trading buying power when marked as a pattern day trader. If the user is designated a pattern day trader, the account.multiplier is equal to 4.

On my end I have the account multiplier of 4 but the bool for isPatternDayTrader is showing up as false which is obviously incorrect. I place multiple orders per day so it should be marked as true.

**Comment by OlegRa** [comment]
@ttt733 Trevor, could you please check this problem on your side?

**Comment by OlegRa** [comment]
I close it for now after 2 weeks of inactivity. If problem still exist in latest version of SDK feel free to re-open this issue.
