### ISSUE TITLE
Error converting value "failed" to type 'Alpaca.Markets.ConnectionStatus'. Path '[0].status', line 1, position 33.

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#125]
I don't believe this is related to the other issue I posted about but I'm receiving this error message and it looks like an api error to me

![Screenshot_1](https://user-images.githubusercontent.com/3075685/64374954-ddb25d00-cff2-11e9-8adc-1398d307ec47.png)

I apparently receive this error when trying to buy shares of an asset that is listed using the ListAssetsAsync method but is marked as not active. Use the symbol CALI for testing this error

**Comment by OlegRa** [comment]
@ooples You can test fix for this problem in [3.2.4](https://www.nuget.org/packages/Alpaca.Markets/3.2.4) or [3.3.0-beta](https://www.nuget.org/packages/Alpaca.Markets/3.3.0-beta) packages available on NuGet.

**Comment by ooples** [comment]
I believe you fixed it because I haven't been able to repeat this issue but I would make a suggestion because if you use the same symbol CALI for subscribe events, now nothing happens at all and the user should at least get an exception or message letting them know that CALI is not an active symbol or something instead of nothing happening at all

**Comment by OlegRa** [comment]
Failed subscription attempts should be reported via `OnError` event but right now Polygon.io API never send `failed` status messages (at least on staging environment) for invalid subscriptions for inactive (or even invalid) contract names. So we unable to detect failed subscription on client side now. Maybe it's only staging issue and production system reports failed subscription as expected.

**Comment by OlegRa** [comment]
I close it for now after 2 weeks of inactivity. If problem still exist in latest version of SDK feel free to re-open this issue.
