### ISSUE TITLE
Feature Request: Include Extended Trading Hours Info

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#126]
You can get the regular trading hours information for IsOpen, NextOpen, NextClose in the GetClockAsync() method but I would like to receive that same information for extended market hours as well in case a user like myself wants to trade during extended hours

**Comment by OlegRa** [comment]
@ooples Please, use general Alpaca [feature request](https://forum.alpaca.markets/c/alpaca/feature-requests) interface for requesting new features not available in Alpaca API. For instance your request already reported [here](https://forum.alpaca.markets/t/clock-api-and-extended-hours/118/2) and has answer about availability. This SDK just .NET facade for original REST/WS APIs and we unable to add features which is not provided by these underlying APIs.
