### ISSUE TITLE
Add `Disconnected` event into `SockClientBase` class

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#127]
Digging further into this issue seems to point to the issue with the underlying socket losing connection for whatever reason but the existing api code makes it impossible to know when this happens. I suggest that you include the underlying socket's disconnected event in the api so the user can reconnect and authenticate once the socket is disconnected. You implement the connected event but not the disconnected event

_Originally posted by @ooples in https://github.com/alpacahq/alpaca-trade-api-csharp/issues/123#issuecomment-528880487_

**Comment by ooples** [comment]
Do you have an eta on when you will get this fix done? It is my biggest issue that I have run across so far

**Comment by OlegRa** [comment]
I'll try to do it in 3.3.0-beta this weekend and back port to 3.2.x beginning of next week.

**Comment by OlegRa** [comment]
@ooples I've decided to make final [3.3.0](https://www.nuget.org/packages/Alpaca.Markets/3.3.0) release with this feature. You can use `SocketClosed` event now for handling underlying web socket disconnections. Unfortunately, right now it's not possible to know exact reason of disconnection from event handler but maybe in future major releases this information will be available.

**Comment by OlegRa** [comment]
I close it for now after 2 weeks of inactivity. If problem still exist in latest version of SDK feel free to re-open this issue.
