### ISSUE TITLE
No support for PATCH requests in HttpClient

### ISSUE THREAD

**Issue by ttt733** [alpacahq/alpaca-trade-api-csharp#129]
Alpaca's added some new PATCH endpoints -
https://docs.alpaca.markets/api-documentation/api-v2/orders/#replace-an-order
https://docs.alpaca.markets/api-documentation/api-v2/account-configuration/

I was looking into ways to add these to the SDK, but it looks like [PATCH requests weren't added until 2.1](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.patchasync?view=netstandard-2.1#applies-to). Is there any particular workaround we should use to support these, or do we need to look into upgrading?

**Comment by OlegRa** [comment]
@ttt733 Yes, it's not supported out-of-box until .NET Core 3.0 (still in preview now) and I'm not sure at which version of full .NET Framework it will be available. But fortunately there is a workaround for creating custom HTTP verbs in .NET - I can implement one of these methods or all of them today and send you PR for review.

**Comment by OlegRa** [comment]
@ttt733 In any case we have to add account configuration endpoints support into SDK. I'll create separate issue for this task.

**Comment by OlegRa** [comment]
@ttt733 Another big problem is current SDK design - for type safety methods never return deserialized JSON objects directly - only via read-only interfaces. But now we need setters at least for some properties in `IOrder` interface and I'm not sure how to implement it w/o breaking current SDK design.

**Comment by OlegRa** [comment]
@ttt733 Please, review my PRs. I will merge both and prepare new release as soon as you will approve changes.

**Comment by OlegRa** [comment]
Can be tested in versions [3.3.2](https://www.nuget.org/packages/Alpaca.Markets/3.3.2) and [3.2.6](https://www.nuget.org/packages/Alpaca.Markets/3.2.6) available on NuGet.
