### ISSUE TITLE
Add PolygonSockClient ctor that takes an auth token

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/alpaca-trade-api-csharp#133]
I'm working on a mobile app that utilizes OAuth however **PolygonSockClient** does not support an `oauthKey`. 

Could we add a constructor that takes just an `oauth` key to the PolygonSockClient similar to the constructor available in the `RestClient`?

**Comment by OlegRa** [comment]
@codebeaulieu Unfortunately, I don't see any option in Polygon.io API specification for providing OAuth credentials for WebSocket authentication. Maybe I miss something or this ability just not mentioned in documents.
@ttt733 Trevor, could you please, check this question with your Polygon.io partners? If it's possible - just provide me information how I can format this authorization request and I'll make all required code changes ASAP.

**Comment by OlegRa** [comment]
I will close it for now. New update for Polygon.io integration coming soon on the back-end. Maybe I will add such an option in the next major release if it will be supported by the back-end.
