### ISSUE TITLE
Change methods parameters passing approach

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#141]
Instead of passing a list of mandatory/optional parameters into methods, we can introduce _parameters object_ types. This types (most probably structs) will encapsulate all data and validation logic for parameters set.

> Wouldn't `startDate` and `endDate` eliminate all confusion? Maybe I'm misunderstanding what the intention is here.
> _Originally posted by @codebeaulieu in https://github.com/alpacahq/alpaca-trade-api-csharp/issues/140#issuecomment-551810168_

**Comment by OlegRa** [comment]
@OlegRa I want to add new methods and related configuration objects into the upcoming 3.5.0 release and mark old constructors with the `Obsolete` attribute (warning level) for a more smooth transition.

**Comment by tclzcja** [comment]
Just to double confirm, are we talking about something like this in JavaScript?

`
function method({
  keyId = null,
  secretKey = null
})
`

And of course in C# we use a struct or something, as you've mentioned.

**Comment by OlegRa** [comment]
@tclzcja Yes, you've got it right - this temporary object can affect performance but most probably you'll create them only once and re-use for future calls (for classes) or JIT will eliminate unnecessary copying (for structs).

**Comment by tclzcja** [comment]
@OlegRa got it, thank you!
