### ISSUE TITLE
Add support for asynchronous enumerable

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#144]
After switching to C# 8.0 and enabling .NET Standard 2.1 support in scope of issue #142 we can consider to add another great feature of .NET Core 3.0 - asynchronous enumerable. This is breaking change so we have to do it in version 4.0.x of SDK.

**Comment by OlegRa** [comment]
Another idea that I prefer to put on hold until I'll see real users upvoted for it. The current implementation for REST API endpoints (returns `IReadonlyList<T>') looks more useful. This new interface (`IAsyncEnumerable<T>`) can potentially be used for streaming classes but it's not easy to implement it properly without writing complex (and potentially error-prone) pub-sub code.

**Comment by ooples** [comment]
How do I vote for this?

**Comment by OlegRa** [comment]
@ooples I've added it back into the 4.0 release scope. This release will contain a lot of breaking changes anyway. But I'm not sure we can really implement it properly without async JSON deserialization support. Unfortunately, the JSON.NET library used for deserialization right now doesn't support such a feature so we have to add an alternative serialization layer first.

**Comment by ooples** [comment]
I just saw that you added this into the latest version but do you have a quick example for how to properly implement this? I'm having trouble figuring out how to do it with the Received event handler

**Comment by OlegRa** [comment]
@ooples Sorry, I don't have enough time now for updating the Wiki with examples for new/changed features. The idea is simple - you just wrap the subscription into the enumerable, not just an event. The usage can look like this:

```cs
var subscription = polygonStreamingClient.GetTradeSubscription("GOOG");
polygonStreamingClient.Subscribe(subscription);

await foreach(var trade in subscription.AsAsyncEnumerable())
{
   // Handle each trade here
}
```

As you can see you have to store the `subscription` object somewhere outside this method for unsubscribing later. Other good ideas are adding the cancellation token, and configure awaiting behavior according to your usage pattern.

Maybe the `Subscribe` and `Unsubscribe` calls should be part of this wrapper but in this case, we have to send into extension method not only subscription event but client instance itself and it's not good from a design perspective.

**Comment by ooples** [comment]
I feel silly because I thought it would be like this at first but second
guessed myself and got confused trying to get the event handlers to work
with the AsyncEnumerable. Can't we utilize the using keyword with the
subscription or does that not work with async enumerables?

**Comment by OlegRa** [comment]
@ooples So you want to implement something like this:

```cs
var subscription = polygonStreamingClient.GetTradeSubscription("GOOG");
await using disposableSubsrciption = subscription.AsAsyncDisposable();
await foreach(var trade in subscription.AsAsyncEnumerable())
{
   // Handle each trade here
}
```

I'm not sure it will work as expected but I can try to implement something like this later this week.

**Comment by ooples** [comment]
Yeah it was just an idea I had for how to handle disposal a bit better.
Also I don't see many people utilizing the unsubscribe method and instead
just disposing everything at the end of the market hours so maybe a
redesign is in order for version 6. Just a thought

**Comment by ooples** [comment]
Either way I feel like I'm doing something wrong or I found a bug because I
implemented the async enumerable example to replace the received event and
I'm getting price updates but it is blocking all other threads. Received
event is working as intended btw

**Comment by ooples** [comment]
@OlegRa I don't know if you received the above bug or if I should create a new issue. Let me know either way

**Comment by OlegRa** [comment]
@ooples I've created a simple test for checking how well work the current implementation. It works fine but you should run your data consuming tasks as separate entities because by default async `foreach` will not move to the next statements until the enumeration completion.

Unfortunately, I still don't have time for creating a more user-friendly example but I hope my test code will be enough for you:

```cs
[Fact]
public async Task TradesSubscriptionWorks()
{
    using var client = _clientsFactory.GetAlpacaDataStreamingClient();

    await client.ConnectAndAuthenticateAsync();

    var waitObject = new AutoResetEvent(false);

    var subscription = client.GetTradeSubscription(Symbol);

    var cancellationTokenSource = new CancellationTokenSource();
    cancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(15));

#pragma warning disable 4014
    Task.Run(async () =>
#pragma warning restore 4014
    {
        await foreach (var trade in subscription
            .AsAsyncEnumerable(cancellationTokenSource.Token)
            .ConfigureAwait(false))
        {
            Assert.Equal(Symbol, trade.Symbol);
            waitObject.Set();
        }
    }, cancellationTokenSource.Token);

    client.Subscribe(subscription);

    if (await isCurrentSessionOpenAsync())
    {
        Assert.True(waitObject.WaitOne(
            TimeSpan.FromSeconds(10)));
    }

    client.Unsubscribe(subscription);

    await client.DisconnectAsync();
}
```

I use the `Task.Run` for spawning the separate task and never waits for its completion - it's not a good idea in general so most probably in the final version of this test/example I'll use something like `Task.WhenAll` for ensuring both logical threads completion.

**Comment by ooples** [comment]
Yeah I attempted to do something very similar but made a stupid error when
I used the await keyword for the task and so that was blocking everything
for me. I incorporated some of your code and it is working fine now
