### ISSUE TITLE
Try to use GitHub actions for CI/CD

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#146]
GitHub Actions now is officially released and we can try to use them for CI/CD instead of Appveyor. Porting should be simple because of Actions also use `.yml` for configuring the build process.

**Comment by OlegRa** [comment]
@umitanuki @ttt733 What to do you think about using built-in GitHub Actions for CI/CD instead of external Appveyor service? The current build script can be easy migrated to GitHub format. I can do all steps except one - creating secret stored on GitHub which will provide encrypted NuGet API key for the build process (we've done a similar task for Appveyor before). If you are OK with the existing Appveyor approach - just tell me and I will postpone my activity on this issue.

**Comment by umitanuki** [comment]
I think it makes sense. What should I do to migrate?

**Comment by OlegRa** [comment]
@umitanuki You should do just two actions:

- Temporary disable current CI/CD running on Appveyor under `alpacahq-bot` account
- Generate new GitHub secret named `NUGET_API_KEY` using Settings -> Secret tab for this repo and real NuGet key which I've sent you via email

As soon as you'll complete these steps I do the rest.

**Comment by OlegRa** [comment]
@umitanuki @ttt733 Any updates about this ticket? Have you received my email with NuGet API key?

**Comment by OlegRa** [comment]
@umitanuki @ttt733 Thanks a lot for your support! Now we can remove Appveyour build definition completely - the last release 3.4.1 was built on GitHub automatically and published on NuGet just by pushing version tag.
