### ISSUE TITLE
The server doesn't send information about replaced order.

### ISSUE THREAD

**Issue by ElektroMech** [alpacahq/alpaca-trade-api-csharp#149]
When I am trying to replace some 'limit' order (change only price) by using 'PatchOrderAsync' method, the server sends me 'Replaced' event with old order and old price.

**Comment by OlegRa** [comment]
Sorry, but I'm unable to help you with this problem. I have no access to Alpaca back-end and just support this client-side SDK. If the server works incorrectly - just report it for the Alpaca support team not here on GitHub.
