### ISSUE TITLE
Maybe use "usingPaperAccount" bool instead of "alpacaRestApi" for RestClient constructor

### ISSUE THREAD

**Issue by tclzcja** [alpacahq/alpaca-trade-api-csharp#155]
Hi there, first of all thanks for all the great works!

Currently the constructor signature for Alpaca.Markets.RestClient looks like:

`RestClient(string keyId, string secretKey, string alpacaRestApi = null, ...)`

And AFAIK the only correct values for the alpacaRestApi are two URLs listing somewhere in the online documents: "api.alpaca.markets" for Live account and "paper-api.alpaca.markets" for Paper.

So I just wonder can we simply have a "bool userPaperAccount = true" parameter in the constructor? In that case the real values of the URL are transparent. Since I'm using the SDK instead of building my own HTTP Rest agent, I think real URL should fade behind abstraction.

Anyway, thanks again for the great work on the SDK!

**Comment by OlegRa** [comment]
@tclzcja In fact there are several non-public environments that used mostly for testing during development so boolean flag is not enough but I'll think how we can use both approaches in scope of issue #106 implementation.

**Comment by tclzcja** [comment]
@OlegRa ah I see, that make sense. Thank you!
