### ISSUE TITLE
Exception in ListAccountActivitiesAsync 

### ISSUE THREAD

**Issue by pratttrader** [alpacahq/alpaca-trade-api-csharp#159]
Not sure if I can post issues here, but I'm using this in my own application.  Everything seems to work good except for ListAccountActivitiesAsync.  Await alpacaClient.ListAccountActivitiesAsync()...returns exception:  {"Error converting value ""20191226025220444::4r588a54-4788a55aa-f2ed-e455ddfr666"" to type 'System.Guid'. Path '[0].id', line 1, position 64."}.

**Comment by OlegRa** [comment]
@pratttrader You've found the right place for reporting this problem. I'll try to fix it and publish updated NuGet packages ASAP. Thank you for your support!

**Comment by OlegRa** [comment]
@pratttrader You can test fix in package version [3.4.2](https://www.nuget.org/packages/Alpaca.Markets/3.4.2) available on NuGet (or you can use [3.3.7](https://www.nuget.org/packages/Alpaca.Markets/3.3.7) if you still rely on 3.3.x stream).

**Comment by pratttrader** [comment]
Thank you...that works now.  FYI, I can't pass in anything for ActvityTypes, that works...so I'm leaving it empty and filtering after the return using ActivityType..which is fine for me, but just want to let you know.

**Comment by OlegRa** [comment]
@pratttrader You can test fix in package version [3.4.2](https://www.nuget.org/packages/Alpaca.Markets/3.4.2) available on NuGet (or you can use [3.3.7](https://www.nuget.org/packages/Alpaca.Markets/3.3.7) if you still rely on 3.3.x stream).

I've fixed (I hope) problem with the activities type list in `ListAccountActivitiesAsync` method - you can try to pass a list of activities types into this method and check how this fix works. Also, I've added an overloaded version of this method with a single mandatory string argument - using this method you can request all activities of this single type.

**Comment by OlegRa** [comment]
@pratttrader Could you please close this issue if the problem was fixed.

**Comment by pratttrader** [comment]
good
