### ISSUE TITLE
Order Side Issue

### ISSUE THREAD

**Issue by pratttrader** [alpacahq/alpaca-trade-api-csharp#161]
According to documentation and your implementation,  there is Buy and Sell order side....but I did a short sale that seems to have been processed as "sell_short" so when requesting Account Activities this error was generated: "{"Error converting value ""sell_short"" to type System.Nullable`1[Alpaca.Markets.OrderSide]'. Path '[1].side', line 1, position 438."}

**Comment by OlegRa** [comment]
Hi @ttt733 and @umitanuki - this issue looks very similar for me. Most probably it's just another form of #95 and #96 issues. It would be nice if you'll check it on the back-end side. I'll add custom deserializer for the `OrderType` enum - it will treat all "unknown" types as sell orders. It will prevent us from seeing such strange exceptions in the future.

**Comment by pratttrader** [comment]
Yes, this is the same issue.  Are you in touch with ALPACA directly, or do just you go off the API documentation?  It would be nice if they did a BUY_OPEN, SELL_OPEN, BUY_CLOSE, SELL_CLOSE...that would cover everything.  Or maybe did a OrderAction {Open, Close} and then the OrderSide {Buy, Sell}.  But just having Buy, Sell is not very precise or helpful.

**Comment by OlegRa** [comment]
@pratttrader I have contacts with Alpaca guys but I'm unable to control the development of back-end features. I suggest you writing proposal on the official Alpaca site for your idea and explain the limitations of the current solution in detail.

I'm working on the proper fix for this issue right now and will publish updated packages on NuGet soon.

**Comment by pratttrader** [comment]
I just posted an issue on their support page for this.

**Comment by OlegRa** [comment]
@pratttrader You can test fix in package version [3.4.2](https://www.nuget.org/packages/Alpaca.Markets/3.4.2) available on NuGet (or you can use [3.3.7](https://www.nuget.org/packages/Alpaca.Markets/3.3.7) if you still rely on 3.3.x stream).

**Comment by pratttrader** [comment]
I'm still getting this exception when doing short sale...when requesting AccountActivity w/ 3.4.3:
{"Error converting value ""sell_short"" to type 'System.Nullable`1[Alpaca.Markets.OrderSide]'. Path '[1].side', line 1, position 440."}.

ALPACA really needs to fix this.

**Comment by OlegRa** [comment]
Unfortunately, I'm unable to fix it right now. I'll check this problem as soon as I return back to home from my New Year trip. @pratttrader If you will send me a full exception stack it would be very helpful.

**Comment by pratttrader** [comment]
That's cool.  It's no hurry...just an FYI.
[exception.txt](https://github.com/alpacahq/alpaca-trade-api-csharp/files/4013177/exception.txt)

**Comment by OlegRa** [comment]
@pratttrader This problem should be fixed in version [3.4.4](https://www.nuget.org/packages/Alpaca.Markets/3.4.4) available on NuGet. Please, test and close if the problem was fixed.
