### ISSUE TITLE
SockClient Authentication

### ISSUE THREAD

**Issue by pratttrader** [alpacahq/alpaca-trade-api-csharp#162]
I'm new to Alpaca, testing the platform for potential use...moving from a different broker.  I'm not new to .NET programming.  

I didn't really read ALL of the documentation prior to testing, but apparently I've been using v1 of the API because my URL didn't include "/v2".  At least that's how I read it.

Using the URL with "/v2"...the SockClient hangs when calling .ConnectAndAuthenticate().Wait()...it seems like it's not authenticating me.

The RestClient works fine..from what I can tell at this point.

Have you seen this happening?  Any ideas on what might be happening?  I notice that your examples don't use "/v2".

**Comment by OlegRa** [comment]
@pratttrader Could you please provide the exact address that you use for SockClient initialization? You can use Alpaca streaming for any account type and Polygon streaming only for brokerage accounts. In general, you shouldn't specify the API version number in URLs - there is a special argument in RestClient constructor for this task. You can use the address provided in usage examples application - it should work for both paper-only and brokerage accounts. The upcoming version of SDK (3.5.0) will contain special static class `Environment` with appropriate values for API base URLs on different environments - you can check these values on the `development` branch using GitHub.

**Comment by pratttrader** [comment]
per Alpaca's specifications:  "The endpoint host name will be the same as v1 (api.alpaca.markets/paper-api.alpaca.markets) but with different path (“/v2”)."....so I use "https://paper-api.alpaca.markets/v2/".  I don't use Polygon, so this is only for order updates.  But I can't even get to that point, process hangs at 

  alpacaSock = new SockClient(ALPACA_Key, ALPACA_Secret, ALPACA_URL);

 alpacaSock.ConnectAndAuthenticateAsync().Wait();  [hangs here, no further processing)

but if I use "https://paper-api.alpaca.markets/" as the URL, it's fine.

**Comment by pratttrader** [comment]
As I think about it more, some background might help.   I have a desktop application.  Yesterday I was reading online info from ALPACA and saw the text about using "/v2/" on the URL which I didn't see before.  So I changed my URL to conform.  The Sock streaming stopped working totally.  Orders were going in and getting executed via REST, but the order stream was dead.  So then I started poking around in your GitHub code and saw that in your examples, you are using ConnectAndAuthenticateAsync, while I'm using ConnectAsync,  so I changed to using that...and that's when I noticed that my code was hanging at that line indicated in previous comment.  If I use ConnectAsync, the code doesn't hang at connect, but the order stream is not working at all.   I even went back and installed an older version for testing purposes...and that fails also.  In summary, the REST requests are working fine with both v1 and v2.  The streaming is working with v1, but not when using "/v2/" in the URL.  I'm using v3.4.4.

**Comment by OlegRa** [comment]
OK. First thing first: you shouldn't specify API version in any URL used by .NET SDK - the base address is enough information for proper client configuration. By default `RestClient` works with version 2 of API and additional constructor parameter allows you to specify old API version (not recommended).

For `SockClient` class you should also use only base path URL without any version number or `/stream` path so `"https://paper-api.alpaca.markets/"` should works fine. And it works fine according to your message.

Just use the same addresses for both `SockClient` and `RestClient` and don't think about API version.

**Comment by OlegRa** [comment]
And now about the difference between `ConnectAsync` and `ConnectAndAuthenticateAsync` methods of `SockClient` class: second one just call the first one and wait for the `Authenticated` event. So if you specify incorrect endpoint returned task will never be completed.

**Comment by pratttrader** [comment]
Part 1: excellent; thanks for the clarification.

Part 2: looking at SockClientBase class, I figured that out.

So it's adding the "/v2" to the URL that's causing both.

Thanks for the help, and the great work on this.

**Comment by pratttrader** [comment]
closed
