### ISSUE TITLE
PolygonStreamingClient Error: System.InvalidOperationException: Unknown connection status

### ISSUE THREAD

**Issue by scyentyfyc** [alpacahq/alpaca-trade-api-csharp#168]
When running the below code snippet, I get the error `System.InvalidOperationException: Unknown connection status` coming out of the "OnError" event of the PolygonStreamingClient.  It happens after the subscription to MSFT.  If you take out the "Subscribe" line, you won't get the error.  I would just ignore it... but I think it feeds my next issue which is that after about 5 minutes of MSFT aggregates... the web socket closes of its own accord.  Not 100% sure the two are related.

```
using System;
using System.Threading.Tasks;
using Alpaca.Markets;

namespace test_trader
{
    class Program
    {
        static async Task Main(string[] args)
        {
           var polygonStreamingClient = Environments.Live.GetPolygonStreamingClient("Your Key here");
           polygonStreamingClient.OnError += PolygonStreamError;
           polygonStreamingClient.MinuteAggReceived += PolygonStreamMinuteAgg;
           await polygonStreamingClient.ConnectAndAuthenticateAsync();

           polygonStreamingClient.SubscribeMinuteAgg("MSFT");

           await Task.Delay(5000);
        }

        private static void PolygonStreamMinuteAgg(IStreamAgg obj)
        {
            string x = obj.Symbol;
        }

        private static void PolygonStreamError(Exception obj)
        {
            Console.WriteLine(obj.ToString());
        }
    }
}

```

**Comment by OlegRa** [comment]
Hi Steve,

I'm unable to check this issue right now due to weekend but I'll do it ASAP Monday morning.

Socket closing after 5 minutes is an another issue. Please, report it separately and provide more information. Does it close with some exception or just silently stop working?

**Comment by OlegRa** [comment]
I've checked issue with exception reported via `OnError` event - it's not critical and can be ignored. I'll fix this small issue in upcoming releases. I'm unable to reproduce a problem with web socket disconnection on my computer. Please, report it as a separate issue and provide more information about disconnection - error logs, exceptions, etc.

**Comment by scyentyfyc** [comment]
Ok, thanks for the update.  Today, even with this bug (which I still get), everything continued to work fine, so you are right that the two issues must not have been related.  I am not going to submit another issue for the socket closing because I'm not convinced it is an issue yet... it may have been something in my own code.

**Comment by OlegRa** [comment]
@scyentyfyc Please, test it using version [3.5.0](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.5.0) available on NuGet and close if the problem with `OnError` event disappeared.

**Comment by scyentyfyc** [comment]
I reran the code from my original post that was previously failing, and it works now without error.  Thank you.
