### ISSUE TITLE
Added Hourly Aggregated Async?

### ISSUE THREAD

**Issue by jcjurevis** [alpacahq/alpaca-trade-api-csharp#177]
Hello, I was hoping to receive hourly candle data from Polygon and I noticed on their api doc it was a simple change in the path. Would you mind if added a new public task ListHourlyAggregatesAsync with the path containing "hour". This way users can pull minute, hour, and daily candle information from Polygon?

Currently, the PolygonDataClient file in the repository contains two public Tasks of “ListMinuteAggregatesAsync” and “ListDayAggregatesAsync”. I noticed a simple change to the path under the ListMinuteAggregatesAsync task where minute could instead be hour, would conclude my goal! (according to Polygon’s API documentation). Currently the path for the ListMinute is...

path = $“v2/aggs/ticker/{symbol}/range/{multiplier}/minute/{unixFrom}/{unixTo}”,

 and I was hoping for an List Hourly which would contain...

path = $“v2/aggs/ticker/{symbol}/range/{multiplier}/hour/{unixFrom}/{unixTo}”,)

Tell me what you think! Thank you!

**Comment by OlegRa** [comment]
@jcjurevis Thanks a lot for this issue and related PR. I'll review it soon. We have issue #141 and in the scope of this task I'll merge all aggregates-related methods into single one but right now I'm OK with this approach.

**Comment by OlegRa** [comment]
Merged manually (w/o formal PR merge) and available in the version [3.5.3](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.5.3) now. Please, test and close if all works as expected.

**Comment by OlegRa** [comment]
@jcjurevis I'll close this issue right now. If you still have problems related to this method - feel free to re-open this issue and provide more details.
