### ISSUE TITLE
Enhancement Request: Trading Client: Specific Exception Types

### ISSUE THREAD

**Issue by williamsderek** [alpacahq/alpaca-trade-api-csharp#182]
Hi,

Would it be possible to add specific exception types to this package?
For example: Let's say I run a screen and one  of the results is symbol=HEI-A.
I then run GetAssetAsync to determine if this asset is actually tradeable before acting on the asset.
However, instead of getting a result that includes the asset and indicates that it isn't tradeable, AlpacaTradingClient.General.cs produces a 404.  My consuming client, however, doesn't see a 404; instead it only gets a general System.Exception.  When I query the API directly with Postman, however, I get this: 
```
{
    "code": 40410000,
    "message": "asset not found for HEI-A"
}
```
I see this playing out a number of possible ways, but _perhaps_ the easiest is for you to list in your documentation a number of error codes and messages of what they mean that could be produced by the server with a general purpose client exception that can be handled by downstream clients, such as mine. I can then look for a specific error code based on documentation and do something with that like maybe log it as part of general error handling.

Thanks!

**Comment by OlegRa** [comment]
@williamsderek It was part of the original design of SDK but unfortunately, after implementing throttling support on the client-side this feature was broken. I'll fix it in the upcoming release. Thanks a lot for pointing on this problem!

**Comment by OlegRa** [comment]
@williamsderek You can test it in the version [3.5.4](https://www.nuget.org/packages/Alpaca.Markets/3.5.4) available on NuGet. Please, close this issue if the problem fixed in this release.

**Comment by williamsderek** [comment]
Thanks, I think this will do the trick. Now I just need to catch RestClientErrorException instead of Exception in order to get the ErrorCode.
