### ISSUE TITLE
PolygonDataClientConfiguration constructor defaults to wrong endpoint

### ISSUE THREAD

**Issue by gsalaz98** [alpacahq/alpaca-trade-api-csharp#186]
In `PolygonDataClientConfiguration`, the parameterless constructor uses `Environments.Live.AlpacaDataApi` for its endpoint, when it should actually be `Environments.Live.PolygonDataApi`: https://github.com/alpacahq/alpaca-trade-api-csharp/blob/6dc4a363e8871de1e85109730f5d0a9460ecda52/Alpaca.Markets/Parameters/PolygonDataClientConfiguration.cs#L16

Attempts to use the `PolygonDataClient` with the `ListAggregatesAsync` method results in 404s. When forced to use the `Environments.Live.PolygonDataApi` environment, the call succeeds. https://github.com/alpacahq/alpaca-trade-api-csharp/blob/6dc4a363e8871de1e85109730f5d0a9460ecda52/Alpaca.Markets/PolygonDataClient.cs#L148

As far as I'm aware, this affects both the `develop (3.6.0v2)` and `master (3.5.5)` branches

Please let me know if you have any questions.

**Comment by OlegRa** [comment]
@gsalaz98 Please, test the fix in version [3.5.6](https://www.nuget.org/packages/Alpaca.Markets/3.5.6) available on NuGet and close if the problem was solved.

**Comment by gsalaz98** [comment]
Thank you, the issue has been resolved.
