### ISSUE TITLE
ListAggregatesAsync Json failure

### ISSUE THREAD

**Issue by kwcoffee1** [alpacahq/alpaca-trade-api-csharp#192]
In file: PolygonDataClient.cs(Line 168)

        public Task<IHistoricalItems<IAgg>> ListAggregatesAsync(
            AggregatesRequest request,
            CancellationToken cancellationToken = default)
        {
           …….
            return _httpClient.GetSingleObjectAsync
                <IHistoricalItems<IAgg>, JsonHistoricalItems<IAgg, JsonMinuteAgg>>( // line 168
                    FakeThrottler.Instance, builder, cancellationToken);
      }

issue: JSon parsing error, the issue apprears to be:
JsonMinuteAgg is a specified json type but the request is looking up a generic aggregate type
(like minute, hour, day, and etc.)

**Comment by kwcoffee1** [comment]
A screen snapshot
![Picture0001](https://user-images.githubusercontent.com/13096086/77716609-969ab200-6fac-11ea-80c3-db3e7e6119e2.png)

**Comment by scyentyfyc** [comment]
I just started getting this too, and I wasn't getting it before.  I hadn't upgraded since 3.5.0, so I'm wondering if Polygon changed something.  Definitely no "code" in Polygon's documentation on what gets returned from the Aggregates call.

**Comment by OlegRa** [comment]
@kwcoffee1 @scyentyfyc Could you please provide a minimal example that reproduces this problem. I've checked the code and I see that root cause is not in Polygon normal response parsing but instead in error response parsing. Unfortunately, I'm unable to reproduce this issue on my side - the possible root cause may be in input data that SDK sends to Polygon.io REST endpoint.

**Comment by kwcoffee1** [comment]
I created simple demo console app with my Alpaca key:
`
using System;

using Alpaca.Markets;

namespace PolygonTest
{
    class Program
    {
        const string API_KEY = "YOUR ALPACA KEY";

        public static void Main()
        {
            DateTime FromDate = DateTime.Now.AddYears(-1);
            DateTime ToDate = DateTime.Now;
            string Symbol = "SPY";

            var polyData = Environments.Live.GetPolygonDataClient(API_KEY);

            AggregationPeriod period = new AggregationPeriod(1, AggregationPeriodUnit.Minute);
            var AggSet = new AggregatesRequest(Symbol, period)
                .SetInclusiveTimeInterval(FromDate, ToDate);

            var aggs = polyData.ListAggregatesAsync(AggSet).Result;

            Console.ReadKey();
        }
    }
}
`

The debug results: (double click image to enlarge)

![Picture0001](https://user-images.githubusercontent.com/13096086/77809919-e7b7ae00-705f-11ea-8d71-10b71d0269ef.png)

Thanks

**Comment by scyentyfyc** [comment]
I'm going to take myself out of this.  I think my issue may have been something different that I was causing that just happened to coincide with this.

**Comment by kwcoffee1** [comment]
It looks like you are throwing an exception on a successful read in file HttpClientExtensions.cs:

![Picture0002](https://user-images.githubusercontent.com/13096086/77813797-640abb00-7079-11ea-9235-81380091b5c1.png)

**Comment by kwcoffee1** [comment]
Sorry, I found the cause of the issue:
Some how ( I or the download) changed the property In file JsonHistoricalItems.cs line 47:

from: [JsonProperty(PropertyName = "db_latency", Required = Required.Default)]
To:   [JsonProperty(PropertyName = "db_latency", Required = Required.Always)]

So, I changed it back to Required.Default.

Thank you,

Please close this issue.
