### ISSUE TITLE
Bracket Orders

### ISSUE THREAD

**Issue by camerontbelt** [alpacahq/alpaca-trade-api-csharp#195]
https://alpaca.markets/docs/trading-on-alpaca/orders/

I'm trying to understand how to use the Alpaca.Markets library to place a bracket order.

**Comment by OlegRa** [comment]
@camerontbelt I'll prepare C# example for bracket orders and will publish it here and on official [HowTo](https://alpaca.markets/docs/api-documentation/how-to/orders/) page.

**Comment by OlegRa** [comment]
I'm not sure how long will it take to publish a full example on the HowTo page so I've decided to help you immediately. 

For instance, the [breaket order example request](https://alpaca.markets/docs/trading-on-alpaca/orders/) provided in help:
```js
{
  "side": "buy",
  "symbol": "SPY",
  "type": "market",
  "qty": "100",
  "time_in_force": "gtc",
  "order_class": "bracket",
  "take_profit": {
    "limit_price": "301"
  },
  "stop_loss": {
    "stop_price": "299",
    "limit_price": "298.5"
  }
}
```
Translates to the next C# call:
```cs
var order = await client.PostOrderAsync(
    new NewOrderRequest(
            "SPY", 100, OrderSide.Buy, OrderType.Market, TimeInForce.Gtc)
    {
        OrderClass = OrderClass.Bracket,
        TakeProfitLimitPrice = 100M,
        StopLossStopPrice = 299M,
        StopLossLimitPrice = 298.5M
    });
```
I assume that you already have the `client` variable created by the 'GetAlpacaTradingClient` method call.

**Comment by OlegRa** [comment]
@camerontbelt Most probably I'll change the `NewOrderRequest` class a little bit in the future release and the resulting code will look more similar to original JS requestion but the provided code should work fine in the 3.6.x versions of the SDK.

I'll close this issue now. If you need more clarifications - re-open it but I hope you've got a point.

**Comment by adrianbegi** [comment]
The example provided above returns unprocessable entity for me and I can not get any bracket orders to work.

**Comment by adrianbegi** [comment]
I believe because the take profit property is below the price. Got it working.

**Comment by camerontbelt** [comment]
@adrianbegi Yea as of right now no one has any documentation on how to do this. I finally got it working through trial and error. I also noticed you have to use a Market order type as well, and the stop price needs to be above the limit price.
