### ISSUE TITLE
Readme tutorial does not work

### ISSUE THREAD

**Issue by camerontbelt** [alpacahq/alpaca-trade-api-csharp#196]
I followed the readme to get started and had an issue with Alpaca.Markets.Environment.Paper. Paper could not be found. 

I am on 3.6.1 with a .net 3.0 console app.

**Comment by OlegRa** [comment]
@camerontbelt Read it carefully - you should use the `Environments` instead of `Environment` (as it properly stated in the `README.md` file.

**Comment by camerontbelt** [comment]
@OlegRa sorry that was a misspelling on my part, I copied and pasted the code from the example in the readme and it highlighted paper red, not underlined. I’m not sure what else I can do. I notice too there are no tests of any kind that might help illuminate how all this works.

**Comment by OlegRa** [comment]
What IDE do you use? Have you added the `Alpaca.Markets` NuGet package into the project? What is your OS (I've never tested it on MacOS for instance)?

In fact, you can see more examples available in different places:

This repo - [UsageExamples](../tree/develop/UsageExamples) project
Unit tests repo - [Alpaca.Market.Tests](https://github.com/OlegRa/Alpaca.Markets.Tests)
AlpacaDOCS - [HowTo](https://alpaca.markets/docs/api-documentation/how-to/) section C# snippets

**Comment by camerontbelt** [comment]
@OlegRa visual studio on windows 10, latest version of both. And yes I have the nuget package installed in the project.

**Comment by OlegRa** [comment]
@camerontbelt I've checked this scenario on my side and all works fine for me. I've even recorded
a short [screencast](https://file.io/rtnaqq9c) that demonstrates how it looks like on my VM with clean Win10/VS2019 for .NET Core 3.1 console application.

**Comment by camerontbelt** [comment]
@OlegRa I closed all instances of visual studio then opened my solution again, and pasted in the README example and it works now. My instance of visual studio must have been in a weird state, I apologize.
