### ISSUE TITLE
DeletePositonAsync returns a Task<bool> not an Order object as defined in the documentation.

### ISSUE THREAD

**Issue by adrianbegi** [alpacahq/alpaca-trade-api-csharp#209]
In the following documentation https://alpaca.markets/docs/api-documentation/api-v2/positions/

DELETE/v2/positions/{symbol} 

Response
An Order object

However in the current sdk it is.
public async Task<Boolean> DeletePositionAsync

**Comment by OlegRa** [comment]
@OlegRa I'll fix it in the upcoming 3.7.0 release and (probably) will backport fix into the 3.6.x branch too.

**Comment by OlegRa** [comment]
@adrianbegi You can test it in the [3.6.4](https://www.nuget.org/packages/Alpaca.Markets/3.6.4) release available on the NuGet. Please, check the newly added method and if all works fine close this issue.

**Comment by adrianbegi** [comment]
@OlegRa Thank you, I see the new method. I can do a final test on Tuesday when markets open.

**Comment by adrianbegi** [comment]
@OlegRa  This has been tested. I will close the issue, thank you.
