### ISSUE TITLE
Providing ClientOrderId for closing positions

### ISSUE THREAD

**Issue by adrianbegi** [alpacahq/alpaca-trade-api-csharp#210]
Is there anyway to supply a clientOrderId when calling DeletePositionAsync? We use custom clientOrderIds to keep track of strategies and there is no way to supply one when closing out a position. Would the only way be to just create a closing order for open position and not use that method?

**Comment by OlegRa** [comment]
@adrianbegi I think it's technically possible on the server-side but it's out of my control. I suggest you ask this question on the Alpaca support forum or on Slack chat.

As a temporary solution, I can suggest you calling the `PatchOrderAsync` method using the `IOrder` object returned by updated version (#209 ) of the `DeletePositionAsync` method.

As soon as REST API will accept a newly proposed parameter you can re-open this issue and I add it support into the 'DeletePositionAsync` method.
