### ISSUE TITLE
Remove deprecated API

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/alpaca-trade-api-csharp#22]
Fundamentals, Bars and Quotes are deprecated.

**Comment by OlegRa** [comment]
@umitanuki It's a breaking change and I prefer to do it as single big task with issue #8 and release new package version 2.0.0-alpha with all changes. As intermediate step we can mark all related interfaces with Obsolete attribute and create 1.2.1 release before start real interfaces removal in version 2.0.0 - it will provide early notice for clients.

**Comment by OlegRa** [comment]
Done in [2.0.0-alpha](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v2.0.0-alpha) release.
