### ISSUE TITLE
Is this API dead?

### ISSUE THREAD

**Issue by mannok** [alpacahq/alpaca-trade-api-csharp#221]
The time now is 2020-07-07 UTC 12:19. I can't connect to the API through this SDK. Is the server dead?

**Comment by OlegRa** [comment]
@mannok It's not a good place for asking such questions - I can answer only about SDK itself not about server availability. By the way, that API do you want to connect - Alpaca or Polygon, REST or streaming? It's hard to answer the question without details about a problem.

**Comment by mannok** [comment]
@OlegRa Sorry for asking that in the wrong place.

I kept using this SDK for a month already, it is used to work fine.  However, it stuck at connection initialization just now.

```
await Environments.Live.GetAlpacaDataStreamingClient(new SecretKey("...", "...")).ConnectAndAuthenticateAsync();
```

p.s. it's fine for other connection. i.e. `await Environments.Live.GetAlpacaStreamingClient(new SecretKey("...", "..."))`

**Comment by OlegRa** [comment]
@mannok I think it would be better to ask this question on Alpaca official support channels like a forum, email, or Slack. Most probably the root cause is on the server-side.

**Comment by mannok** [comment]
Thank you so much @OlegRa
