### ISSUE TITLE
Data streaming API issues with C# SDK (v 3.8.0-beta2)

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#224]
I have following C# code for Alpaca data streaming API (with SDK v3.8.0-beta2) and it seem to work sometimes with paper trading during market hours. But it is flaky. When I restart the code, it starts throwing AuthStatus.Unauthorized error. During off market hours, it never works. Is this the expected behavior for paper trading?

When I switch to **Live** trading by commenting the first line and uncommenting the second line (in below code), it does not work at all. The code hangs on the line with ***await _dataStreamingClient.ConnectAndAuthenticateAsync();*** I can successfully call trading API with live account. There were no issues. I know there is a web socket connection used and if it works for paper trading, it should work for live trading. Right?

Please let me know if I need to do something for this code to work in live trading.

Here is my code:
`		

           _dataStreamingClient = Alpaca.Markets.Environments.Paper.GetAlpacaDataStreamingClient(securityKey);
           //_dataStreamingClient = Alpaca.Markets.Environments.Live.GetAlpacaDataStreamingClient(oAuthKey);

            Console.WriteLine($"Hooking to OnError event ...");
            _dataStreamingClient.OnError += (Exception ex) =>
            {
                Console.WriteLine($"OnError event => Exception: {ex}");
            };

            Console.WriteLine($"Hooking to Connected event ...");
            _dataStreamingClient.Connected += (AuthStatus authStatus) =>
            {
                Console.WriteLine($"Connected event => AuthStatus: {authStatus}");
            };

            Console.WriteLine($"Hooking to SocketClosed event ...");
            _dataStreamingClient.SocketClosed += () =>
            {
                Console.WriteLine("SocketClosed event => Socket closed.");
            };

            Console.WriteLine($"Hooking to SocketOpened event ...");
            _dataStreamingClient.SocketOpened += () =>
            {
                Console.WriteLine("SocketOpened event => Socket opened.");
            };

            await _dataStreamingClient.ConnectAndAuthenticateAsync();

            if (!string.IsNullOrWhiteSpace(symbol))
            {
                var tradeSubscription = _dataStreamingClient.GetTradeSubscription(symbol);

                Console.WriteLine($"Hooking to trade subscription for symbol {symbol} event ...");
                tradeSubscription.Received += (IStreamTrade trade) =>
                {
                    Console.WriteLine($"Trade Streaming: {trade.Symbol}, Exchange: {trade.Exchange}, Price: {trade.Price}, Size: {trade.Size}, TimeUtc: {trade.TimeUtc}, TradeId: {trade.TradeId}, Current Time: {DateTime.UtcNow}");
                };

                Console.WriteLine($"Subscribing to trade for symbol {symbol} ...");
                _dataStreamingClient.Subscribe(tradeSubscription);

                //Quote
                var quoteSubscription = _dataStreamingClient.GetQuoteSubscription(symbol);

                Console.WriteLine($"Hooking to quote subscription for symbol {symbol} event ...");
                quoteSubscription.Received += (IStreamQuote quote) =>
                {
                    Console.WriteLine($"Quote Streaming: {quote.Symbol}, Exchange: {quote.AskExchange}, AskPrice: {quote.AskPrice}, AskSize: {quote.AskSize}, BidExchange: {quote.BidExchange}, BidPrice: {quote.BidPrice}, BidSize: {quote.BidSize}, TimeUtc: {quote.TimeUtc}, Current Time: {DateTime.UtcNow}");
                };

                Console.WriteLine($"Subscribing to quotes for symbol {symbol} ...");
                _dataStreamingClient.Subscribe(quoteSubscription);

                //Minute aggregated data for symbol
                var minAggrSubscription = _dataStreamingClient.GetMinuteAggSubscription(symbol);

                Console.WriteLine($"Hooking to minute aggregated data subscription for symbol {symbol} event ...");
                minAggrSubscription.Received += (IStreamAgg agg) =>
                {
                    Console.WriteLine($"Minute Aggregation Streaming: {agg.Symbol}, Open: {agg.Open}, High: {agg.High}, Low: {agg.Low}, Close: {agg.Close}, Average: {agg.Average}, StartTimeUtc: {agg.StartTimeUtc}, EndTimeUtc: {agg.EndTimeUtc}, Volume: {agg.Volume}, Current Time: {DateTime.UtcNow}");
                };

                Console.WriteLine($"Subscribing to minute aggregated data for symbol {symbol} ...");
                _dataStreamingClient.Subscribe(minAggrSubscription);
            }

            int waitTime = 60000;
            Console.WriteLine($"Keeping the data streaming alive for {((float)waitTime) / 60000} minutes ...");
            await Task.Delay(waitTime);
            Console.WriteLine($"Exiting data streaming after {((float)waitTime) / 60000} minutes ...");
			`

The output the I get from the above code is (in live mode):

_Hooking to OnError event ...
Hooking to Connected event ...
Hooking to SocketClosed event ...
Hooking to SocketOpened event ...
SocketOpened event => Socket opened
SocketClosed event => Socket closed._

**Comment by OlegRa** [comment]
@rudeGit The Alpaca data API (both paper and live) doesn't work during off-market hours. I'm not sure about OAuth authentication support for Alpaca Data Streaming API - I've never tried it before. Ask Alpaca support about this scenario. And try to connect using key/secret pair on the live environment for checking connection status.

**Comment by rudeGit** [comment]
@OlegRa: I updated my code to use security key (for live account) for live trading data streaming. I just tried both paper and live trading data streaming during market hours. Both are now reporting Unauthorized. The paper environment used to work sometimes during market hours but now it does not work at all. Not sure what else should I try here. Any suggestions?

**Comment by OlegRa** [comment]
@rudeGit Try to re-generate keys and set up some breakpoints in SDK code - NuGet should download sources and VS (full version not Code) should allow you to debug SDK line-by-line.

**Comment by rudeGit** [comment]
@OlegRa I generated new keys and the live streaming is now working. Did the same with paper streaming as well, it magically started working too. Thanks for the suggestion.
