### ISSUE TITLE
GetPosition reports incorrect percent values

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#225]
When I issued a market order for TQQQ with a quantity of 8 with my paper trading account:

The order seemed to have executed because the _tradingClient.GetPositionAsync(symbol); call succeeds and tells me that my current quantity for the symbol is 8. However when I logged into my alpaca account via browser, there is no trace of this position. What is going on here?

The _tradingClient.GetPositionAsync(symbol) also shows following information:

_|AssetChangePercent|0.0355168369911208|decimal|
|AssetClass|UsEquity|Alpaca.Markets.AssetClass|
|AssetCurrentPrice|123.62|decimal|
|AssetLastPrice|119.38|decimal|
|AverageEntryPrice|123.17|decimal|
|CostBasis|985.36|decimal|
|Exchange|Nasdaq|Alpaca.Markets.Exchange|
|IntradayUnrealizedProfitLoss|3.6|decimal|
|IntradayUnrealizedProfitLossPercent|0.0036534870504181|decimal|_

The AssetChangePercent as well as IntradayUnrealizedProfitLossPercent do not report the % value but only the fraction value.

For example:
The AssetChangePercent (because of the percent in the name) value should be: ((123.62 - 119.38)/119.38)*100 = 3.55… etc. However the current AssetChangePercent is 0.0355… which I think is wrong way to compute.

**Comment by OlegRa** [comment]
@rudeGit I agree with you, maybe the current names can confuse SDK users but I prefer to keep it as is for several reasons:

- These values (`IntradayUnrealizedProfitLossPercent` and `UnrealizedProfitLossPercent`) are received from API and provided to the user unchanged and all other Alpaca SDKs do the same.
- Another important reason for keeping values as is - they can be easily formatted as a percentage value using .NET `P` format specifier.
- Most important reason - it's not possible to apply this change in a backward-compatible way. Of course, I can add new properties with new names and mark old properties as obsolete but I don't see a real reason to do so.
