### ISSUE TITLE
Can you make all clients implement an interface for better testing?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#227]
Currently AlpacaTradingClient, AlpacaDataClient, AlpacaDataStreamingClient classes are sealed and do not implement as interface. Can you make them implement as interface so that it is easier to test strategies? It is good that the return values of methods these clients implement already use interfaces. I think the missing piece is to have all the clients implement interface as well.

**Comment by OlegRa** [comment]
@rudeGit That's a great idea! I can do it even without introducing the breaking changes (I hope) in 3.8 release.

**Comment by OlegRa** [comment]
@rudeGit You can test it in the latest [3.8.0-beta3](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.8.0-beta3) release.

**Comment by rudeGit** [comment]
@OlegRa Thank you for making the interface change. It is working great in the latest 3.8.0-beta3 release.
