### ISSUE TITLE
Update the official Alpaca HowTo examples

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#231]
The official Alpaca HowTo examples contain examples for several tasks implemented using different SDKs - JS/Go/C#/etc. Unfortunately, some examples miss C# editions and users can think that .NET SDK doesn't provide such functions.

**Comment by ooples** [comment]
I'm working on updating the examples as we speak and I sent you an email with a few questions I had

**Comment by OlegRa** [comment]
The PR for Alpaca's official documentation project is [here](https://github.com/alpacahq/user-docs/pull/98). This issue will be closed as soon as this PR merged.
