### ISSUE TITLE
Add Support for Blazor WebAssembly

### ISSUE THREAD

**Issue by liftee** [alpacahq/alpaca-trade-api-csharp#233]
Add support to run Blazor client-side C# code directly in the browser, using WebAssembly.

**Comment by OlegRa** [comment]
@liftee I'm not sure about streaming clients from this SDK - most probably they will not work properly in WASM mode.

**Comment by OlegRa** [comment]
I've checked the simplest `GetClockAsync` API method usage and it works in the default Blazor VS template. There are my steps for testing it:

- Add `Alpaca.Markets` and `Alpaca.Markets.Extensions` NuGet packages (use version `3.9.0-alpha3` and later) into project
- Add the next call into the `Main` method of the Blazor application: 
```cs
builder.Services.AddAlpacaTradingClient(Environments.Paper, new SecretKey(KEY_ID, SECRET_ID));
```
- Add the `@inject IAlpacaTradingClient client` directive into your Razor page
- Add the `clock` field with `IClock` type into the Razor page class
- Use the injected `client` field in the `OnInitializedAsync` method for initializing the `clock` value:
```cs
clock = await client.GetClockAsync();
```
- Use the value of the `clock` field in the page rendering logic:
```cs
@if (clock == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <p>Open: @clock.NextOpenUtc.ToShortDateString();</p>
    <p>Close: @clock.NextCloseUtc.ToShortDateString();</p>
}
```

**Comment by OlegRa** [comment]
@liftee Please, test other scenarios and open other issues if something will not work. If you'll have problems with initial SDK usage in Blazor WebAssembly - ask questions here. If you'll be able to connect to Alpaca REST API using the latest version of SDK from your client-side Blazor code using the suggested approach, please, close this issue.

**Comment by liftee** [comment]
@OlegRa I was able to connect and display the simple Open/Close times with the directions above. 

An exception is thrown when I try to wrap the clock in a function though.

`    public IClock GetClock(IAlpacaTradingClient AlpacaTradingClient)
    {
        IClock clock = AlpacaTradingClient.GetClockAsync().Result;
        return clock;
    }
`
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot wait on monitors on this runtime.
System.Threading.SynchronizationLockException: Cannot wait on monitors on this runtime.
  at (wrapper managed-to-native) System.Threading.Monitor.Monitor_wait(object,int)
  at System.Threading.Monitor.ObjWait (System.Boolean exitContext, System.Int32 millisecondsTimeout, System.Object obj) <0x3ee9330 + 0x00046> in <filename unknown>:0 

I will follow the Alpaca.Markets.Extensions NuGet package updates.

**Comment by OlegRa** [comment]
@liftee This is [expected behavior](https://github.com/dotnet/aspnetcore/issues/22400) for single-threaded implementation of CLR used in Blazor. How you can wait for something if you have only one thread? Just design your code in a truly async way and never use `Result` or `Wait` on `Task` objects directly.
