### ISSUE TITLE
.NET Core IIS issue, need help ASAP

### ISSUE THREAD

**Issue by zhorakiev** [alpacahq/alpaca-trade-api-csharp#241]
I am just trying to capture the alert from the trading view chart and process the marketplace order. So I am using razor ASP.NET Core page. Everything is fine when I debug it in IIS express (localhost) in Visual Studio - https://prnt.sc/uu7ad3, but when I publish and run it in virtual directory in Windows IIS, it is not placing orders in Alpaca, same code....  So the code looks like that:

```cs
public async void OnGet()
{
    try
    {
        var alpacaTradingClient = Environments.Paper.GetAlpacaTradingClient(new SecretKey(API_KEY, API_SECRET));
        var order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest("XOM", 133, OrderSide.Buy, OrderType.Market, TimeInForce.Day) { });
    }
    catch (Exception ex)
    {
        ErrorMessage = ex.ToString();
    }
}

public async void OnPost()
{
    try
    {
        var alpacaTradingClient = Environments.Paper.GetAlpacaTradingClient(new SecretKey(API_KEY, API_SECRET));
        var order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest("XOM", 133, OrderSide.Buy, OrderType.Market, TimeInForce.Day) { });
    }
    catch (Exception ex)
    {
        ErrorMessage = ex.ToString();
    }
}
```

**Comment by OlegRa** [comment]
@zhorakiev I need more information about this issue:

- What is your target .NET and ASP.NET Core versions? What version of Alpaca .NET SDK do you use?
- What exactly happened in IIS mode - do you observe exception, or call just never completed, or returns unexpected result?
- Could you enable HTTP traffic logging for your application and check the raw request/response data for this REST call?

**Comment by zhorakiev** [comment]
ASP.NET Core 3.1
So in the IIS express, while debugging, it works, I am able to send the order and Alpaca records it
When I deploy to windows, I post it into http://MYIP/corealpaca?NUMBEROFSHARES=61&TICKER=XOM&SIGNAL=BUY and keeping hardcoded values, just like in the example. I am not receiving any requests yet, I just hardcoded number of shares, ticker and buy signal on both post and get. Windows is simple AWS windows 2019 server. Firewall is off. Also when I run code on the server, attaching actual IIS, it does not trigger post, only get.... Nothing changed, just standard AWS install...

**Comment by zhorakiev** [comment]
in logging, requests are coming fine 

#Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2020-10-06 18:32:13
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2020-10-06 18:32:13 MY IP POST /corealpaca NUMBEROFSHARES=10&TICKER=MSFT&SIGNAL=BUY 80 - 52.32.178.7 Go-http-client/1.1 - 400 0 0 977
2020-10-06 18:32:16 MY IP POST /corealpaca NUMBEROFSHARES=10&TICKER=FB&SIGNAL=BUY 80 - 52.32.178.7 Go-http-client/1.1 - 400 0 0 65

**Comment by zhorakiev** [comment]
OK I converted into framework 4.5 to make it easier, now when I go to the browser its, registering a sale, but for some reason its not working when alert system doing http post (webhook) to that same URL that's in my browser... Am I missing something?

  protected async void Page_Load(object sender, EventArgs e)
        {
            try
            {

                long lNumShares = long.Parse(Request.QueryString["NUMBEROFSHARES"].ToString().Trim());
                string Ticker = Request.QueryString["TICKER"].ToString().ToUpper().Trim();
                string Signal = Request.QueryString["SIGNAL"].ToString().ToUpper().Trim();

                var alpacaTradingClient = Environments.Paper.GetAlpacaTradingClient(new SecretKey(API_KEY, API_SECRET));




                if (Signal == "BUY")
                {

                    var order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest(Ticker, lNumShares, OrderSide.Buy, OrderType.Market, TimeInForce.Day) { });
                }
                else
                { 
                    
                    var order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest(Ticker, lNumShares, OrderSide.Sell, OrderType.Market, TimeInForce.Day) { });
                }


                
            }
            catch (Exception ex)
            {
                lblalpacaerror.Text = ex.ToString();
            }
        }
    }

**Comment by OlegRa** [comment]
@zhorakiev What does it mean 'it's not working when alert system doing HTTP POST'? Your browser request page using the GET command if you want to implement a POST command handler for the same route you have to do it separately.

AFAIU your issue is not related to SDK itself it's related to your ASP.NET application. If some requests not handled properly by ASP.NET configuration it's not a problem of SDK. If you get an exception during the SDK call - send me information about this exception and I'll try to help. But I'm unable to help you with your server code.

**Comment by zhorakiev** [comment]
OK here it is, ASP.NET 4.5 its sending JSON post to that page, page is storing data in the database and same issue, it is not executing order - var order = await alpacaTradingClient.PostOrderAsync for some reason.

  protected async void Page_Load(object sender, EventArgs e)
        {
            Signal jsignal = new Signal();
            string s = string.Empty;
            string[] st;


            try
            {

               


                try
                {
                    string[] data = new StreamReader(Request.InputStream).ReadToEnd().Split(',');
                   
                   

                    for (int i = 0; i < data.Length; i++)
                    {
                        s = data[i].ToUpper().Trim();
                        st = s.Split('=');

                        if (st[0].ToUpper().Trim() == "SIGNAL")
                            jsignal.ISBUYORSELL = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "EXCHANGE")
                            jsignal.EXCHANGE = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "TICKER")
                            jsignal.TICKER = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "PRICE")
                            jsignal.PRICE = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "VOLUME")
                            jsignal.VOLUME = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "OPEN")
                            jsignal.OPEN = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "CLOSE")
                            jsignal.CLOSE = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "HIGH")
                            jsignal.HIGH = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "LOW")
                            jsignal.LOW = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "TIME")
                            jsignal.TIME = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "TIMENOW")
                            jsignal.TIMENOW = st[1].ToUpper().Trim();

                        if (st[0].ToUpper().Trim() == "NUMBEROFSHARES")
                            jsignal.NUMBEROFSHARES = st[1].ToUpper().Trim();



                        
                    }

                    SQLServerUserDAL.InsertStream(jsignal);

                }
                catch (Exception ex)
                {
                    SQLServerUserDAL.LogErrorToDB(ex.ToString());
                }




                var alpacaTradingClient = Environments.Paper.GetAlpacaTradingClient(new SecretKey(API_KEY, API_SECRET));




                if (jsignal.ISBUYORSELL == "BUY")
                {

                    var order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest(jsignal.TICKER, long.Parse(jsignal.NUMBEROFSHARES), OrderSide.Buy, OrderType.Market, TimeInForce.Day) { });
                }
                else
                { 
                    
                    var order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest(jsignal.TICKER, long.Parse(jsignal.NUMBEROFSHARES), OrderSide.Sell, OrderType.Market, TimeInForce.Day) { });
                }


                
            }
            catch (Exception ex)
            {
                SQLServerUserDAL.LogErrorToDB(ex.ToString());
            }
        }

**Comment by zhorakiev** [comment]
I found solution in .NET framework 4.5... Not sure why later frameworks and .NET core did not place orders in Alpaca. Now at least I was able to make it work. 

I wish you have another WEB project as part of the usage cases.
