### ISSUE TITLE
Add support for the alpaca-proxy-agent project

### ISSUE THREAD

**Issue by shlomikushchi** [alpacahq/alpaca-trade-api-csharp#243]
The WebSocket connection is limited to 1 connection per account. For that exact purpose, this [project](https://github.com/shlomikushchi/alpaca-proxy-agent)  was created (follow README to learn more on how to run it locally)

Then, route the WebSocket to point to the local container's URL (e.g `ws://127.0.0.1:8765`) to be able to use it.

**Comment by OlegRa** [comment]
@shlomikushchi I've added the discussed support for the overriding streaming URLs in any environment using the fluent interface call. The URL argument of the `WithProxyForAlpacaDataStreamingClient` and `WithProxyForPolygonStreamingClient` is optional and if it missed system tries to read it from the environment variable and if it missed it will use the default value `ws://127.0.0.1:8765` as a last resort.

If you need a usage example for your documentation page - just tell me and I'll provide you code snippet.

**Comment by shlomikushchi** [comment]
great thanks, looks good!
I will let you know if I need anything else.

**Comment by OlegRa** [comment]
@shlomikushchi So I can close this issue now?

**Comment by shlomikushchi** [comment]
yes

**Comment by ooples** [comment]
@OlegRa Do you think this can be used to test against the data limit exceptions I'm getting? Do you have a usage example for how I can run multiple paper accounts with this code?

**Comment by OlegRa** [comment]
@OlegRa This one will allow you to run several algorithms on a single Alpaca account. AFAIU you have more than 1 account so this approach will not help you.

**Comment by ooples** [comment]
yes I have been wanting to test multiple algorithms per alpaca account

**Comment by OlegRa** [comment]
@ooples Unfortunately, this project is outdated and doesn't support the new Alpaca Data API v2 streaming properly.
