### ISSUE TITLE
Why did I get a signature is invalid (Code = 40110000) error?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#244]
Around US easter standard time, 2020-10-09 03:49:30 PM (Friday):

1. My app was running for a week or so at this point with live trading.
2. My app just placed a sell order to liquidate my position (for a symbol, say, A) successfully.
3. In next 50 milliseconds, my app has checked the status of this just placed order and confirmed that it was successfully executed by the server.
4. It then waited for 15 seconds to check if there were any other outstanding orders for symbol A again. This worked fine.
5. Next, it tried to get the symbol A position by calling GetPositionAsync method.
6. This call first resulted in NotFound error. This is also expected because there was no existing position for symbol A.
7. Next my app invoked IAlpacaDataClient.GetLastTradeAsync method. This resulted in Unauthorized error with message: **_signature is invalid (Code = 40110000)_**
8. Note that when the above call is made, the market is still open.
9. Interestingly I am able to reproduce this even after the market is closed.
10. So I changed the symbol to something else, say, B, the error still reproduced.
11. Then I thought there may be a problem with my oAuth access token. So I got a new access token and retried.
12. It still produced the same error.

Not sure why I received the above error and what it means. Also how do I recover from it (other than retrying the same call)? I do not blindly want to retry without knowing what it means. Would appreciate an explanation.

I was using nuget package version: **3.9.0-beta1** and then **3.9.0-rc2**

Also posted the error at Alpaca forum: https://forum.alpaca.markets/t/why-am-i-getting-signature-is-invalid-code-40110000-error/2959

**Comment by OlegRa** [comment]
@rudeGit This error is server-side and unfortunately SDK unable to do anything useful with it. Shortly speaking - are you able to call any methods of `AlpacaDataClient` class using this OAuth token before this problem occurred?

- If you unable to use your token for this endpoint but it works for the `AlpacaTradingClient` on - it's a token problem. In this case, I suggest you check the token request - most probably it doesn't contain the `data` scope.
- If you can use the `AlpacaDataClient` endpoint before but it stop working right after a particular call - it's a server-side problem and in this case, only Alpaca support can help you.

**Comment by rudeGit** [comment]
I re-generated one more oAuth2 access token and checked if it has data scope or not. It does. Tried calling the same endpoint again with this new token. It still erred with same message. Only AlpacaDataClient calls are failing and AlpacaTradingClient calls are working fine.

I sent an email to support@alpaca.markets with all the details and the forum question link. Hopefully they will tell me what is wrong with my access token. It is weird that it suddenly stops working.

**Comment by rudeGit** [comment]
@OlegRa I found something interesting, possibly a bug.

With 2 clients (AlpacaDataClient and AlpacaTradingClient), I was using 2 different HttpClient instances, 1 for each client. Each client uses a separate security key setting.

My code first set the valid oAuth access token for the trading client and then set the token with key id and key secret for the data client. But the first call I made is the one with data client. The http request inspector tool (fiddler) showed me that the oAuth access token is set and not the key id and key secret.

Next, I changed both of them to use key id and key secret. This time, the data client used the key id and key secret.

Is this intentional? (If so, what is the rational for it) Or Is this a bug?

**Comment by OlegRa** [comment]
@rudeGit I'm unable to reproduce your issue. There is my code snippet (just a simple unit test):

```cs
[Fact]
public void TwoClients()
{
    var dataClient = new HttpClient();
    var dataConfiguration =
        Environments.Paper.GetAlpacaDataClientConfiguration(new OAuthKey("oauth"));
    dataConfiguration.HttpClient = dataClient;
    var data = new AlpacaDataClient(dataConfiguration);

    var tradingClient = new HttpClient();
    var tradingConfiguration =
        Environments.Paper.GetAlpacaTradingClientConfiguration(new SecretKey("id", "secret"));
    tradingConfiguration.HttpClient = tradingClient;
    var trading = new AlpacaTradingClient(tradingConfiguration);

    Assert.NotNull(dataClient.DefaultRequestHeaders.Authorization);
    Assert.False(dataClient.DefaultRequestHeaders.Contains("APCA-API-KEY-ID"));
    Assert.False(dataClient.DefaultRequestHeaders.Contains("APCA-API-SECRET-KEY"));

    Assert.Null(tradingClient.DefaultRequestHeaders.Authorization);
    Assert.True(tradingClient.DefaultRequestHeaders.Contains("APCA-API-KEY-ID"));
    Assert.True(tradingClient.DefaultRequestHeaders.Contains("APCA-API-SECRET-KEY"));
}
```

So authorization headers configured properly for both clients and because this configuration is done in the constructor all subsequent calls should use the same headers.

Could you please share a simple test code that reproduces the problem on your side? It would be very helpful for investigating this issue.

**Comment by rudeGit** [comment]
@OlegRa Sorry, for wasting your time on this one. I have accidentally switched GetPosition call with GetLastTrade call in my code snippet below. It was my fault. There is no bug. I was messing around on how to make this code work. Looks like using the key id and key secret works for data client.

But I found some another anomaly with the server response. Interestingly, the API server throws non-json error at me now for Forbidden error (for example, it throws HTML string at me). Yikes!

`<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
`


        [Fact]
        public async Task KeyTest()
        {
            var liveTrading = true;
            var symbol = "MSFT";

            IAlpacaDataClient dataClient = CreateAlpacaDataClient(liveTrading, accessToken);
            IAlpacaTradingClient tradingClient = CreateAlpacaTradingClient(liveTrading, accessToken);

            var lastTrade = await dataClient.GetLastTradeAsync(symbol);
            Assert.NotNull(lastTrade);

            //var position = await tradingClient.GetPositionAsync(symbol);
            //Assert.NotNull(position);
        }

        private static IAlpacaDataClient CreateAlpacaDataClient(bool liveTrading, string accessToken = null)
        {
            var environment = liveTrading ? Environments.Live : Environments.Paper;
            var dataClientApiEndPoint = environment.AlpacaDataApi;
            SecurityKey securityKey = liveTrading ?
                                            (new OAuthKey(accessToken)) as SecurityKey :
                                            //(new SecretKey(LIVE_KEY_ID, LIVE_SECRET_KEY)) as SecurityKey :
                                            (new SecretKey(PAPER_KEY_ID, PAPER_SECRET_KEY)) as SecurityKey;

            var dataClientConfig = new AlpacaDataClientConfiguration()
            {
                ApiEndpoint = dataClientApiEndPoint,
                SecurityId = securityKey,
                HttpClient = GetAlpacaHttpClient()
            };
            IAlpacaDataClient dataClient = new AlpacaDataClient(dataClientConfig);

            return dataClient;
        }

        private static HttpClient GetAlpacaHttpClient()
        {
            var httpClient = new HttpClient();
            return httpClient;
        }

        private static IAlpacaTradingClient CreateAlpacaTradingClient(bool liveTrading, string accessToken = null)
        {
            var environment = liveTrading ? Environments.Live : Environments.Paper;
            var tradingApiEndPoint = environment.AlpacaTradingApi;
            SecurityKey securityKey = liveTrading ?
                                            //(new OAuthKey(accessToken)) as SecurityKey :
                                            (new SecretKey(LIVE_KEY_ID, LIVE_SECRET_KEY)) as SecurityKey :
                                            (new SecretKey(PAPER_KEY_ID, PAPER_SECRET_KEY)) as SecurityKey;

            var tradingClientConfig = new AlpacaTradingClientConfiguration()
            {
                ApiEndpoint = tradingApiEndPoint,
                SecurityId = securityKey,
                HttpClient = GetAlpacaHttpClient()
            };
            IAlpacaTradingClient tradingClient = new AlpacaTradingClient(tradingClientConfig);

            return tradingClient;
        }

**Comment by OlegRa** [comment]
Again, it's a server-side behavior and I'm unable to do anything useful with this issue on the SDK side. In the ideal world, all endpoints should provide errors in JSON format but look like Alpaca decided to move some authorization checks into NGNIX proxy and reduce real servers workload. Of course, they can customize HTTP 403 response for API endpoints on NGNIX instead of just using the default HTML template. I suggest escalating this issue to Alpaca's support.

**Comment by rudeGit** [comment]
I followed your suggestion. Today, Alpaca finally resolved my issue on their server side.
