### ISSUE TITLE
OrderType.TrailingStop - TrailOffsetInPercent  - Error, String value missing, but not specified what string value

### ISSUE THREAD

**Issue by zhorakiev** [alpacahq/alpaca-trade-api-csharp#249]
I am getting string value missing on the trailing stop order below, but it does not specify what exactly is missing. There not a single example of TrailingStop order.

order = await alpacaTradingClient.PostOrderAsync(new NewOrderRequest(jsignal.SYMBOL, long.Parse(jsignal.NUMBEROFSHARES), OrderSide.Buy, OrderType.TrailingStop, TimeInForce.Day)
 {                                        
      TrailOffsetInPercent = decimal.Parse(ConfigurationManager.AppSettings["TrailOffsetPercent"].ToString())
});

**Comment by OlegRa** [comment]
@zhorakiev Could you please provide the exact exception information (message and stack) - it's hard to investigate such a problem using only the generic description.

**Comment by OlegRa** [comment]
@zhorakiev I'll close this issue due to inactivity. If you still experience the problem using the latest version of SDK - provide the requested information and reopen the issue.
