### ISSUE TITLE
Minor typo in IFundamental

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/alpaca-trade-api-csharp#25]
**DividentsRate** should be **DividendsRate**

https://github.com/alpacahq/alpaca-trade-api-csharp/blob/a3476d527c8b9c69b8338ce277a643e0d62411a1/Alpaca.Markets/Interfaces/IFundamental.cs

**Comment by OlegRa** [comment]
@codebeaulieu Thank you for pointing this. You can fix suggest PR for this simple fix, I will review/merge it and prepare service release but be aware that we will remove this interface and related methods in version 2.0.0 of our SDK. See issue #22 (already closed) for more details.

**Comment by umitanuki** [comment]
Actually, Dividends and Fundamentals were initially part of API, but at the moment they are not. We should remove related API in this library for now.

**Comment by OlegRa** [comment]
Pull request merged and new service release version [1.2.1](https://www.nuget.org/packages/Alpaca.Markets/1.2.1) pushed into NuGet.

**Comment by umitanuki** [comment]
And the interface is going to be removed?

**Comment by OlegRa** [comment]
@umitanuki Yes. It's already removed in version 2.0.0
