### ISSUE TITLE
Feature Request: Allow ListOrdersRequest to be able to list only buy or sell orders

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#251]
I would like to add an additional filter option to ListOrdersRequest to be able to filter by OrderSide such as looking for buy open orders only. I might be wrong of course but I'm not seeing an option to be able to do that

**Comment by OlegRa** [comment]
@ooples There are no such options in the REST API so I'm unable to implement it without client-side processing of results. But I dislike this approach for the next reasons:

- We have to get all orders from the server for such filtering and I don't see any difference between applying the LINQ `Where` method to the returned value on the client-side or in SDK itself.
- I'm unable to implement this feature on the SDK side correctly - if you will add the `Limit` filter to this request who SDK should work? Do requests until the filtered list will not exceed this value?

But I agree with you - it would be nice to have such a filter in the order API so I suggest you open a ticket on the Alpaca support forum. AFAIR they have a special topic for 'requested features`. And as soon as the underlying REST API will support this filter I'll add it into SDK ASAP.
