### ISSUE TITLE
ListOrdersRequest only returns buy orders when RollUpNestedOrders is true

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#252]
I have a strange bug that I noticed when messing with ListOrdersRequest. If you turn on RollUpNestedOrders then it does what it says it is supposed to do and give you the leg information but it also only returns buy orders and when you turn it off it shows both buy and sell orders.

```cs
var openOrders = await alpacaTradingClient.ListOrdersAsync(
    new ListOrdersRequest
    {
        OrderStatusFilter = OrderStatusFilter.Open,
        RollUpNestedOrders = false
    }); // returns both buy and sell open orders

var openOrders = await alpacaTradingClient.ListOrdersAsync(
    new ListOrdersRequest
    {
        OrderStatusFilter = OrderStatusFilter.Open,
        RollUpNestedOrders = true
    }); // only returns open buy orders
```

I have sent you the code I'm using to run this

**Comment by OlegRa** [comment]
@ooples To be honest, I'm not sure it's an SDK problem but I'll check it tomorrow. Just to be sure that I understand the problem correctly I will write it more formally:

- **Initial state:** we have an account without any working (open) orders.
- **Action:** place one buy limit order for symbol `AAPL` for instance and one sell limit order for symbol `MSFT` for example and both orders not executed immediately.
- **Expected result:** the `ListOrdersAsync` returns 2 items regardless of the `RollUpNestedOrders` parameter value.
- **Actual result:** the `ListOrdersAsync` returns 2 items is the `RollUpNestedOrders` equal to `false` and 1 item istead.

Am I right or I miss something important in your description? If I understand it wrong - just put here the minimal code snippet that demonstrates the problem - just the order placement part will be enough for understanding the STR.

**Comment by ooples** [comment]
No you are correct

**Comment by OlegRa** [comment]
@ooples I'm unable to reproduce it on the paper environment using this simple test code (assume that I have 2 orders in the `New` state):

```cs
var orders = await _alpacaTradingClient.ListOrdersAsync(new ListOrdersRequest());

Assert.NotNull(orders);
Assert.Equal(2, orders.Count);

orders = await _alpacaTradingClient.ListOrdersAsync(new ListOrdersRequest { RollUpNestedOrders = false });

Assert.NotNull(orders);
Assert.Equal(2, orders.Count);

orders = await _alpacaTradingClient.ListOrdersAsync(new ListOrdersRequest { RollUpNestedOrders = true });

Assert.NotNull(orders);
Assert.Equal(2, orders.Count);
```

All three call s returns the same collection with 2 open orders (1 buy and 1 sell) as expected. If you can prepare a simple xUnit test that replicates this problem on your side - provide it here and re-open the issue.

**Comment by ooples** [comment]
The bug is caused by the fact that the open buy orders are nested orders and the open sell orders aren't. When you use RollUpNestedOrders = true it seems to me that it is only showing nested orders instead of what it is supposed to do and combine the nested order information inside the multi leg variables.
