### ISSUE TITLE
Does this have support for Bracket orders?

### ISSUE THREAD

**Issue by citestaccount** [alpacahq/alpaca-trade-api-csharp#255]
I was looking through the SDK , but I did not see option to put in a bracket order, is that possible?
https://alpaca.markets/blog/bracket-orders/

**Comment by ooples** [comment]
Yes this supports bracket orders and you can see some great examples at https://alpaca.markets/docs/api-documentation/how-to/orders/

**Comment by OlegRa** [comment]
Thanks, @ooples for the prompt answer! @citestaccount You can always check [Wiki](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Order-Placement#examples-1) for more order placement examples.

**Comment by citestaccount** [comment]
Thanks for the prompt response. This is my first day trying to learn this nuget to use Alpaca
