### ISSUE TITLE
Polygoin.io DataClient

### ISSUE THREAD

**Issue by citestaccount** [alpacahq/alpaca-trade-api-csharp#257]
I noticed that PolygonDataClient.cs file does not have support for all the available endpoints such as 
Snapshot - Single Ticker
Ticker News
and few others, is there a plan to add support for these endpoints for polygoin.io?

**Comment by OlegRa** [comment]
@citestaccount The Polygon.io connector included in this package mostly for historical reasons. Initially, Alpaca didn't provide any streaming/historical data and just partner with Polygon.io for providing it.
I have ideas about splitting the Alpaca and Polygon.io classes into separate assemblies and NuGet packages but right now I have more urgent tasks and have no ETA for this split. Or maybe I'll resurrect my project for the separate .NET Polygon.io connector and later will just re-use it in this SDK. In any case, this SDK will never contain full Polygon.io support.
