### ISSUE TITLE
Take Profit Issue

### ISSUE THREAD

**Issue by lgreenlee** [alpacahq/alpaca-trade-api-csharp#258]
Hello, 

TakeProfitOrder tpo = LimitOrder.Buy("123", 1, 100M).TakeProfit(101);

Yields an incomplete json request body which is rejected by the server because the original limit price of 100M is not specified. The original limit price of the first trade (100M) is null when viewed in the Debugger. Debugger output:

  | Name | Value | Type
-- | -- | -- | --
  | ClientOrderId | null | string
  | ExtendedHours | null | bool?
  **| LimitPrice | null | decimal?**
  | OrderClass | OneTriggersOther | Alpaca.Markets.OrderClass?
  | OrderSide | Buy | Alpaca.Markets.OrderSide
  | OrderType | Limit | Alpaca.Markets.OrderType
  | Quantity | 1 | long
  | StopLoss | null | Alpaca.Markets.JsonNewOrderAdvancedAttributes
  | StopPrice | null | decimal?
  | Symbol | "123" | string
◢ | TakeProfit | {Alpaca.Markets.JsonNewOrderAdvancedAttributes} | Alpaca.Markets.JsonNewOrderAdvancedAttributes
  | LimitPrice | 101 | decimal?
  | StopPrice | null | decimal?
  | TimeInForce | Day | Alpaca.Markets.TimeInForce
  | TrailOffsetInDollars | null | decimal?
  | TrailOffsetInPercent | null | decimal?

Thanks for your help!

**Comment by OlegRa** [comment]
@lgreenlee You can test the fix in the version [3.9.1](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.9.1) already available on the NuGet.

**Comment by lgreenlee** [comment]
Thanks - that fixed it, it is working now!
