### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by lgreenlee** [alpacahq/alpaca-trade-api-csharp#262]
Hi, 

The client seems to throttle requests, which may be by design, however this isn't a soft failure. It needs to be a hard failure that the application then needs to resolve.

I have had many trades which have taken minutes to be transmitted from the API. You can see the progression here:

Later requests
"00:07:16.651177"
"00:07:16.865176"
"00:07:14.391106"
"00:07:09.074717"
"00:07:04.018112"
"00:07:04.865247"
"00:07:04.947636"
"00:07:03.080743"
"00:07:00.440117"
"00:07:00.752954"
"00:07:00.17805"
"00:06:59.870483"

.....

"00:00:06.932148"
"00:00:07.689027"
"00:00:06.187697"
"00:00:07.347814"
"00:00:07.46176"
"00:00:05.565169"
"00:00:04.280995"
"00:00:03.634404"
"00:00:03.789719"
"00:00:03.794224"
"00:00:03.7935"
"00:00:04.740369"
"00:00:04.367127"
"00:00:03.913475"
"00:00:03.614058"
"00:00:00.871766"
"00:00:00.049424"
"00:00:00.055999"
"00:00:00.051759"
"00:00:00.050427"
"00:00:00.049117"
"00:00:00.037908"
"00:00:00.044835"
"00:00:00.053231"
Early requests

Thankfully the paper trade API is a great testing interface!

**Comment by OlegRa** [comment]
@lgreenlee Rate limit is part of Alpaca REST API and SDK should handle it somehow. Retry logic with random delay is useful for most users but I understand that sometimes it's better to fail fast. You already have an ability to control the throttling behavior.

It can be done by changing the `ThrottleParameters` property of the `AlpacaTradingClientConfiguration` class. For example, if you want to fail immediately on any non-success HTTP return code:

```cs
var configuration =
    Environments.Paper.GetAlpacaTradingClientConfiguration(
        new SecretKey(KEY_ID, SECRET_KEY));
configuration.ThrottleParameters = new ThrottleParameters
{
    MaxRetryAttempts = 1
};

var client = new AlpacaTradingClient(configuration);
```

The main disadvantage of the current implementation is the fact that you are unable to control throttling for each method only for the whole client. Another gotcha - you have to set up throttling parameters before the first client instantiation - all subsequent attempts to change throttling parameters will fail with the `InvalidOperaiton` exception.

I know it's not obvious, neither documented and most probably this approach will be changed in the next major SDK version in the scope of issue #237 implementation.

**Comment by OlegRa** [comment]
@lgreenlee I close it due to a long inactivity period. If you still experiencing the problem - just re-open the issue and provide more information.
