### ISSUE TITLE
READ_ME.md code snippet needs to be updated.

### ISSUE THREAD

**Issue by tieje** [alpacahq/alpaca-trade-api-csharp#264]
I'm learning C# through a stock-trading pet project. The code snippet does not work as intended. Several parts are deprecated. It took me an hour, but I got it working. Feel free to copy and paste this code as the new template code snippet for getting started:

```cs
using System;
using Alpaca.Markets;

namespace CHANGE_AS_NEEDED
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = Environments.Paper
                .GetAlpacaTradingClient(new SecretKey("your API key", "your secret API key"));

            var clock = client.GetClockAsync().Result;

            if (clock != null)
            {
                Console.WriteLine(
                    "Timestamp: {0}",
                    clock.TimestampUtc);
            }
        }
    }
}
```

**Comment by OlegRa** [comment]
Thanks a lot, @tieje It's always hard to maintain code snippets that are you unable to compile. I've updated the instructions and now this sample code should compile without any issues.

In the future, you can just propose your changes in form of a pull request.
