### ISSUE TITLE
How to recover from System.Net.Sockets.SocketException (10060)?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#266]
I am using nuget package version 3.9.0-rc3 and in live enviornment.

My program has been running for a week without any issues. Then I suddenly got the following exception:

_System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond._

I am not using ThrottleParameters settings at all. However I do handle the HttpResponseMessage related errors such as Bad Gateway etc. by retrying the requests using Polly library in my own custom HttpClientHandler, which is used HttpClient instance in both AlpacaDataClientConfiguration and AlpacaTradingClientConfiguration instances. This all works good.

The stack trace for the above exception showed that the call originated in Alpaca.Markets.HttpClientExtensions.sendThrottledAsync(HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken, IThrottler throttler) method.

**Questions:**

1. Does the use of ThrottleParameters will handle the retry for the above error?
2. Do you have any suggestions on how to recover from the above exceptions without using the ThrottleParameters settings?
3. Is there a way to use the IHttpClientFactory to address this issue?

Thanks.

**Comment by rudeGit** [comment]
This turned out to be rather simple. I just needed to create another polly retry policy for inner SocketException and check for the error code 10060. Then execute this policy, whose execution body used the previous policy's execution that handles multiple http responses.

**Comment by OlegRa** [comment]
@rudeGit Is it possible to extract your code for handling throttling using the Poly library from your project into the independent 'package' and share it with other users of this SDK? Most users are OK with the current throttling implementation and straightforward #237 implementation can break the backward compatibility for them.

I'm thinking about integrating your approach into the `Alpaca.Markets.Extensions` library instead of adding the new dependency into the main SDK package (at least not in the upcoming 4.0 release). If you don't have enough time for preparing PR with all required changes - just share some code here (if it's possible) and I'll do all the integration work myself.

**Comment by rudeGit** [comment]
@OlegRa Sorry. Just saw your comment. Here is my code. Please modify and use it as you wish. I wrote it as a simple handler.

`    
public class MyAlpacaClientHandlerWithPolly : HttpClientHandler
    {
        const int MaxAttempts = 5;
        TimeSpan StartWaitTime = TimeSpan.FromSeconds(1);
        AsyncRetryPolicy<HttpResponseMessage> _retryResponsePolicy = null;

        const int ConnectionMaxAttempts = 5;
        TimeSpan ConnectionStartWaitTime = TimeSpan.FromSeconds(5);
        AsyncRetryPolicy _retryConnectionPolicy = null;

        AsyncPolicyWrap<HttpResponseMessage> _policyWrap = null;

        public MyAlpacaClientHandlerWithPolly()
        {
            _retryConnectionPolicy = Policy
                .HandleInner<System.IO.IOException>(ioEx =>
                {
                    LogToConsole($"{ioEx}");

                    return ioEx.Message.StartsWith("The response ended prematurely");
                })
                .OrInner<SocketException>(socEx =>
                {
                    LogToConsole($"{socEx}");

                    //There is no point in retry this exception:
                    //  System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
                    //return socEx.ErrorCode == 10061;

                    //However we can retry following exceptions:
                    //  System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                    //  System.Net.Sockets.SocketException (11001): No such host is known.
                    //  System.Net.Sockets.SocketException (11001): The name of the host could not be resolved. Try again later.

                    return (socEx.ErrorCode == 10060 || socEx.ErrorCode == 11001 || socEx.ErrorCode == 11002);
                })
                .WaitAndRetryAsync(
                    ConnectionMaxAttempts,
                    sleepDurationProvider: (retryCounter) =>
                    {
                        var seconds = ConnectionStartWaitTime.Seconds * Math.Pow(2, retryCounter - 1);
                        var waitTime = TimeSpan.FromSeconds(seconds);
                        LogToConsole($"Connection Policy Retry count: {retryCounter}, Waiting for {waitTime.Seconds} seconds before retrying ...");
                        return waitTime;
                    },
                    onRetry: (exception, waitTime, retryCount, context) =>
                    {
                        LogToConsole($"onRetry: Exception: {exception.GetType().Name}; waitTime: {waitTime}, retryCount: {retryCount} ...");
                    }
                );

            _retryResponsePolicy = Policy<HttpResponseMessage>
                .HandleResult(response =>
                    {
                        var statusCode = (int)response.StatusCode;
                        if (statusCode >= 400)
                        {
                            var responseString = response.Content.ReadAsStringAsync().Result;
                            if (!string.IsNullOrWhiteSpace(responseString))
                            {
                                LogToConsole($"Received following response: {responseString}");
                            }

                            LogToConsole($"Received status code: {response.StatusCode}. (Url: {response.RequestMessage.RequestUri}) Checking to see if we need to retry ...");
                            if (response.Headers.RetryAfter?.Delta != null)
                            {
                                LogToConsole($"Retry-After header value is set to {response.Headers.RetryAfter.Delta.Value} seconds. Waiting for this time to elapse (before starting retry iterations) ...");
                                Task.Delay(response.Headers.RetryAfter.Delta.Value).Wait();
                            }
                            return (statusCode >= 500 || statusCode == 429);
                        }
                        else
                        {
                            return false;
                        }
                    }).
                WaitAndRetryAsync(
                    MaxAttempts,
                    sleepDurationProvider: (retryCounter) =>
                    {
                        var seconds = StartWaitTime.Seconds * Math.Pow(2, retryCounter - 1);
                        var waitTime = TimeSpan.FromSeconds(seconds);
                        LogToConsole($"Response Retry count: {retryCounter}, Waiting for {waitTime.Seconds} seconds before retrying ...");
                        return waitTime;
                    },
                    onRetry: (exception, waitTime, retryCount, context) =>
                    {
                        LogToConsole($"onRetry: Exception: {exception.GetType().Name}; waitTime: {waitTime}, retryCount: {retryCount} ...");
                    }
                );

            //Wrap the response policy within the connection policy
            _policyWrap = _retryConnectionPolicy.WrapAsync(_retryResponsePolicy);
        }                

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            //Without connection retry policy
            //return await _retryPolicy.ExecuteAsync(() => base.SendAsync(request, cancellationToken));

            //With connection retry policy
            //return await _retryConnectionPolicy.ExecuteAsync(() => _retryPolicy.ExecuteAsync(() => base.SendAsync(request, cancellationToken)));

            //Execute the policy that wraps the response policy within the connection policy
            return await _policyWrap.ExecuteAsync(() => base.SendAsync(request, cancellationToken));
        }

        private void LogToConsole(string messsage)
        {
            Console.WriteLine($"{DateTime.UtcNow.ToLocalTimeDisplay()}: {messsage}");
        }
    }
`

**Comment by OlegRa** [comment]
Thanks a lot, @rudeGit, it's really helpful. Now I can think about how I can provide both approaches for SDK users in the scope of issue #237.
