### ISSUE TITLE
Duration could not be set as GTC. It switches to Day

### ISSUE THREAD

**Issue by ayushguptacoder** [alpacahq/alpaca-trade-api-csharp#270]
Code being called:
```
newOrderRequest = LimitOrder.Buy(botAlert.Ticker.ToUpper(), quantity, botAlert.LimitPrice)
                            .Bracket(botAlert.TakeProfitPrice, botAlert.StopPrice).WithDuration(TimeInForce.Gtc);
```

Actual request body going out ( found via fiddler)
`{"symbol":"PLTR","qty":178,"side":"buy","type":"limit","time_in_force":"day","limit_price":28.0,"order_class":"bracket","take_profit":{"limit_price":29.0},"stop_loss":{"stop_price":27.0}}`

**Comment by ayushguptacoder** [comment]
I had to move the WithDuration to the base order and not the bracket order.

**Comment by OlegRa** [comment]
@ayushguptacoder Yes, it's a side effect of the last changes in the 3.9.1 and later related to another order sending problems. It's good that you've found the workaround and it works for you. I'll try to find another solution that provides a way for specifying the order properties even for the compound orders themselves not only for the base orders.

**Comment by OlegRa** [comment]
@ayushguptacoder Both approaches should work the same in version [3.9.3](../releases/tag/v3.9.3) and later.

**Comment by OlegRa** [comment]
@ayushguptacoder I close it due to 2 weeks of inactivity. If you still experiencing this issue, feel free to re-open the issue and provide more information.
