### ISSUE TITLE
Change Polygon Streaming Client Subscription Process to Match Alpaca Data Streaming Client

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#271]
This is how you subscribe to all active assets using the Alpaca Data Streaming Client and I want to be able to have the same exact method for the Polygon Streaming Client as well.

```
var priceSubscription = alpacaDataStreamingClient.GetMinuteAggSubscription();
                    priceSubscription.Received += (agg) =>
                    {
                        // handle subscription logic here
                    };
                    alpacaDataStreamingClient.Subscribe(priceSubscription);
```

**Comment by OlegRa** [comment]
@ooples This issue description duplicates issue #137 and I'll close this one as a duplicate. If you want to track progress with this change - subscribe to the original issue updates.

Unfortunately, it's not easy to change the current subscription approach without significant change in internal class implementation and it most probably will be a breaking change so I've decided to move all significant changes into the scope of version 5.0 (next year's version).

So version 4.0 (upcoming soon) will be an LTS version with the current stable interface and 5.0 will be more experimental and most probably will support less target .NET versions/standards in favor of new features/approaches.
