### ISSUE TITLE
IAlpacaStreamingClient Exception thrown

### ISSUE THREAD

**Issue by Ricbun16** [alpacahq/alpaca-trade-api-csharp#275]
Hi Guys,

Just want to give a headsup about a exception that was invoked by IAlpacaStreamingClient.OnError. This happend when I received a ITradingUpdate about a StopLossOrder I had on.

Here is the received Exception:

```
ERROR  21/01/2021 16:46:04,050  TradingAlgo.TradingService.Alpaca.AlpacaTradingService ==>  [7] [InitiateStream]: Alpaca TradingStream threw an Exception: Error setting value to 'TimestampUtc' on 'Alpaca.Markets.JsonTradeUpdate'.
Newtonsoft.Json.JsonSerializationException: Error setting value to 'TimestampUtc' on 'Alpaca.Markets.JsonTradeUpdate'. ---> System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij SetTimestampUtc(Object , Object )
   bij Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
   --- Einde van intern uitzonderingsstackpad ---
   bij Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bij Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bij Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   bij Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   bij Newtonsoft.Json.Linq.JToken.ToObject[T]()
   bij Alpaca.Markets.ActionExtensions.DeserializeAndInvoke[TApi,TJson](Action`1 eventHandler, JToken eventArg)
   bij Alpaca.Markets.AlpacaStreamingClient.handleTradeUpdate(JToken token)
   bij Alpaca.Markets.StreamingClientBase`1.<>c__DisplayClass24_0`1.<HandleMessage>b__0()
   bij Alpaca.Markets.SynchronizationQueue.processingTask()
```

**Comment by OlegRa** [comment]
@Ricbun16 You can test the potential fix in the version [4.0.2-beta](../releases/tag/sdk-4.0.2-beta) available also on NuGet.

This is a pre-release version so use the exact version number if you use CLI or enable pre-release version display if you use GUI. This change is no backward compatible with existing client code that uses the 'ITradeUpdate.TimestampUtc` property but a full backward compatibility cycle will be too expensive for this simple change.

Please test it and provide me an update. If it will work for you I publish a final version of 4.0.2 available for all clients.

**Comment by Ricbun16** [comment]
@OlegRa Thanks for the quick fix! Just updated to 4.0.2 and updated my code with null handeling. Will test in de coming week and let you know.

Nice work on the SDK by the way, it's really straight forward to use!

**Comment by ooples** [comment]
I'm still getting this bug with the latest version. Here is my exception info:

Exception Type:
Newtonsoft.Json.JsonSerializationException

Exception Message:
Error setting value to 'TimestampUtc' on 'Alpaca.Markets.JsonTradeUpdate'.

Exception StackTrace:
   at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target,
 Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValu
e(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract
containerContract, JsonProperty containerProperty, JsonReader reader, Object tar
get)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(
Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty m
ember, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Js
onReader reader, Type objectType, JsonContract contract, JsonProperty member, Js
onContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonS
erializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Alpaca.Markets.ActionExtensions.DeserializeAndInvoke[TApi,TJson](Action`1
eventHandler, JToken eventArg)
   at Alpaca.Markets.SynchronizationQueue.processingTask()

Exception Target Site:
SetValue

Exception Source:
Newtonsoft.Json

Inner Exception Message:
Object reference not set to an instance of an object.

Inner Exception StackTrace:
   at SetTimestampUtc(Object , Object )
   at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target,
 Object value)

**Comment by OlegRa** [comment]
@ooples 5.0.0-alpha1 doesn't contain this fix. It will be re-integrated into 5.0 after @Ricbun16 confirmation that it works fine in the 4.0.2 pre-release version.

**Comment by Ricbun16** [comment]
I’ve not encountered the issue since I updated and made 50+ trades since.
Seems to work great.

Op vr 29 jan. 2021 om 00:13 schreef Oleg Rakhmatulin <
notifications@github.com>

**Comment by OlegRa** [comment]
@Ricbun16 Now you can use the version [4.0.2](../releases/tag/sdk-4.0.2) from NuGet instead of pre-release version.
@ooples  Now you can use the version [5.0.0-alpha2](../releases/tag/sdk-5.0.0-alpha2) from NuGet - it contains fix for this issue.
