### ISSUE TITLE
Is there a way to find if a stock is split on a given day in real time?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#276]
Lets say I had 10 shares of TQQQ prior to today (i.e. before this stock is split). Today the stock is split 1:2, which means my number of shares went up from 10 to 20 with half the price of original. But this information is not available to me in the Alpaca brokerage account until the next day.

My question, is there any method in the SDK that would tell me in real time that a given stock (such as TQQQ) is splitting today so that I can take a meaningful action in my application? I also posted the question at: https://forum.alpaca.markets/t/how-to-detect-stock-split-on-the-day-it-splits-in-the-api/4015.

Would I appreciate if you have a figured out a way to get this info in real time.

**Comment by OlegRa** [comment]
@rudeGit This information available via [Polygon.io REST API endpoint](https://polygon.io/docs/get_v2_reference_splits__stocksTicker__anchor) for subscribers with stock information subscription level. Unfortunately, this endpoint not enabled for Alpaca users. You can discuss this issue with Alpaca support and maybe they will add this information into Alpaca Data API (and I'll in my turn update the SDK ASAP).

**Comment by rudeGit** [comment]
@OlegRa Thanks for the info.
