### ISSUE TITLE
alpha 5 subscribe to polygon realtime data

### ISSUE THREAD

**Issue by jeffwlandry** [alpacahq/alpaca-trade-api-csharp#285]
As I understand it previous to alpha 4, the scheme to get real time polygon data was:
attach a trade event handler to `streamingClient.TradeReceived += eventHandler`
request a subscription for a specific symbol

This meant all the trade events for all the symbols went to the same event handler.

Based on exmaple provided by ooople in issue "not receiving after hours data" there is a new scheme:
create a `subscription = streamingClient.GetTradeSubscription(symbol)`
attach a trade event handler for that specific symbol by `subscription.Received+=eventHandler`
subscribe to the handler by `streamClient.Subscribe(subscription)`

At this point I expect that subscription.subscribed will equal true.  I find it is always false and never hit my event handler.  It seems I am missing some important point here.

I have a stock class with subscribe2TradeDataStream().  This is called when the stock is instantiated.  I have confirmed this is called

```cs
/// <summary>
/// ask the broker for live trading data for this stock
/// </summary>
public override void subscribe2TradeDataStream()
{
    switch (tradePeriod)
    {
        case streamType.trade_alpaca:
            broker.subscribeTrade(ticker);
            break;
        case streamType.minuteAgg_alpaca:
        case streamType.secondAgg_alpaca:
            broker.subscribeMinuteAgg(ticker);
            break;
    }
}
```

Broker class talks to the alpaca c# api.  This is where I attempt to subscribe for this stock.  I have confirmed this is called.

```cs
/// <summary>
/// ask for all trades for specific stock
/// </summary>
/// <param name="ticker"></param>
public override void subscribeTrade(string ticker)
{
    var subscription = polygonStream.GetTradeSubscription(ticker);
    subscription.Received += tradeReceived;
    polygonStream.Subscribe(subscription);
}
```

Using the code for the previous scheme, the broker event handler "tradeReceived" should receive all the trade events for all the stocks, then passes the event to the correct stock instance.

```cs
void tradeReceived(IStreamTrade trade)
{
}
```

I get no events.  I have also tried to subscribe for quotes and aggregates (similar code), but I never get an event.

Any suggestions will be appreciated.

Thank you,
jeff

**Comment by OlegRa** [comment]
@jeffwlandry I have a separate (for some historical reasons) GitHub repo with tests for this SDK package where you can find working examples for most of the public API endpoints. For instance, your case tested by the [TradesSubscriptionWorks](https://github.com/OlegRa/Alpaca.Markets.Tests/blob/118932b85d05626e26f77174b9b22617ffd9c9b8/Alpaca.Markets.Tests/PolygonStreamingClientTest.cs#L24) test case.

I think it has no sense to fix it in this repo because this code is dead due to discontinued Alpaca-Polygon.io integration. I will check it again as soon as I have a working streaming client in the new Polygon.io SDK package.

**Comment by jeffwlandry** [comment]
That's fine.  I will fall back and then wait for polygon.io package.

Thank you,
jeff
