### ISSUE TITLE
Add support for Data v2 stream connection

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#288]
The `AlpacaDataStreaming` client implementation should be changed according to the [new specification](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/real-time/) and supports 2 possible URLs (Basic and Pro subscriptions).

**Comment by FranklyBrandon** [comment]
Glad this is on the backlog already! Came here after seeing Alpaca is migrating to their V2 and wanted to make sure this library was getting updated

**Comment by OlegRa** [comment]
New endpoints support available now in versions [4.1.1-beta](../releases/tag/sdk-4.1.1-beta) and [4.0.5-beta](.../releases/tag/sdk-4.0.5-beta). The [5.0.1-alpha](/releases/tag/sdk-5.0.1-alpha) contains the same changes as well.
These changes still not well tested and anyone who will find issues in the beta/alpha versions should report them here.
