### ISSUE TITLE
Ambiguity between 'IQuoteBase<string>.AskPrice' and 'IQuoteBase<long>.AskPrice'

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#289]
I'm getting the above error when trying to compile the latest version of the api. I'm pretty sure this must be a mistake because I can't understand why ask price would be a string in the first place

**Comment by OlegRa** [comment]
@ooples I'm not sure that I understand you properly. Do you have this problem during the SDK code compilation or in your code, dependent on the SDK?

- In the first case, please, share the exact error output from the compiler (with the file name and line) for investigation.
- In the second case, please, provide a code snippet that generates the error and your version of the C# compiler (at least your target C# and .NET version). Next week I'll re-integrate the latest changes in my separate unit tests project and maybe I'll find and fix this problem by myself. But if you have code that works fine with the previous version of SDK but doesn't compile with the latest one, please share it with exact information about both version numbers.

**Comment by ooples** [comment]
var quoteInfo = await
alpacaDataClient.GetLastQuoteAsync("GOOG").ConfigureAwait(false);
Console.WriteLine(quoteInfo.AskPrice); // error here

**Comment by OlegRa** [comment]
@ooples It's the result of an old (bad) idea of 'generalizing' interfaces for all return objects. I'll try to find the most backward-compatible way for preventing such errors. Most probably fix will be ready by Monday. Right now you can solve it by casting to the `IQuoteBase<long>` interface.

**Comment by ooples** [comment]
I figured it was something like that and I just wanted to bring the error
to your attention
