### ISSUE TITLE
Example programs in alpaca documentation not working for C#

### ISSUE THREAD

**Issue by TonyC1Ward** [alpacahq/alpaca-trade-api-csharp#290]
I'm using .net code as a practise application.

In Get Historical Price and Volume Data

```cs
var bars = await client.GetBarSetAsync( new BarSetRequest("AAPL", TimeFrame.Day) { Limit = 5 });
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IAlpacaTradingClient' does not contain a definition for 'GetBarSetAsync' and no accessible extension method 'GetBarSetAsync' accepting a first argument of type 'IAlpacaTradingClient' could be found (are you missing a using directive or an assembly reference?)	

In Submit Bracket Orders example

```cs
var barSet = await dataClient.GetBarSetAsync(
                 new BarSetRequest(symbol, TimeFrame.Minute) { Limit = 1 });

await tradingClient.PostOrderAsync(
                MarketOrder.Buy(symbol, 1)
                .WithDuration(TimeInForce.Gtc)
                .Bracket(
                    stopLossStopPrice: price * 0.95M,
                    takeProfitLimitPrice: price * 0.94M,
                    stopLossLimitPrice: price * 1.05M));
```

Give error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'tradingClient' does not exist in the current context.
```

Can you advise on how to correct or are these bugs in the api wrapper?

**Comment by OlegRa** [comment]
@TonyC1Ward This method marked as obsolete and removed from SDK by mistake. I'll fix it in the next release ASAP.

**Comment by OlegRa** [comment]
@TonyC1Ward You can try again - just update your `Alpaca.Markets` package up to version `4.1.1` from NuGet.

**Comment by TonyC1Ward** [comment]
Yes, I'll try it later on tonight.  Thanks for looking into it for me.

Cheers Tony

**Comment by TonyC1Ward** [comment]
Hi OlegRa,  

I have reinstalled Alpaca.Markets to version 4.1.1.  Unfortunately I  still have the same errors.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IAlpacaTradingClient' does not contain a definition for 'GetBarSetAsync' and no accessible extension method 'GetBarSetAsync' accepting a first argument of type 'IAlpacaTradingClient' could be found (are you missing a using directive or an assembly reference?).

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'dataClient' does not exist in the current context;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'tradingClient' does not exist in the current context

The code segments I am trying are from the C# examples, cut and paste.

using Alpaca.Markets;

           // Get daily price data for AAPL over the last 5 trading days.
           var bars = await client.GetBarSetAsync( new BarSetRequest("AAPL", TimeFrame.Day) { Limit = 5 });

           Console.WriteLine($"Got order #{order.ClientOrderId}");
            var barSet = await dataClient.GetBarSetAsync(
                 new BarSetRequest(symbol, TimeFrame.Minute) { Limit = 1 });
            var price = barSet[symbol].Single().Close;

           // We could buy a position and add a stop-loss and a take-profit of 5 %
            await tradingClient.PostOrderAsync(
                MarketOrder.Buy(symbol, 1)
                .WithDuration(TimeInForce.Gtc)
                .Bracket(
                    stopLossStopPrice: price * 0.95M,
                    takeProfitLimitPrice: price * 0.94M,
                    stopLossLimitPrice: price * 1.05M));
 

Thanks in advance for looking.

Cheers Tony

**Comment by OlegRa** [comment]
@TonyC1Ward You just get code snippets from different examples and try to run it as a single meaningful piece of code? Maybe this will work with JS or Python (weak-typed dynamic languages) but not with C#. In each example, the variable name has some meaning and type and if you try to call a method of one interface from an instance of another one it will not work. Just use each example as a starting point and adjust it with C# syntax and type checking rules in mind. I've checked all code samples (in automatic mode) on the Alpaca documentation site and they at least compile without any issues.

**Comment by TonyC1Ward** [comment]
Ok thanks for the guidance.  I'll try again.

**Comment by TonyC1Ward** [comment]
I've rebuilt the project from scratch.

It worked first time.

Thanks very much for your help.

Cheers Tony
