### ISSUE TITLE
4.1.1-beta2 reports "barSetRequest will be removed"

### ISSUE THREAD

**Issue by jeffwlandry** [alpacahq/alpaca-trade-api-csharp#291]
4.1.1-beta2 reports BarSetRequest and GetBarSetAsync are obsolete and will be removed in the next API.

I believe I've used all of the v5 versions.  None of them report these are removed.

This is something polygon doesn't provide (nor Interactive Brokers).  Will this be removed without replacement?

Thank you,
jeff

**Comment by OlegRa** [comment]
This one is a duplicate for issue #290 - this method marked as obsolete and removed from SDK by mistake. I'll fix it in next release.
