### ISSUE TITLE
alpha5.0.1-beta2 "await alpacaDataClient.ListHistoricalTradesAsync(request)" erratic

### ISSUE THREAD

**Issue by jeffwlandry** [alpacahq/alpaca-trade-api-csharp#292]
I understand all this is in flux.

Thank you for maintaining as much as possible of the pre-existing historical and real-time schema.

1) Start Visual Studio
2) load my program
3) run my program in debug
4) usually all calls to listHistoricalTradesAsync complete (not the case in beta1)
5) ask program to re-request the same data
6) some call to listHistoricalTradesAsync will fail with "internal server error occurred"

adding 2 second waits between successive calls had no effect.  Asking for fewer items returned had no effect.

I assume this is probably from the end point rather than the c# api.  

for what it's worth,
Jeff

**Comment by OlegRa** [comment]
@jeffwlandry According to [this page](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/#public-beta-status) the new Alpaca Data API v2 is in public beta status so most probably these errors are server-side related.
