### ISSUE TITLE
Using Same Api Key Info for 2 different Alpaca accounts doesn't give error

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#298]
I'm not 100% sure if this is a feature or a bug but if you use the same exact api and secret info for 2 different alpaca accounts, you don't get an error when using the connect and authenticate method. The expected result would be to have the connect and authenticate run a check on the account name. It obviously runs this check because after the market opens I suddenly get the api authentication error

**Comment by OlegRa** [comment]
@ooples It's not clear to me how you can "use the same exact API and secret info for 2 different alpaca accounts" at all. If you have two separate Alpaca accounts (I'm sure it's possible for paper trading using different emails) each one will have independent key/secret pair for API access. If you try to connect to open several connections to the streaming API using the same key/secret pair it shouldn't be possible according to the Alpaca documentation. If it's possible during a market close time - it looks like a server-side bug for me and I suggest you report it on the Alpaca forum or Slack.

**Comment by ooples** [comment]
Yeah I only found about this bug because I have 2 paper accounts and I was
surprised when I accidentally used the same api info for both and didn't'
get any errors. You aren't able to send this issue up the food chain so to
speak?

**Comment by OlegRa** [comment]
@ooples I've sent this information to Alpaca guys but right now most of them are busy with new Data API v2 and Fractional support. I close this issue because it's not possible to do anything with it on the client-side. Except for the reconnection loop reported in separate issue #297.
