### ISSUE TITLE
Unhandled Exception: System.Threading.SynchronizationLockException

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#309]
I apologize for the lack of a full stacktrace but I got this exception when running the latest code and it caused my program to crash. I have a screenshot but I wasn't able to get everything copied and pasted before I accidentally hit the close button and I wasn't able to reproduce this error.

I have an image of the exception below:
[https://prnt.sc/10ujs6u](url)

**Comment by ooples** [comment]
Just want to update you to let you know that my program crashed again today but this time I didn't get a notice that it crashed. I'm assuming it is the same exception and I will give you more info as soon as I get it

**Comment by OlegRa** [comment]
@ooples Please, try the 5.0.2-alpha2 version of both packages.

**Comment by ooples** [comment]
This issue is fixed in the latest version
