### ISSUE TITLE
TimeInForce missing IOC and FOK options

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/alpaca-trade-api-csharp#31]
According to the documentation our TimeInForce options are day, gtc, opg, ioc, and fok.

https://docs.alpaca.markets/broker-functions/orders/#time-in-force

However, the SDK only offers Dat, Gtc, and Opg.

Running Alpaca.Markets 2.0.0-beta

**Comment by OlegRa** [comment]
Fix available in both [2.0.0](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v2.0.0) and [1.2.3](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v1.2.3) releases.
