### ISSUE TITLE
Review Alpaca API documentation

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#311]
Sometimes Alpaca extends API (input parameters and output data) and these changes not applied to SDK. The goal is to check all input/output data going through SDK and make it compatible with the current state of Alpaca documentation.

Found issues:

- [x] The `JsonAccount.WithdrawableCash` property points to the unexisting JSON property. This property should just return the value of the `JsonAccont.TradableCash` property.
- [x] The `JsonOrder.OrderType` property uses the deprecated `order_type` JSON property - use `type` property instead.
- [x] The `IOrder` interface (and `JsonOrder` class) miss a bunch of the new properties: `replaced_at`, `replaced_by`, `replaces`, and `order_class`.
- [x] Remove `IAlpacaStreamingClient.OnAccountUpdate` event and all related interfaces/classes from SDK (don't forget about 4.0 and 4.1 - mark all these classes/interfaces/properties with the `Obsolete` attribute).
- [x] Remove `IPosition.AccountId` property because server never send this in JSON.
- [x] Add conditions (as a list of strings) into the last/historical trades/quotes in Alpaca Data API v2 REST and streaming.
- [x] Remove `TimeFrame.Hour` and `BarTimeFrame.Second` enum members (and mark them with the `Obsolete` attribute in 4.x releases)

**Comment by ww2406** [comment]
Hey @OlegRa, I might be able to assist with this somewhat—any suggestions for the best way to approach this?

**Comment by OlegRa** [comment]
@ww2406 Thank you for your helpful proposal. The general idea is to read the whole [Alpaca API v2 documentatio](https://alpaca.markets/docs/api-documentation/api-v2/)n and compare each request/response with the related SDK interfaces/classes. There are two possible outputs:

1. Minimal: you will compare Alpaca documentation with [SDK online documentation](https://olegra.github.io/Alpaca.Markets/api/index.html) and list all found discrepancies in the issue description for future fixing by me.
2. Optimal: you will compare Alpaca documentation with SDK codebase directly with the same output. The difference is that in this case, you can also check JSON properties names mapping and do more checks.
3. Maximal: you will make all required changes in your fork and send me a PR for review. But in any case, it would be better if you'll list all found discrepancies in this issue.

**Comment by OlegRa** [comment]
@ww2406 I will keep it open for a while so you'll be able to check Alpaca API documentation against the latest codebase one more time. If you will find any discrepancies feel free to report them as comments in this issue.
