### ISSUE TITLE
Streaming API wiki code example for IAsyncEnumerable doesn't work

### ISSUE THREAD

**Issue by criterioncreative** [alpacahq/alpaca-trade-api-csharp#312]
https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Alpaca-Streaming-API

The issue is this line, where I get an error that the SubscribeTrade method does not exist:

`await using var subscription = client.SubscribeTrade(Symbol);`

I've tried installing the latest stable version and the latest preview versions of the Alpaca.Markets.Extensions NuGet package, but none of them work.

**Comment by OlegRa** [comment]
@criterioncreative All code examples that use this extension package assume that you've added the next line into your C# file `using` section:

```cs
using Alpaca.Markets.Extensions;
```

Please, update your code and close this issue if the compiler error is disappeared. I've already updated the related Wiki pages with this information for prevent future misunderstandings.

**Comment by criterioncreative** [comment]
That was an oversight on my part - thank you, this resolves my issue.
