### ISSUE TITLE
Help with Pagination Support

### ISSUE THREAD

**Issue by kwcoffee1** [alpacahq/alpaca-trade-api-csharp#313]
Hi,

I tried to implement your pagination snippet code and I get a compiler error.

```cs
static public async Task<List<SimpleBarTick>> SetHourlyHistoricalData(GroupEntity group, DateTime end)
{
    //var Adjusted = group.stock.Alias.Split(' ')[3] == " Adj";
    var list = new List<SimpleBarTick>();
    string symbol = group.Symbol;

    if (group.Symbol.StartsWith("#"))
    {
        symbol = Regex.Match(group.Symbol, @"#(.+)\d{2}|$").Groups[1].Value;
    }

    var from = end.Subtract(TimeSpan.FromDays(90));

    var cancellationTokenSource = new CancellationTokenSource();
    cancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(200));

    await foreach (var bar in group.alpacaDataClient.GetHistoricalBarsAsAsyncEnumerable(
            new HistoricalBarsRequest(symbol, from, end, BarTimeFrame.Hour))
        .GetAsyncEnumerator(cancellationTokenSource.Token))
    {
        var dt = DateTimeHelper.UTCToESTZone((DateTime)bar.TimeUtc);
        var tick = new SimpleBarTick()
        {
            Close = bar.Close,
            High = bar.High,
            Low = bar.Low,
            Open = bar.Open,
            TimeStamp = dt,
            Volume = bar.Volume
        };

        list.Add(tick);
    }

    return list;
}
```
I get the following error message on the await line statement: Error CS8411 Asynchronous foreach statement cannot operate on variables of type 'IAsyncEnumerator<IAgg>' because 'IAsyncEnumerator<IAgg>' does not contain a suitable public instance or extension definition for 'GetAsyncEnumerator'

How do I implement an instance of object: GetAsyncEnumerator ?

Sorry, I also try your code:

```cs
static public async Task<List<SimpleBarTick>> SetHourlyHistoricalData(GroupEntity group, DateTime end)
{
    //var Adjusted = group.stock.Alias.Split(' ')[3] == " Adj";
    var list = new List<SimpleBarTick>();
    string symbol = group.Symbol;

    if (group.Symbol.StartsWith("#"))
    {
        symbol = Regex.Match(group.Symbol, @"#(.+)\d{2}|$").Groups[1].Value;
    }

    var from = end.Subtract(TimeSpan.FromDays(90));

    var cancellationTokenSource = new CancellationTokenSource();
    cancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(200));

    await foreach (var bar in group.alpacaDataClient.GetHistoricalBarsAsAsyncEnumerable(
            new HistoricalBarsRequest(symbol, from, end, BarTimeFrame.Hour))
        .WithCancellation(cancellationTokenSource.Token))
    {
        var dt = DateTimeHelper.UTCToESTZone((DateTime)bar.TimeUtc);
        var tick = new SimpleBarTick()
        {
            Close = bar.Close,
            High = bar.High,
            Low = bar.Low,
            Open = bar.Open,
            TimeStamp = dt,
            Volume = bar.Volume
        };

        list.Add(tick);
    }

    Task<IPage<IAgg>> ListHistoricalBarsAsync(

    return list;
}
```

I get the following error message on the await line statement: Error CS8412 Asynchronous foreach requires that the return type 'ConfiguredCancelableAsyncEnumerable<IAgg>.Enumerator' of 'ConfiguredCancelableAsyncEnumerable<IAgg>.GetAsyncEnumerator()' must have a suitable public 'MoveNextAsync' method and public 'Current' property

thanks in advance

PS: I notice I do not get the compiler error if I  use a "var variable" in place of the "await foreach".

**Comment by OlegRa** [comment]
@kwcoffee1 Your first code snippet is incorrect - if you call 'GetAsyncEnumerator' method you have to use it manually in the `while` loop not in the `foreach` loop.

Your second code snippet should work fine and it's very strange for me why your compiler produced such an error. Unfortunately, I'm unable to reproduce this compiler error on my side using the latest Extensions package using the latest .NET 5.0 SDK and VS 2019 on Windows.

But maybe the problem is in my latest refactoring applied for these extension methods - older SDK versions can treat overloads with cancellation token incorrectly). As a temporary solution, I recommend you to pass the cancellation token as the second argument into the `GetHistoricalBarsAsAsyncEnumerable` method instead of `WithCancellation` extension method usage. So your code should look like this:

```cs
await foreach (var bar in group.alpacaDataClient.GetHistoricalBarsAsAsyncEnumerable(
        new HistoricalBarsRequest(symbol, from, end, BarTimeFrame.Hour), cancellationTokenSource.Token))
```

I will revert all my last refactoring changes soon but if you will inform me which version of the Alpaca SDK/Extensions package do you use it would be very helpful.

**Comment by kwcoffee1** [comment]
Per your request:  I'm using WPF .NET SDK 4.8 with C# 9.0.

I also observe and reported: using "HistoricalBarsRequest" with  BarTimeFrame.Minute and BarTimeFrame.Day timeframe works great but fail to work with BarTimeFrame.Hour.

Thank you for your quick response.

**Comment by kwcoffee1** [comment]
I resolved the issue when updating Microsoft.Bcl.AsyncInterfaces to version 5.0.

Thanks,

King
