### ISSUE TITLE
Reconnect / Retry socket connection 

### ISSUE THREAD

**Issue by bizjaya** [alpacahq/alpaca-trade-api-csharp#317]
Hi, this is my code for receiving trade updates, Should I have a retry mechanism on the StartStream() method
i.e. using try catch block to check if it was diconnected or timed out to reconnect ?

I guess I see SocketClosed and SocketOpened Action/Events but I'm not sure how to implement it, any advice would be greatly appreciated.

`public class ApcStreamSvc : IApcStreamSvc
    {

        private static IDbContextFactory<DbCtx> _factory;
        private static DbCon _dbcon;
        private static string _apikey = ConfigurationManager.AppSetting["ApcApiKey"];
        private static string _seckey = ConfigurationManager.AppSetting["ApcApiSec"];

        public IAlpacaStreamingClient streamClient;

        private static readonly IMapper _mapper = new MapperConfiguration(cfg => cfg.AddProfile(new DataProfile())).CreateMapper();

        public ApcStreamSvc(IDbContextFactory<DbCtx> factory, DbCon dbcon)
        {
           _factory = factory ?? throw new ArgumentNullException(nameof(factory));
            _dbcon = dbcon ?? throw new ArgumentNullException(nameof(dbcon));  
        }

        public void StartStream()
        {

            streamClient = Environments.Paper.GetAlpacaStreamingClient(new SecretKey(_apikey, _seckey));
            streamClient.ConnectAndAuthenticateAsync().Wait();
            streamClient.OnTradeUpdate += UpdateOrder;
        }

        private async void UpdateOrder(ITradeUpdate trade)
        {

            ApcTrade apt = _mapper.Map<ApcTrade>(trade.Order);

            apt.TradeEvent = trade.Event;

            await _dbcon.Insert<ApcTrade>(apt);

        }

 
    }`

**Comment by OlegRa** [comment]
@bizjaya I don't know your project architecture and can comment only on this code snippet and provide more information about SDK abilities for you:

1. The default implementation of the `IAlpacaStreamingClient` doesn't support automatic reconnection. It's a meaningful design choice - the SDK itself provides just a thin wrapper around the underlying API. It makes your life harder but provides more control over the process.
2. The `Alpaca.Markets.Extensions` helper package also available on the [NuGet](https://www.nuget.org/packages/Alpaca.Markets.Extensions) provides some helper wrappers for more sophisticated scenarios. For instance, it contains helper extension methods for wrapping the default implementation into the re-connectable one. You can read more about this feature on [this](../wiki/Extensions-Package#auto-reconnection-support) Wiki page.
3. You can use wrappers from this extension package or implement something similar in your own code. The real implementation is really simple and just uses the `SocketClosed` event for initiating the reconnection process. You can check this implementation [here](../blob/develop/Alpaca.Markets.Extensions/Reconnection/ClientWithReconnectBase.cs).

And one additional issue - I strongly recommend you rewrite your code in an asynchronous way if possible. It's not a good idea to call a `Wait` method on a task returned by the `ConnectAndAuthenticateAsync` method call. And of course, you can subscribe to the `TradeUpdate` event before the connection process starting.

**Comment by OlegRa** [comment]
@bizjaya I close this issue due to 2 weeks of inactivity. If you still have questions feel free to re-open this issue,
