### ISSUE TITLE
Typo in OrderStatus enum

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/alpaca-trade-api-csharp#32]
Found `Alpaca.Markets.OrderStatus.PendingMew` for PendingNew.

**Comment by OlegRa** [comment]
Fix available in both [2.0.0](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v2.0.0) and [1.2.3](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v1.2.3) releases.
