### ISSUE TITLE
It should be possible to select the streaming data API endpoint separately from trading environment

### ISSUE THREAD

**Issue by Dav-id** [alpacahq/alpaca-trade-api-csharp#340]
I've just spent some time debugging my code wondering why I am not seeing the same flow of quotes when I connect directly to the websocket vs via the client. What I realised is the the two endpoints were different (IEX vs SIP). I have a pro market data subscription which I want to use against the paper trading API. This is currently not possible (from what I can tell) without directly editing in the client. 

It would be great to separate out the data client from the trading client / or let us specify whether to use the SIP or IEX streaming data feed.

**Comment by OlegRa** [comment]
Maybe I don't understand your problem, but SDK provides 2 different `IEnvironment` implementations with different URLs for Alpaca Data Streaming API v2 endpoints;

if you want to create an instance of the `IAlpacaDataStreaming` interface connected to free tier IEX data you can use the `Environments.Paper` property. For paid SIP data stream you can use the `Environments.Live` property respectively.

If you want to use paper trading but SIP data stream just use different `IEnvironments` implementation for creating clients.

```cs
var tradingClient = Environments.Paper.GetAlpacaTradingClient(new SecretKey(PAPER_KEY_ID, PAPER_SECRET_KEY));
var streamingClient = Environments.Live.GetAlpacaDataStreamingClient(new SecretKey(DATA_KEY_ID, DATA_SECRET_KEY));
```

Or if your code works with `IEnvorinment` abstraction you can create your own implementation which combines URLs from paper trading and SIP data stream.

Moreover, you can create the `IAlpacaDataStreamingClient` implementation even without the `IEnvironment` interface usage just by providing the properly initialized `AlpacaDataStreamingClientConfiguration` object.

**Comment by Dav-id** [comment]
Thanks Oleg, I did try this and it makes sense this should be the approach. However, when I do ConnectAndAuthenticateAsync() the AuthResponse I get is Unauthorized. 

I don't have a live trading account API Key / Secret, so I am using paper credentials but with a paid pro data account.

I will explore the IEnvironment approach you suggest. 

Thanks!

**Comment by OlegRa** [comment]
I've just checked this scenario - paper key/secret and Unlimited data subscription plan. It works on my side - I use Paper for the trading and Live for stream connections respectively.

**Comment by OlegRa** [comment]
Looks like this issue has already solved so I can close it. @Dav-id Feel free to re-open it if you still have some issues/questions.
