### ISSUE TITLE
GetHistoricalBarsAsAsyncEnumerable issue

### ISSUE THREAD

**Issue by mattrobinson3** [alpacahq/alpaca-trade-api-csharp#342]
I'm trying to get some historical data and started with your wiki's sample code, but I get a compile error on these lines.

```cs
await foreach(var bar in client
    .GetHistoricalBarsAsAsyncEnumerable(
        new HistoricalBarsRequest("AAPL", DateTime.Today.AddDays(-5), DateTime.Today, BarTimeFrame.Hour))
    .WithCancellation(cancellationTokenSource.Token))
{
    Console.WriteLine($"{bar.TimeUtc}: {bar.Open}");
}
```

> foreach statement cannot operate on variables of type 'IAsyncEnumerable<IBar>' because 'IAsyncEnumerable<IBar>' does not contain a public instance definition for 'GetEnumerator'

Any ideas?  Is there something else I need to do in my project?

**Comment by OlegRa** [comment]
@mattrobinson3 At first your compiler should know how to work with the `IAsycnEnumerable<T>` interface. So your project C# language level should be 8.0 or greater. If you use .NET Core 3.0 or later (including the .NET 5) all should work fine without any additional changes. If you use .NET Framework 4.8 or .NET Core 2.x - read [this](https://btburnett.com/csharp/2019/12/01/iasyncenumerable-is-your-friend.html) article. For general information about async enumerating in .NET read [this](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8) article from MSDN.

**Comment by mattrobinson3** [comment]
Thanks, I'll be upgrading at least to 8.0
