### ISSUE TITLE
Add new features from Alpaca Data API v2

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#357]
The Python and Go SDKs already have some additional features that will be widely available for all users later. We can add support for them in a separate branch and enable them later:

- [x] #359
- [x] The trading statuses updates in the Data Streaming API connection ([Go/#134](https://github.com/alpacahq/alpaca-trade-api-go/pull/134))
- [x] The LULD values updates in the Data Streaming API connection ([Go/#136](https://github.com/alpacahq/alpaca-trade-api-go/pull/136) & [Python/#464](https://github.com/alpacahq/alpaca-trade-api-python/pull/464))
- [x] #380
- [x] Metadata endpoints - conditions and exchanges dictionaries retrieval methods

**Comment by ooples** [comment]
What exactly are these limit up limit down events and how are they supposed to work?

**Comment by OlegRa** [comment]
@ooples I don't know how you can use it in your code but the initial idea of LULD is to control price volatility. See more info [here](https://www.luldplan.com/) or in the Investopedia ([one](https://www.investopedia.com/terms/l/limitup.asp), [two](https://www.investopedia.com/terms/l/limitdown.asp)).
