### ISSUE TITLE
Add the new fields VWAP and trades number in the historical and streaming bars

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#359]
These fields are already available in REST API and It would be nice to add them for all supported SDK versions.

**Comment by jeonnagroup2** [comment]
maybe i'm missing something but VWAP and TradeCount show 0  i run SDK 5.2.4 

![image](https://user-images.githubusercontent.com/91985268/146220510-21549dad-3681-48ed-a455-d38f8a59f485.png)

**Comment by jeonnagroup2** [comment]
any idea when this going to show the data ?

**Comment by OlegRa** [comment]
@jeonnagroup2 I've opened a separate issue for this problem - #432 and I already know the root cause. I'll include a fix in the next release (ETA is Sunday).

**Comment by jeonnagroup2** [comment]
ty buddy !!  so the tradecount is for all exchanges ?

**Comment by OlegRa** [comment]
@jeonnagroup2 AFAIU trade count value calculated differently for free (IEX) and paid (SIP) subscriptions.
