### ISSUE TITLE
Bar TimeFrames

### ISSUE THREAD

**Issue by matt953** [alpacahq/alpaca-trade-api-csharp#362]
Hi,

Would it be possible to add an additional option for 5Min Bars to historical Bar requests. Currently its limited to 1Min, 1Hour and 1Day.

**Comment by OlegRa** [comment]
@matt953 Unfortunately, this option is not supported by the underlying [Alpaca Data API](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#bars) so it can be implemented only using re-sampling but it's not a goal of this low-level SDK.
