### ISSUE TITLE
Reproducing Alpaca .Net SDK Unity Integration issues: C#

### ISSUE THREAD

**Issue by waymanapps** [alpacahq/alpaca-trade-api-csharp#364]
Step 1: Access the official Alpaca SDK page to find the NuGet Package Link here:
https://alpaca.markets/docs/api-documentation/client-sdk/
#SupportImageAttached1:
 
![AlpacaHelp1](https://user-images.githubusercontent.com/16636647/130306674-525b3702-40e5-4e0d-b8cf-2de0f50d438b.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
Step 2: Download the NuGet Package version (5.0.6) from here:
https://www.nuget.org/packages/Alpaca.Markets/
#SupportImageAttached2:
 
![AlpacaHelp2](https://user-images.githubusercontent.com/16636647/130306579-33b7d0c2-1455-48ff-9526-c5aaa1a631b3.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
This next step assumes you a basic knowledge of installing and using the Unity Engine environment.
I’m using Unity version 2020.3.15f2 in this example, but any version 2019 or higher should work.
Step 3: Copy the downloaded Package and paste it into a new Unity project’s “Asset’s folder” directory.
#SupportImageAttached3:
 
![AlpacaHelp3](https://user-images.githubusercontent.com/16636647/130306589-3404f734-39ad-442c-b591-55f356b4e3d1.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
Step 4: Notice the NuGet package name at this step: (alpaca.markets.5.0.6.nupkg) I’ll change this name in the following step in order to access the package content.
#SupportImageAttached4:
 
![AlpacaHelp4](https://user-images.githubusercontent.com/16636647/130306600-12784767-e526-4a36-a1f7-dcae4d6692ec.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
Step 5: In this step, I changed the downloaded package name by only removing the appended string (.nupkg) replacing it with (.zip ). The package file can now be unzipped, and we can now access the Highlighted content inside:
#SupportImageAttached5:
 
![AlpacaHelp5](https://user-images.githubusercontent.com/16636647/130306606-d2da72d4-f8b5-44e8-8fe0-f5a9c195d1ef.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
Step 6: Now inside the Unity Engines inspector, we immediately have the following errors:

```
Multiple precompiled assemblies with the same name Alpaca.Markets.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/lib/net5.0/Alpaca.Markets.dll)
```

In the following step, I attempt to identify the duplicate Alpaca.Markets.dll’s :
#SupportImageAttached6:
 
![AlpacaHelp6](https://user-images.githubusercontent.com/16636647/130306621-02e381c2-ce41-437b-a7d9-9326aa2826c3.jpg)

Step 7: Now after entering the unzipped content folder named “Lib” I noticed (4) additional folders named: {net5.0, net461, netstandard2.0, netstandard2.1}. Each folder containing its own Alpaca.Markets.dll and XML file.
In the following step, I attempt to randomly remove (3) of the folders containing what appear to be duplicate Alpaca.Markets.dll and XML files:
#SupportImageAttached7:
 
![AlpacaHelp7](https://user-images.githubusercontent.com/16636647/130306629-68e6e949-7652-4480-a490-f78fa7eddd96.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
The (3) content folders I randomly selected for deletion are: {net5.0, net461, and netstandard2.1}
Step 8: Now that I’ve successfully delete (3) of the folders containing the duplicate Alpaca.Markets.dll and XML files, The Unity console presented me with the following new error:

```
Assembly 'Assets/lib/netstandard2.0/Alpaca.Markets.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Threading.Tasks.Extensions'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Alpaca.Markets references strong named Newtonsoft.Json Assembly references: 13.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
Unable to resolve reference 'Polly'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'WebSocket4Net'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'SuperSocket.ClientEngine'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

#SupportImageAttached8:
 
![AlpacaHelp8](https://user-images.githubusercontent.com/16636647/130306649-6e010f52-e57c-443b-a77e-fc4c4447e767.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
Step 9: At this stage, if I attempt to create a new C# script in Unity called “AlpacaExample.cs”, as you can see in the attached image, I’m able to access the Alpaca namespaces without script compile errors being thrown.
However… in the following step…
#SupportImageAttached9:
 ![AlpacaHelp9](https://user-images.githubusercontent.com/16636647/130306654-0c87532f-adc3-4a40-8dfc-241617508657.jpg)

------------------------------------------------------------------------------------------------------------------------------------------
Step 10 FinalStep: Back in the Unity inspector, however; I’m provided the following build error:
Assembly 'Assets/lib/netstandard2.0/Alpaca.Markets.dll' will not be loaded due to errors:

```
Unable to resolve reference 'System.Threading.Tasks.Extensions'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Alpaca.Markets references strong named Newtonsoft.Json Assembly references: 13.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
Unable to resolve reference 'Polly'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'WebSocket4Net'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'SuperSocket.ClientEngine'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

And this is where I’m stuck. Thanks for any help one can provide.
#SupportImageAttached10:
 
![AlpacaHelp10](https://user-images.githubusercontent.com/16636647/130306659-a276231b-6483-4934-ab7f-2096adf94915.jpg)

-END  (Sorry for any typos found…)
------------------------------------------------------

[Alpaca SDK Unity Integration issues.pdf](https://github.com/alpacahq/alpaca-trade-api-csharp/files/7024663/Alpaca.SDK.Unity.Integration.issues.pdf)

**Comment by OlegRa** [comment]
OK. I see 2 main problems in the errors list:

- The `Newtonsoft.Json` assembly version (13.0) used by the Alpaca SDK is greater than the version 12.0 used by your Unity project (or any other dependency in this project). It's not a good idea to downgrade the dependency version in SDK but instead, it would be better to find out the code in your Unity project that uses an old version of the `Newtonsoft.Json` and update it with the newer one.
- The `System.Threading.Tasks.Extensions`, `Polly`, `WebSocket4Net`, and `` are not part of NuGet package itself because they are parts of dependent assemblies. There are some ways for obtaining them and I'll explain the simplest one soon.

I suggest trying the [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) tool for importing the Alpaca SDK. It solves a lot of issues related to versions incompatibility and dependencies (even transitive) management. But if you prefer to do it manually use this approach for obtaining the full list of Alpaca SDK binaries with all dependencies:

1. Create the .NET library project in the VS or using the `dotnet` command that will target .NET Standard 2.0
2. Add the `Alpaca.Markets` NuGet package (and the `Alpaca.Markets.Extensions` package if needed) into this project
3. Build project and get all `.dll` files from output folder except the project name `.dll` file and place into the Unity Assets folder

I will do these steps later today and attach the results into this issue for you

**Comment by OlegRa** [comment]
Please, try to add conent of one of these files into your Assets folder:

- [Alpaca.Markets-v5.0.6.zip](https://github.com/alpacahq/alpaca-trade-api-csharp/files/7025255/Alpaca.Markets-v5.0.6.zip)
- [Alpaca.Markets-v5.1.0.zip](https://github.com/alpacahq/alpaca-trade-api-csharp/files/7025256/Alpaca.Markets-v5.1.0.zip)

I recommend you to start from 5.1.0 version - it has less 3rd party dependencies but 5.0.6 should also works fine.

Please, inform me about results. If this approach will work fine I'll add the CI/CD step for creating such .zip archive for each SDK version and publish it here attached to the GitHub release.

**Comment by waymanapps** [comment]
Thanks again @OlegRa, I'll give these methods a try and get back to you with my results. I appreciate the help!!

**Comment by waymanapps** [comment]
@OlegRa 
YES, it works!!!

We finally got it to work. I'll create Documentation to illustrate each of my steps, and post them here before the close of day Monday 08/23/21

Thank you for all your help!

PS: the Alpaca.Markets-v5.1.0 content files did the trick!

**Comment by waymanapps** [comment]
**Alpaca .Net SDK – Successful Basic Unity Integration: (unofficial)**


Step 1: Create a new Unity project using Unity Hub version 3.0.0-beta.2 
(This step SHOULD work for almost any version of Unity Hub. - Not Validated-)
#SupportImageAttached1:
 
![AlpacaWorking1](https://user-images.githubusercontent.com/16636647/130373979-7a94e5a2-b519-41db-bb76-2b260ffc82d9.jpg)


------------------------------------------------------------------------------------------------------------------------------------------
Step 2: We selected the default Unity project settings (3D Core), Unity version 2020.3.15f2.
(This step SHOULD work for any rendering pipeline. URP/HDRP. - Not Validated-)
#SupportImageAttached2:
 
![AlpacaWorking2](https://user-images.githubusercontent.com/16636647/130374002-7d004592-2814-4076-bc0d-79b8e92efa9b.jpg)


------------------------------------------------------------------------------------------------------------------------------------------
Step 3: Once the new project has Loaded/Opened, navigate to the “Package Manager” to inspect the pre-installed packages.  We’ll need to remove packages that conflict with Newtonsoft.Json v13.0
(Path: Window / Package Manager)
#SupportImageAttached3:
 
![AlpacaWorking3](https://user-images.githubusercontent.com/16636647/130374009-7b6baa64-a2b0-4ca5-bd47-9994b7f0357b.jpg)

------------------------------------------------------------------------------------------------------------------------------------------


Step 4: Outlined in red are the packages I removed to get the Alpaca SDK to work. Remove/Uninstall each of these pre-installed Packages. {JetBrainsRiderEditor, TextMeshPro, Timeline, VersionControl}.

> I understand that removing some of these packages is not ideal for most projects, but this is what worked for me. After following these steps, feel free to experiment and share your results.

#SupportImageAttached4:
 
![AlpacaWorking4](https://user-images.githubusercontent.com/16636647/130374036-240205ad-f082-4e2f-b301-72ce01b10250.jpg)

------------------------------------------------------------------------------------------------------------------------------------------


Step 5: After uninstalling the packages, navigate outside of Unity to the location of your Alpaca.Markets-v5.1.0 zip file.  Extract the file to expose the Dynamic-link libraries inside. 
#SupportImageAttached 5.1 & 5.2:
 
![AlpacaWorking5](https://user-images.githubusercontent.com/16636647/130374050-f388cf17-03af-4c01-af70-4091617f0008.jpg)

![AlpacaWorking5_2](https://user-images.githubusercontent.com/16636647/130374051-cc69f06d-2405-458b-86eb-96883e985d34.jpg)
 
(We’ll have to copy and paste this content in the following step…)

------------------------------------------------------------------------------------------------------------------------------------------



Step 6: Now back in the Unity engine, under the Asset folder directory, we’ll need to create a folder named “Plugins” (Case-Sensitive). Inside this “Plugins” folder, we’ll need to paste the Dynamic-link libraries extracted in the previous step.
#SupportImageAttached6:
 
![AlpacaWorking6](https://user-images.githubusercontent.com/16636647/130374061-21e16b7e-90e5-49a3-bf2f-d95bb7155f4d.jpg)

------------------------------------------------------------------------------------------------------------------------------------------



Step 7: After removing the conflicting packages, and pasting the Dynamic-link libraries into the Plugins folder, all that is left to do is attempt a call to the Alpaca servers. To simplify this step, I’ve edited a script from the official Alpaca examples page, here:
https://alpaca.markets/docs/api-documentation/how-to/account/
My edit allows the native C# code to play nicely with Unity’s MonoBehaviour.  

provided C# file 
([AlpacaManager.zip](https://github.com/alpacahq/alpaca-trade-api-csharp/files/7028361/AlpacaManager.zip))

Users should add this script to his or her project, and attach it to any gameObject in the Scene. 
This script will print a log on Start, containing the user's account balance etc.
Please be sure to add your keys!!!
API_KEY = “Your Paper ID or Client ID”
And
API_SECRET = “Your Paper Secret of Client Secret”

PS: I have not thoroughly stress-tested this Unity Integration, but the script call to Alpaca was a success. I’ll keep updating issues as needed.

Thanks again @OlegRa for all the help!!!

Let me know if you have any questions.

-END  (Sorry for any typos found…)
------------------------------------------------------------------------------------------------------------------------------------------

**Comment by OlegRa** [comment]
@waymanapps Possible [solution](https://forum.unity.com/threads/dependency-on-newtonsoft-json.814128/) for the JSON.NET compatibility that will allow you to keep all pre-installed packages (step 4). I'm unable to test it right now but AFAIU it should work if you will specify version 13.0 in the `app.config` file. Just don't forget to do it twice!

**Comment by waymanapps** [comment]
Awesome, I'll give this a try and get back to you with my results. @OlegRa

**Comment by Nishat11** [comment]
@waymanapps  yes I worked on similar issues.

**Comment by waymanapps** [comment]
> @waymanapps yes I worked on similar issues.

Stop it @Nishat11

We were working on this project together! LMAO

**Comment by Atr-Matthew** [comment]
Found a neat way to get rid of the async method all together to make retrieving multiple values super easy.
The simple snippet below should set any unity UI text to the account equity, but you could pull anything pretty easily like this : )

`
using UnityEngine;
using System;
using Alpaca.Markets;
using TMPro;

public class AlpacaManager : MonoBehaviour
{
    private static string API_KEY = "basic_key_here";
    private static string API_SECRET = "secret_key_here";

    public TMP_Text capital_lbl;

    private IAlpacaTradingClient _client;

    private float acc_capital;

    public void Start ()
    {
        _client = Environments.Live.GetAlpacaTradingClient(new SecretKey(API_KEY, API_SECRET));

        var _account = _client.GetAccountAsync().GetAwaiter().GetResult();
        
        acc_capital = (float)Math.Round(_account.Equity, 2);

        capital_lbl.text = "Capital: " + acc_capital.ToString();
    }
}
`
