### ISSUE TITLE
Add CI/CD step for Unity package preparation

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#366]
It's possible to use SDK binaries in Unity (see #364 discussion) but this process is not straightforward. We can add the automatic Unity package preparation build step into our CI/CD pipeline. The tarball package format can be easily produced from the project output. More details about the internal package layout can be found in the [Unity documentaion](https://docs.unity3d.com/Manual/CustomPackages.html).

**Comment by OlegRa** [comment]
@waymanapps Do you still need this special archive with dependencies or you are able to use the SDK NuGet package directly from Unity?

**Comment by waymanapps** [comment]
Hi @OlegRa 

It's pretty helpful for the Pre-release sdk-6.0.1 versions. Not mandatory though. No need to keep producing them if it adds additional work to your process.  Seems there are no alpha NuGet versions available via the Unity NuGet Package manager.

That said, I can access the stable versions of the Alpaca SDK via Unity NuGet package manager. It seems the versions available via the NuGet Unity plugin are a little delayed sometimes. Can you make the Alpha releases available via NuGet? They currently are not visible via the manager when I search. So I’ve relied on the dependencies archive for alpaha releases.

I’ve been off the platform detoured for a few weeks while I close out a large work related project, but I’ll benefit from the archive again soon.

Here is what I currently see in the plugin via Unity when searching: “Alpaca.Markets”
I see version 5.2.2 and version 5.2.1. Are these the latest two stable builds of the Alpaca SDK ?
Image:
![Screenshot 2021-11-08 000443](https://user-images.githubusercontent.com/16636647/140707247-8ef4b7b9-fe87-4571-b365-d7b700af25db.png)

**Comment by OlegRa** [comment]
@waymanapps In fact ALL versions of SDK and Extensions packages are available on NuGet. Each GitHub release contains a link for the appropriate NuGet page for direct download.
Have you ever tried to enable both the `Show All Versions` and `Show Prerelease` checkboxes and press the `Refresh` button? If this tool requests data directly from the NuGet.org site it should display you all 6.0.x versions too.

**Comment by waymanapps** [comment]
@OlegRa 
I could have sworn activating the “Prerelease bool didn’t work in the past; however, I stand corrected. That was the correct/simple solution.
I guess the appropriate answer to your question is no, the dependencies archive is no longer needed.
Thank you for all your help. I’ll be sure to open a ticket if I have issues in the future.
PS: I’ll also visit the link to the Unity Documentation you've shared.
FYI: Here’s what appears in the search window with “Prerelease” selected.
![Screenshot 2021-11-08 165305](https://user-images.githubusercontent.com/16636647/140841719-23291076-73ca-4821-ae03-5f4edfc30fc3.png)
