### ISSUE TITLE
Apply API breaking changes

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#370]
Alpaca introduced the [API breaking changes](https://alpaca.markets/blog/api-breaking-change-notification-for-unpriceable-assets/?utm_source=slack-community&utm_medium=organic-social&utm_campaign=slack-community-api-breaking-change-notification-for-unpriceable-assets-blog-2021) that will affect some SDK clients. We should mark the related properties with correct JSON deserialization attributes and update the nullability of these properties as needed.

**Comment by OlegRa** [comment]
@waymanapps You can get all `.dll` files required for the Unity packed into a single `.zip` archive from the [GitHub release](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/sdk-5.1.0-rc2) page now.

**Comment by waymanapps** [comment]
Awesome!

Thank you! @Oleg
