### ISSUE TITLE
Change "d" reference to "t" for minute agg

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/alpaca-trade-api-csharp#38]
Please refer to https://github.com/alpacahq/alpaca-trade-api-python/pull/49

**Comment by umitanuki** [comment]
https://github.com/alpacahq/alpaca-trade-api-csharp/blob/master/Alpaca.Markets/Messages/JsonMinuteAgg.cs#L24

**Comment by OlegRa** [comment]
@umitanuki I have some questions:

 1. Do you want to support both fields for now and use 'd' only if 't' is not available or just switch to 't' completely?
 2. Do you need 1.2.4 release with this fix or it's enough to apply proposed changes only in 2.1.0?
