### ISSUE TITLE
Great strategy! I love it! There few issues I noticed.

### ISSUE THREAD

**Issue by zhorakiev** [alpacahq/alpaca-trade-api-csharp#391]
What's up my brother! I use your program on huge accounts and it is giving me great returns. Few things I would recommend addressing or maybe I am not understanding it correctly. 

Can you please explain the significance of Scale - why it's defaulted to 200? What is your opinion are acceptable numbers and what kind of impact these numbers can make?

Noticed is when stock is blocked from shorting, the program is trying to take short positions anyway. 

Another problem, when it's taking positions, it uses all your available buying power in the first order. For example, when taking long positions, but the price is going down, the program tries to take additional positions, but the available buying power is zero. Is there a way to say, take 20% on the first order and add 20% each time?

See screenshot - https://prnt.sc/1w4k8cq - buying power is zero and bot is trying to add more money...

This is the example of trying to sell when shorting is not allowed - https://prnt.sc/1w4m321

I understand that this is not applied to all stocks. Maybe you have best practices strategy with it, what kind of symbol will work with it. I also noticed you hardcoded SPY and 200 for the scale in the code. Can you please give more details on this part.

**Comment by OlegRa** [comment]
@zhorakiev I'm glad that the `UsageExample` code still works even after years of not touching. In fact, this code is just an example of how to use .NET SDK in real code. Moreover, this code was written by another developer and I don't have deep understandings of the internals of this code. But I'll try to answer your questions:

1. Yes, it's possible to check if the asset is shortable or not before opening the short position. I'll add this check later.
2. Yes, it's possible to use not full buying power. I will check how to do it in the simplest way and if it will not make code more 'cryptic' I'll add this feature into the example.
3. I'm not sure about the scale and its meaning in the algorithm. I'll check it and provide you with more information later.
