### ISSUE TITLE
Subscription issue

### ISSUE THREAD

**Issue by zhorakiev** [alpacahq/alpaca-trade-api-csharp#398]
Downloaded new version and started getting subscription issue. 

After  await alpacaDataStreamingClient.SubscribeAsync(subscription); - executing fine without errors, no 1 minute bar events comming in. 

I tried previous version and event is working.

Here is the video http://youtu.be/GbaGaJo2a5c?hd=1

**Comment by OlegRa** [comment]
Looks like the #385 issue fix did not resolve the problem completely and even add the new issues. I have some ideas on how to fix this problem but am unable to test them right now. I'll release the updated version of the package as soon as I'll have stable test results.

**Comment by Tifoid** [comment]
I'll add my experience notes to this bug as I think my issue is related to @zhorakiev 

Using v1.5.2 nuget package I am able to properly subscribe to minute data.  Additionally I do get minute data, but after approximately 2 hours of getting periodic minute data (for about 50 tickers) the minute data just stops. No errors are reported. The rest of my application continues to run without issue I just no longer receive callbacks to my minute processing logic.
