### ISSUE TITLE
[BUG]: invalid syntact of GetTradeSubscription

### ISSUE THREAD

**Issue by koolinoor** [alpacahq/alpaca-trade-api-csharp#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```cs
var _client = Environments.Live.GetAlpacaDataStreamingClient(key);
await _client.ConnectAndAuthenticateAsync();
var sub = _client.GetTradeSubscription(can.Key);
sub.Received += TradeReceived;
```                

Does not work. All I get is a bunch of errors without descriptions. no trade info 

### Expected Behavior

The `TradeReceived(ITrade obj)` event obviously.

### Steps To Reproduce

install nuget, try out the included example

**Comment by OlegRa** [comment]
@koolinoor I'll check how well trade subscription logic works in the latest stable SDK but AFAIR I've tested it last week.

1. It's not clear from your description if it's a syntax error generated by the C# compiler or it's some run-time errors. In both cases, it's better to provide more specific details not just generic info.
2. It's almost impossible to investigate without information about your environment: which version of SDK do you use, what is your OS version/bitness, which .NET SDK do you use, and what is your target .NET version/bitness?
3. It's not clear where you get 'included example' - the NuGet package itself doesn't contain any samples. In your code snippet, I don't see one important step - you should call the `SubscribeAsync` method and pass the `sub` object into it for sending the real subscription request to the server.

**Comment by OlegRa** [comment]
@koolinoor You can use code from this [Wiki page](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Alpaca-Streaming-API#subscribing-realtime-data) as a starting point. I've just checked it and all works as expected on my side.

**Comment by koolinoor** [comment]
<package id="Alpaca.Markets" version="5.2.3" targetFramework="net48" />

**Comment by OlegRa** [comment]
It would be nice if you'll provide answers to all questions not for a single one.

**Comment by OlegRa** [comment]
Closed now due to inactivity. Feel free to re-open it (and provide more info) if problem still exists.
