### ISSUE TITLE
Make changes in the streaming clients

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#420]
Recent changes in the Alpaca streaming specification requires some changes in the existing clients:

- [x] Report new message types received from the stream not as errors but as warnings (introduce the new `OnWarning` event for it).
- [x] Add support for implicit subscriptions - for example, the trades' subscription initialization implicitly subscribes you for corrections/cancels.
- [x] Add an additional event for `Subscribed` state change (named like `OnSubscribedChanged` or so) - looks like it can be useful in some scenarios.

**Comment by ooples** [comment]
@OlegRa  When are you going to release these new changes for the prerelease versions?

**Comment by OlegRa** [comment]
@ooples Is it critical for you? I just want to implement full support for 2 new objects in streaming - corrections & errors and make the 6.0.x version with all changes. But if you really need intermediate release just with suppressed errors I can do it today.

**Comment by ooples** [comment]
No it isn't critical. I was just noticing that you published it for the
other versions and I was just curious
