### ISSUE TITLE
[BUG]: Solution does not complie and not working

### ISSUE THREAD

**Issue by zhorakiev** [alpacahq/alpaca-trade-api-csharp#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am trying to download and start the solution in Visual Studio 2019, it is not compiling and not able to debug anything. It does not work. Why uncompiled solution is checked?

### Expected Behavior

User should download and debug without any issues

### Steps To Reproduce

```markdown
Just download latest version
```

### Environment

```markdown
.Net studio 2019
```

### Anything else?

No

**Comment by OlegRa** [comment]
The `develop` branch now uses .NET SDK 6.0 and C# 10 language features. If you want to use/compile it as code you have to install the latest Visual Studio 2022 - it supports .NET 6.0 and provides a better user experience (now it is 64-bit finally).
Of course, you can still use SDK as a NuGet package from any other IDE and from other .NET SDKs including .NET Framework and Unity for example.
