### ISSUE TITLE
[BUG]: Receiving multiple "minute bar" updates for the same minute

### ISSUE THREAD

**Issue by polymorphicshade** [alpacahq/alpaca-trade-api-csharp#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not 100% sure if this is a bug or not, but when subscribing to "BTCUSD" with the `CryptoStreamingClient.SubscribeMinuteBarAsync(...)` method, I'm getting minute bar updates just fine, but periodically I get multiple updates for the same minute in very quick succession (see screenshot below).

![image](https://user-images.githubusercontent.com/32504507/145156974-77e6f917-1fd0-4e28-bda2-0cbeb1eeab2d.png)
(left timestamp is the bar timestamp, and the right timestamp is `DateTime.UtcNow`)

I do get different data per event trigger (the latest bar information). Is this expected behavior? This is effecting my calculations and how my code reacts to price changes. Maybe I need to be able to handle this kind of behavior?

### Expected Behavior

I would expect the minute bar subscription to only trigger 1 event every minute.

### Steps To Reproduce

```markdown
var dataSubscription = await CryptoStreamingClient.SubscribeMinuteBarAsync("BTCUSD");
dataSubscription.Received += bar => { /* ... */ };
```

### Environment

```markdown
- SDK Version: 6.0.2-alpha2
- OS (version, bitness): Windows 10 x64
- .NET SDK (version): 6.0
```

**Comment by OlegRa** [comment]
I've checked the SDK sources several times and was unable to find any places for such behavior. I'm not sure about the crypto, but AFAIR in case of any corrections/cancells in the stocks stream Alpaca re-send the related minutes' bar with updated values. Maybe they made the same thing for the crypto too. I think it's better to escalate this question to the Alpaca support.

**Comment by polymorphicshade** [comment]
Thanks for the response! Yeah I figured it boiled down to something like that. All this would mean is I need to buffer these updates within 1-min bar intervals, rather than treating each event subscription as an additional bar.

I'll close this since this seems like I'm using the API incorrectly.

**Comment by polymorphicshade** [comment]
> I'm also having this problem. Did anyone find out why it behaves like this and why the two updates don't have the same value for the same timestamp?

I totally forgot about this, but I believe this isn't an issue if you specify a crypto exchange in your query.

**Comment by polymorphicshade** [comment]
> 
Use the WithExchanges() extension method: `new HistoricalCryptoBarsRequest(...).WithExchanges(...);`

**Comment by OlegRa** [comment]
@polymorphicshade Thanks for the prompt answer. I'll just add a small correction: if @PlayCreatively want's to specify an exchange(s) for the streaming crypto data the `WithExchanges` method should be called for the `AlpacaCryptoStreamingClientConfiguration` class instance.

BTW, the underlying REST API for historical crypto data doesn't support per-exchange bars/trades/quotes anymore so `WithExchanges` methods for historical data requests will not have any effect in SDK version 6.1.0 and above.
