### ISSUE TITLE
[QUESTION]: Unexpected message type 'x' received

### ISSUE THREAD

**Issue by YongliangLi** [alpacahq/alpaca-trade-api-csharp#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Hi,

I keep getting the following message in the Alpaca Data Stream client, and the trade/quotes are stopped flowing in after it.
I've talked this to Alpaca support for more than 2 weeks already, but no definitive answers, the support is trying to get a response from engineers.
Does anyone else see this problem? how do you get this resolved? Thank you in advance.

`2021-12-10T09:48:12.8387405-05:00 ERROR:: Unexpected message type 'x' received.`

**Comment by OlegRa** [comment]
@YongliangLi Just use the latest version of SDK from your stream (5.2.4 in the case of mainline) - all such issues are now reported via the `OnWarning` event and you can just log it without any additional action.

**Comment by YongliangLi** [comment]
Thanks for the reply @OlegRa. 
Do you have any idea why the data stream stopped after receiving this message? The algorithm is still running after printing out this ERROR log, but the quote/trade is not updated unless restarting the algorithm.  I feel the server-side stopped sending data, will changing the log level to warning make any difference?

**Comment by YongliangLi** [comment]
Quick update, after consuming version 5.2.4, the issue didn't show up in recent 2 days. 
Thank you, @OlegRa! I'm going to close the ticket.
