### ISSUE TITLE
How to interpret the most recent bar date and time with GetHistoricalBarsAsync call?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

The following code (using version 5.2.4) that fetches daily bars (the execution time is around 7:50AM on Dec 16 in UTC):

```cs
var symbols = new List<string>() { "AAPL" };

var request = new HistoricalBarsRequest(symbols,
    DateTime.Parse("2020-07-01"), DateTime.Parse("2021-12-16"), BarTimeFrame.Day);
request.Adjustment = Adjustment.Nothing;

var client = CreateAlpacaDataClient(true, ACCESS_TOKEN);
IMultiPage<IBar> multiPageBar = null;
bool initialRequest = true;

Console.WriteLine($"Symbol, Time, Open, High, Low, Close, Volume");

do
{
    if (!initialRequest)
    {
        request = request.WithPageToken(multiPageBar.NextPageToken);
    }

    multiPageBar = await client.GetHistoricalBarsAsync(request);

    Console.WriteLine($"Next page token: {multiPageBar.NextPageToken}");

    foreach (var item in multiPageBar.Items)
    {
        var symbol = item.Key;
        var bars = item.Value;

        foreach (var bar in bars)
        {
            Console.WriteLine($"{bar.Symbol}, {bar.TimeUtc:f}, {bar.Open}, {bar.High}, {bar.Low}, {bar.Close}, {bar.Volume}");
        }
    }

    if (initialRequest)
    {
        initialRequest = false;
    }
}
while (multiPageBar.NextPageToken != null);
```
produces the following output (only most recent bars are shown):

```
Symbol, Time, Open, High, Low, Close, Volume
AAPL, Wednesday, December 8, 2021 5:00 AM, 172, 175.96, 170.7, 175.08, 116911182
AAPL, Thursday, December 9, 2021 5:00 AM, 174.84, 176.75, 173.92, 174.56, 108955978
AAPL, Friday, December 10, 2021 5:00 AM, 175.14, 179.63, 174.69, 179.45, 115269420
AAPL, Monday, December 13, 2021 5:00 AM, 181, 182.13, 175.53, 175.74, 152365422
AAPL, Tuesday, December 14, 2021 5:00 AM, 175.3, 177.74, 172.21, 174.33, 139551966
AAPL, Wednesday, December 15, 2021 5:00 AM, 175.16, 179.5, 172.3108, 179.3, 130902329
```

1. As you can see, the time is shown in UTC as 5:00 AM on last day December 15. Is this correct? Should this not be equivalent of market close time of 4PM (US Eastern Time) equivalent which should translate to around 8PM in UTC time on December 15?
2. How are we supposed to interpret this time component that is coming back in the above API?

### Anything else?

In addition, if I specify Dec 15, 2021 as the to date, the last bar shows up as Dec 14. The documentation says following:

```
into: Filter data equal to or before this time.
```

What am I missing?

**Comment by OlegRa** [comment]
I've checked the raw JSON response from the Alpaca Data API REST endpoint and can confirm - in the case of daily bars they return this timestamp (5:00 AM in UTC). Most probably the root cause is that this timestamp is midnight (12:00 AM) in the EST timezone. In any case - SDK returns the properly deserialized value so I suggest closing this issue.

And about the `into` parameter - if you use the `DateTime` constructor that takes an only year, month, and date (or parse this object from a string that contains only these parts) it will assume that all time's parts are zero. So if you need a day bar for this day too you should specify the next day or the last minute of the target day.

**Comment by rudeGit** [comment]
Thanks for the explanation.
