### ISSUE TITLE
Add method for requesting snapshot for the crypto

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#433]
The Alpaca Data API v2 for the crypto contains the new (currently undocumented) REST endpoint. The reference implementation in [Python](https://github.com/alpacahq/alpaca-trade-api-python/pull/539#event-5741886703), [Go](https://github.com/alpacahq/alpaca-trade-api-go/pull/179#event-5748380921), and [JS](https://github.com/alpacahq/alpaca-trade-api-js/pull/176#event-5748284152) can be used as starting point as usual.

**Comment by matsydoodles** [comment]
Ha, just went looking for this 🤦‍♂️
