### ISSUE TITLE
[QUESTION]: Subscribe to bars with wildcard

### ISSUE THREAD

**Issue by IsaackRasmussen** [alpacahq/alpaca-trade-api-csharp#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Is subscribing to bars with wildcards supported? I get an error when subscribing to "*" and I can't find any mention of this in the issues or Wiki pages.

**Comment by OlegRa** [comment]
@IsaackRasmussen I've checked the `GetMinuteBarSubscription()` method and it works as expected. See the next code snippet:

```cs
var key = new SecretKey("...", "...");
using var client = Environments.Paper.GetAlpacaDataStreamingClient(key);
client.OnError += exception => Console.Error.WriteLine(exception);

var status = await client.ConnectAndAuthenticateAsync();
Console.WriteLine(status);

var bars = client.GetMinuteBarSubscription();
bars.Received += bar => Console.WriteLine($"B: {bar.Symbol} @ {bar.TimeUtc}");
await client.SubscribeAsync(bars);

Console.Read();

await client.DisconnectAsync();
```

**Comment by IsaackRasmussen** [comment]
Yes this works and the Intellisense also says its for listening to all. I somehow missed that.

Thanks for pointing it out!

You added it as a v6.0 milestone but I guess, that's no longer needed?
