### ISSUE TITLE
Consistent response structure for IAlpacaTradingClient.ListCalendarAsync

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When I invoke the IAlpacaTradingClient.ListCalendarAsync method:

```cs
var list = await this.alpacaTradingClient.ListCalendarAsync(calendarRequest);
```

with a request that requires multiple calendar dates, I get a list of date times. 

I inspect list's first item's values as shown below:

The following looks good as there are 5 hours of difference between EST and UTC:

```cs
list.First().TradingOpenTimeEst.ToString("G")
"12/30/2021 9:30:00 AM"
list.First().TradingOpenTimeUtc.ToString("G")
"12/30/2021 2:30:00 PM"
```

The following looks good as there are 5 hours of difference between EST and UTC:

```cs
list.First().TradingCloseTimeEst.ToString("G")
"12/30/2021 4:00:00 PM"
list.First().TradingCloseTimeUtc.ToString("G")
"12/30/2021 9:00:00 PM"
```

However the following shows inconsistent time values:

```cs
list.First().TradingDateEst.ToString("G")
"12/30/2021 12:00:00 AM"
list.First().TradingDateUtc.ToString("G")
"12/30/2021 12:00:00 AM"
```

The above is confusing. If you want to show only one date with 12 AM as the time, then you might want to have a single property, say TradingDate whose value can be:

`"12/30/2021 12:00:00 AM"`

Having TradingDateEst and TradingDateUtc properties with the same exact info is confusing.

The API response (from https://alpaca.markets/docs/api-documentation/api-v2/calendar/) is much cleaner as it simply shows EST info only.

```json
{
  "date": "2021-12-30",
  "open": "09:30",
  "close": "16:00"
}
```

### Describe the solution you'd like

Remove properties: TradingDateEst and TradingDateUtc 

Add property: TradingDate

**Comment by OlegRa** [comment]
@rudeGit I'll try to explain my vision and the reason why I don't want to make the proposed simple solution:

- I agree that the current version of the `ICalendar` interface is too complex and confusing but it's a result of the long evolution of this interface - some users want EST data, some need UTC instead. In fact, I've changed it in the 6.0.x version and added even more properties (including `TradingDate` property with `DateOnly` data type), but now I'm thinking that it's not a good idea at all.
- In fact, the `ICalendar.TradingDateUtc` and `ICalendar.TradingDateEst` properties are different. The first one has `DateTimeKind` property equal to `DateTimeKind.Utc` and second one has `DateTimeKind.Undefined` value. Most probably the right solution is to use `DateTimeOffset` data type for the EST time points instead.
- Removing these two properties immediately is a huge breaking change and nobody likes the breaking changes, so I should think about a possible step-by-step removal process using the `Obsolete` attribute over versions. And about the new naming schema of course to make the transition more clear.

I need some time for analyzing the alternatives and propose a better design that will cover all use cases and will provide backward compatibility (or at least a simple transition path) for the existing clients.

**Comment by OlegRa** [comment]
@rudeGit Please, review the new `IIntervalCalender` interface and related extension methods in the latest 6.0.3-alpha1 SDK and provide your feedback. I hope the new approach is a little bit cleaner and this breaking change is worth it.

**Comment by rudeGit** [comment]
Is this the correct way to create the request with desired dates?

```
var request2 = new CalendarRequest().WithInterval(new Interval<DateOnly>(new DateOnly(2022, 1, 10), new DateOnly(2022, 1, 11)));

var intervals = client.ListIntervalCalendarAsync(request2).Result;

foreach (var interval in intervals)
{
    Console.WriteLine($"GetTradingDate: {interval.GetTradingDate()}");
    Console.WriteLine($"interval.Session.OpenEst: {interval.Session.OpenEst}");
    Console.WriteLine($"interval.Session.Local: {interval.Session.OpenEst.ToLocalTime()}");
    Console.WriteLine($"interval.Session.CloseEst: {interval.Session.CloseEst}");
    Console.WriteLine($"interval.Session.Local: {interval.Session.CloseEst.ToLocalTime()}");
    Console.WriteLine($"interval.Trading.OpenEst: {interval.Trading.OpenEst}");
    Console.WriteLine($"interval.Trading.Local: {interval.Trading.OpenEst.ToLocalTime()}");
    Console.WriteLine($"interval.Trading.OpenEst: {interval.Trading.CloseEst}");
    Console.WriteLine($"interval.Trading.Local: {interval.Trading.CloseEst.ToLocalTime()}");
}
```

The construction of the request object seems overly complex to me. I would have expected following to work:

`var request2 = new CalendarRequest(){ new DateOnly(2022, 1, 10), new DateOnly(2022, 1, 11)};

Is there a reason for WithInterval fluid style of implementation? If there are multiple properties that one wants to set, I can understand the fluid style implementation.
