### ISSUE TITLE
.NET Core Usage Example ERROR

### ISSUE THREAD

**Issue by DragonMastery** [alpacahq/alpaca-trade-api-csharp#44]
Here is the full code for the .NET test application and it throws this error:

CS1503	Argument 3: cannot convert from 'System.Uri' to 'string'	

`using System;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri Endpoint = new Uri("https://paper-api.alpaca.markets");
            var KeyId = "my_KEY_ID";
            var SecretKey = "my_SECRET_KEY";
            var client = new Alpaca.Markets.RestClient(
                KeyId, SecretKey, Endpoint);

            var clock = client.GetClockAsync().Result;

            if (clock != null)
            {
                Console.WriteLine(
                    "Timestamp: {0}, NextOpen: {1}, NextClose: {2}",
                    clock.Timestamp, clock.NextOpen, clock.NextClose);
            }
        }
    }
}
`

**Comment by OlegRa** [comment]
@DragonMastery Thank you for pointing this issue! We've made changes in unit tests but (as usual ) have forget to update `README.md` file.
You have to pass URLs in string form if you want to use `RestClient` constructor with default values. If you specify URL using `Uri` object instance you have to provide all 3 used URLs and staging environment flag.
So your code will looks like:
```cs
using System;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var Endpoint = "https://paper-api.alpaca.markets";
            var KeyId = "my_KEY_ID";
            var SecretKey = "my_SECRET_KEY";
            var client = new Alpaca.Markets.RestClient(
                KeyId, SecretKey, Endpoint);

            var clock = client.GetClockAsync().Result;

            if (clock != null)
            {
                Console.WriteLine(
                    "Timestamp: {0}, NextOpen: {1}, NextClose: {2}",
                    clock.Timestamp, clock.NextOpen, clock.NextClose);
            }
        }
    }
}
```
I've updated `README.md` file according to current SDK API.

**Comment by DragonMastery** [comment]
I would also recommend adding these two lines, just so the console does not close without the user seeing what happened.
```
                Console.WriteLine("Press any key to exit...");
                Console.ReadKey();

```
