### ISSUE TITLE
[FEATURE]: Add subscription for updated bars

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#457]
### Is your feature request related to a problem? Please describe.

The Alpaca data streaming clients for stocks and crypto offer a new subscription for the updated bars. The .NET SDK should provide the same feature.

### Describe the solution you'd like

Use related PRs from the other SDKs as a base point for C# implementation:

- Python [#574](https://github.com/alpacahq/alpaca-trade-api-python/pull/574)
- Go [#190](https://github.com/alpacahq/alpaca-trade-api-go/pull/190)
- JS [#195](https://github.com/alpacahq/alpaca-trade-api-js/pull/195)

**Comment by ooples** [comment]
@OlegRa I have several questions for you regarding all of these new subscription methods that have been added. Last time I messed with the data subscription stream was many versions ago when it was just getting second data or minute data. Now I see that the second data stream is gone and there are many many new options for data streams. 

1. Why are the only streams that allow subscribing to all active stocks the GetNewsSubscription and the GetMinuteSubscription? Why don't the other streams support this same behavior?
2. Do you have an updated example or can you share a working example here that uses the latest sdk and is the recommended way to be able to setup a data stream for all symbols that runs on it's own in the background? I have attached my current code that I based on yours with a few changes. I'm assuming nothing substantial has changed but was wondering if this is the most effective way to create a data stream in the background while the program works on other tasks

```
var minuteSubscription = dataStreamingClient.GetMinuteBarSubscription();
        await dataStreamingClient.SubscribeAsync(minuteSubscription).ConfigureAwait(false);
        using var minuteWaitObject = new AutoResetEvent(false);
        using var minuteCancelTokenSource = new CancellationTokenSource();
        _ = Task.Run(async () =>
        {
            await foreach (var item in minuteSubscription
                .AsAsyncEnumerable(minuteCancelTokenSource.Token)
                .ConfigureAwait(false))
            {
                // handle the incoming minute data here
                AddStockData(item);
                minuteWaitObject.Set();
            }
        }, minuteCancelTokenSource.Token).ConfigureAwait(false);
```

**Comment by OlegRa** [comment]
1. The underlying WS API supports wildcard (`*`) subscriptions only for the minute bars and new articles. I think the main problem is the amount of data that potentially can be generated if you'll try to subscribe to **all** quotes or/and trades.
2. Your code is mostly correct but why do you need a separate task for running the `await foreach` loop? The implementation of the asynchronous `foreach` statement never blocks the main execution thread for obtaining the next element from the source sequence. A separate task is needed only if you want to run another code that is placed after the loop before the loop will complete. But in this case, you can just subscribe to `Received` event and do processing in the event handler - it will make your code clearer (IMO).

**Comment by ooples** [comment]
@OlegRa Yeah sorry if I didn't make my description clearer. The reason for me writing the code like this is because I want to subscribe to all of the data streams then run code after the loop before waiting for the loop to complete. Basically I want this loop to be running on it's own in the background while the program continues with other processes. I believe the reason we had a discussion before about this and there was a reason why you recommended going the async enumerable route instead of the subscription event route. Which case do you recommend for my use case where I want to continue code after the loop without waiting for the loop to finish?

**Comment by OlegRa** [comment]
It depends on your application's internal structure/architecture. In most cases, the event-based approach is the simplest and most convenient option. The asynchronous enumerable internally just subscribe on an event and push it into a temporary channel/pipe for async reading on the caller side.

**Comment by ooples** [comment]
@OlegRa Any reason why the cancel subscription only allows a max of one symbol and not a list of symbols to subscribe to?

**Comment by OlegRa** [comment]
I've just forgotten to add extension methods for these subscription types into the Extensions SDK. I'll add them soon - most probably this week.
