### ISSUE TITLE
Handling results of calendar requests

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#459]
@OlegRa  So unless I'm doing something wrong then I found a bug with this process. I live in the eastern time zone so I used the market open and close hours in my local time in the historical bars request and received bars between 09:30 to 16:00 in UTC which is essentially the pre market hours. You should be able to check this on your end but I can show a screenshot and/or code if you need it. Also the code I sent you would be useful for replacing the Calendar code which I have found to be difficult and I have a way to be able to get the last x bars using my calendar. If you would like I can send you some code in an email outlining how this can work

_Originally posted by @ooples in https://github.com/alpacahq/alpaca-trade-api-csharp/issues/455#issuecomment-1047406312_

**Comment by OlegRa** [comment]
There is a code example for SDK 6.0.x that get all 15 minutes bars for the specific day:

```cs
var date = new DateOnly(2022, 2, 18);
var key = new SecretKey("...", "...");

using var tradingClient = Environments.Paper.GetAlpacaTradingClient(key);

var calendars = await tradingClient.ListIntervalCalendarAsync(
    CalendarRequest.GetForSingleDay(date)).ConfigureAwait(false);

var calendar = calendars.Single();

var sessionInterval = calendar.Session.ToInterval();
var tradingInterval = calendar.Trading.ToInterval();

Console.WriteLine("\t\tOpen (EST)\t\t\tClose (EST)\t\t\tOpen (UTC)\t\tClose (UTC)");
Console.WriteLine($"Session\t\t{calendar.Session.OpenEst}\t{calendar.Session.CloseEst}\t{sessionInterval.From}\t{sessionInterval.Into}");
Console.WriteLine($"Trading\t\t{calendar.Trading.OpenEst}\t{calendar.Trading.CloseEst}\t{tradingInterval.From}\t{tradingInterval.Into}");

using var dataClient = Environments.Paper.GetAlpacaDataClient(key);

var fifteenMinutesBars = new BarTimeFrame(15, BarTimeFrameUnit.Minute);

var tradingBars = await dataClient.ListHistoricalBarsAsync(new HistoricalBarsRequest(
    "GOOG", fifteenMinutesBars, calendar.Trading)).ConfigureAwait(false);

var sessionBars = await dataClient.ListHistoricalBarsAsync(new HistoricalBarsRequest(
    "GOOG", fifteenMinutesBars, calendar.Session)).ConfigureAwait(false);

Console.WriteLine("\r\n\t\tCount\tFirst (UTC)\t\tLast (UTC)");
Console.WriteLine($"Session\t\t{sessionBars.Items.Count}\t{sessionBars.Items.First().TimeUtc}\t{sessionBars.Items.Last().TimeUtc}");
Console.WriteLine($"Trading\t\t{tradingBars.Items.Count}\t{tradingBars.Items.First().TimeUtc}\t{tradingBars.Items.Last().TimeUtc}");

```

This code snipped produces the next output on my side (UTC+2:00 time zone now):

```
                Open (EST)                      Close (EST)                     Open (UTC)              Close (UTC)
Session         2/18/2022 7:00:00 AM -05:00     2/18/2022 7:00:00 PM -05:00     2/18/2022 12:00:00 PM   2/19/2022 12:00:00 AM
Trading         2/18/2022 9:30:00 AM -05:00     2/18/2022 4:00:00 PM -05:00     2/18/2022 2:30:00 PM    2/18/2022 9:00:00 PM

                Count   First (UTC)             Last (UTC)
Session         38      2/18/2022 12:00:00 PM   2/18/2022 11:30:00 PM
Trading         27      2/18/2022 2:30:00 PM    2/18/2022 9:00:00 PM
```

**Comment by OlegRa** [comment]
The main problem with date/times in .NET is that it's not clear how to properly work with time zones. The only good approach for handling different time zones is the `DateTimeOffset` type but it also has some limitations. My initial approach about using date/time data in SDK was **UTC-only** API but some users want to see calendar data in EST and it's the reason why I've added the related properties into the `ICalendar` interface.

Unfortunately, I've used the `DateTime` data type instead of the `DateTimeOffset` type because I've thought these properties (with the `Est` suffix) will be used only for display purposes. The `Kind` property of these values is `DateTimeKind.Unspecified` and from the serialization perspective it's equal to `UTC` because no time zone is treated as a default time zone (UTC).

Your code has the same problem - it uses the `TimeZoneInfo.ConvertTimeFromUtc` and this method will return the `DateTime` object with the `Unspecified` value of `Kind` property even if you run it on PC with EST time zone enabled. The only proper way to represent date/times in some shared code (like this SDK) is to use UTC in all possible cases.

The new `OpenClose` struct returns the `DateTimeOffset` values for open and close time respectively because it's only one possible way to represent EST timezone correctly on any computer. And this type can be implicitly converted into the `Interval<DateTime>` type so you can use it directly for requesting data (see example above).

**Comment by ooples** [comment]
@OlegRa So first off if I'm understanding this correctly Session in your example is supposed to represent the extended hours and Trading represents the normal hours? Also below is the code I used to get the historical bars using my local time and you can check the results if you want.

This doesn't work:
```
var startDate = new DateTime(2021, 02, 21, 9, 30, 0);
var endDate = new DateTime(2021, 02, 21, 16, 0, 0);
var bars = await GetHistoricalBars(new HistoricalBarsRequest("GOOG", 
startDate, endDate, BarTimeFrame.Minute)).ConfigureAwait(false);
```

This works:
```
var startDate = new DateTime(2021, 02, 21, 9, 30, 0);
var endDate = new DateTime(2021, 02, 21, 16, 0, 0);
var bars = await GetHistoricalBars(new HistoricalBarsRequest("GOOG", startDate.ToUniversalTime(), 
endDate.ToUniversalTime(), BarTimeFrame.Minute)).ConfigureAwait(false);
```

That being said I do understand the issue is related to the Unspecified kind and I think the easiest solution would be to use UTC only for the api requests like you originally wanted but I guess I'm not understanding why you can't handle all requests with UTC and still use the OpenClose struct to return the UTC date to Eastern Time like you are doing now

**Comment by ooples** [comment]
@OlegRa Trying to run your code using the latest version for the sdk gives GetForSingleDay(date) is obsolete so did you have a newer replacement for this use case in mind?

**Comment by OlegRa** [comment]
Most values returned and accepted by Alpaca APIs are in UTC the calendar endpoint is the only place where the EST time zone is used. Of course, I can make SDK UTC-only but I think more flexibility is better even if it leads to some problems.

1. If you create the `DateTime` object manually it will have `Unspecified` date/time kind by default. You can provide another value (`Local` or `Utc`) as an additional (rarely used) constructor parameter or use the static method `DateTime.SpecifyKind` but both approaches work fine only with UTC data. The local time zone is a dangerous concept - it can change during your process lifetime!
2. The `OpenClose` struct returns the `DateTimeOffset` objects with EST timestamps for two main reasons - the SDK should (IMO) provide access to underlying API data (in this case all data in the response is in EST timezone) and some users need this exact values. Of course, I can just return UTC values but converting it back into EST properly is not easy and it's easier for me to construct these values from underlying JSON in this form. Moreover, it's not a problem - I've added a lot of helper extension methods for getting UTC date/time values from the `IIntervalCalendar` interface instance and the `OpenClose` struct has an implicit conversion operator that allows you to use it directly in any place where `Interval<DateTime>` type is expected.
3. The `GetForSingleDay` method now expects the `DateOnly` type instead of `DateTime` because, in fact, the underlying REST API endpoint accepts only date values. You can easily create the `DateOnly` object using the same approach as you use for the 'DateTime` - just by year/month/day specifying in the constructor. Or you can use the `DateOnly.FromDateTime` factory method for converting the `DateTime` value into the `DateOnly` one.
4. Yes, the bar re-sampling is done on the server-side. AFAIK the Alpaca caches most used bar sizes (5-, 15-, 30- minutes bars, etc.) but you can even request a 12-minutes bar and the server will do all heavy work for you.

**Comment by ooples** [comment]
@OlegRa I'm not sure why I couldn't find the original issue for it but for the stock indicator library example it looks good and much better than my version but the only issue is if you clear the signals list after each call then you should also clear the custom values list as well
