### ISSUE TITLE
[BUG]: While using PageToken in GetHistoricalBarsAsync to get the next page of symbols, it include one symbol of a previous page.

### ISSUE THREAD

**Issue by tcj2001** [alpacahq/alpaca-trade-api-csharp#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While using PageToken to get the next page of symbols, it includes one symbol of a previous page.               

- Selected asset is a list of 5000 symbols
- BarTimeFrameUnit is 1 Day
- BarTimeFrameCount is 30 

maximum 5000 was used since we cannot pass more than that 5000 symbols as listed to the API (GetHistoricalBarsAsync)

```cs
var ListOfSymbolAndItsBars = await ListHistoricalBars(selectedAssets, BarTimeFrameUnit, BarTimeFrameCount, 5000);

public async Task<Dictionary<string, IReadOnlyList<IBar>>> ListHistoricalBars(IEnumerable<string> symbols, BarTimeFrameUnit barTimeFrameUnit, int barTimeFrameCount, int symbolCount)
{
    //get the interval based on barTimeFrameUnit, barTimeFrameCount and date  (barTimeFrame can be 20Day, 15Min, 5Weeks etc)
    //used to get historical bar
    var iInclusiveTimeInterval = await GetTimeIntervalFrom(new BarTimeFrame(barTimeFrameCount, barTimeFrameUnit), DateTime.UtcNow);

    //define barTimeFrame of one unit required by the api
    var barTimeFrame = new BarTimeFrame(1, barTimeFrameUnit);

    //Dictionary to hold symbol and historical bars
    Dictionary<string, IReadOnlyList<IBar>> keyValues = new();

    //get a historical bars and snapshots of symbols 5000 at a time
    for (int i = 0; i <= symbols.Count(); i += symbolCount)
    {
        var symbolsSubSet = symbols.Skip(i).Take(symbolCount);
        var historicalBarsRequest = new HistoricalBarsRequest(symbolsSubSet, iInclusiveTimeInterval, barTimeFrame);
        var pageToken = "";
        do
        {
            var historicalBars = await alpacaDataClient.GetHistoricalBarsAsync(historicalBarsRequest, token);
            foreach (var bars in historicalBars.Items)
            {
                try
                {
                    keyValues.Add(bars.Key, bars.Value);
                }
                catch(Exception e) 
                {
                    var x = e;
                    //An item with the same key has already been added. Key: GRNB
                }
            }
            pageToken = historicalBars.NextPageToken;
            historicalBarsRequest = historicalBarsRequest.WithPageToken(pageToken);
        } while (pageToken != null);
    }
    return keyValues;
}

public async Task<IInclusiveTimeInterval> GetTimeIntervalFrom(BarTimeFrame barTimeFrame, DateTime utcDate)
{
    DateTime newDate = utcDate;
    switch (barTimeFrame.Unit) 
    {
        case BarTimeFrameUnit.Minute:
            newDate = utcDate.AddMinutes(-barTimeFrame.Value);
            break;
        case BarTimeFrameUnit.Hour:
            newDate = utcDate.AddHours(-barTimeFrame.Value);
            break;
        case BarTimeFrameUnit.Day:
            newDate = utcDate.AddDays(-barTimeFrame.Value);
            break;
        case BarTimeFrameUnit.Week:
            newDate = utcDate.AddDays(-barTimeFrame.Value * 7);
            break;
        case BarTimeFrameUnit.Month:
            newDate = utcDate.AddMonths(-barTimeFrame.Value);
            break;
    }
    return TimeInterval.GetInclusiveIntervalFromThat(newDate);
}
```

### Expected Behavior

Each page retrieved should have unique symbols

### Steps To Reproduce

I have pasted the method that can be called by passing the following params

- List: list of 5000 symbols
- BarTimeFrameUnit is 1 Day
- BarTimeFrameCount is 30

### Environment

- SDK Version: Latest
- .NET SDK (version): .NET 6.0

**Comment by OlegRa** [comment]
@tcj2001 I don't know why do you expect this behavior (only a single symbol per page and/or all bars for a single symbol on one page). Each response page can contain ANY number of symbols and symbol data can be distributed over several response pages. The pagination is based on page size (number of items) not on the page content (symbols). This behavior is implied by the server-side API and the client SDK unable to do anything with it.

I see the next solutions for your "problem":

1. Just `TryGetValue` with constructor + `AddRange` approach for maintaining the proper bars list instead of simple `Add` call inside your while loop. It's not hard to implement and in fact, it's only the proper way to handle API data in this case.
2. Just use the Extensions package - it contains a set of helper methods for handling pagination and wrapping the results in the proper way. Some of these methods are described on [Wiki](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Alpaca-REST-API#pagination-support) but there are a lot more methods that allow you to handle pages in a more simple way.

**Comment by tcj2001** [comment]
Thankyou for pointing me in the right direction, now I have simplified my method

        /// <summary>
        /// List of symbols and its Bars
        /// </summary>
        /// <param name="symbols"></param>
        /// <param name="barTimeFrameUnit"></param>
        /// <param name="barTimeFrameCount"></param>
        /// <param name="symbolCount"></param>
        /// <param name="toDate"></param>
        /// <returns></returns>

        public async Task<Dictionary<string, List<IBar>>> ListHistoricalBars(IEnumerable<string> symbols, BarTimeFrameUnit barTimeFrameUnit, int barTimeFrameCount, int symbolCount, DateTime toDate)
        {
            //get the FromDate based on barTimeFrameUnit, barTimeFrameCount and toDate  (barTimeFrame can be 20Day, 15Min, 5Weeks etc)
            var fromDate = await GetTimeIntervalFrom(new BarTimeFrame(barTimeFrameCount, barTimeFrameUnit), toDate);

            //define barTimeFrame of one unit required by the api
            var barTimeFrame = new BarTimeFrame(1, barTimeFrameUnit);

            //List to hold bars
            List<IBar> bars = new();
            Dictionary<string, List<IBar>> symbolAndBars = new();
            //get a historical bars and snapshots of symbols 5000 at a time
            for (int i = 0; i < symbols.Count(); i += symbolCount)
            {
                var symbolsSubSet = symbols.Skip(i).Take(symbolCount);
                var historicalBarsRequest = new HistoricalBarsRequest(symbolsSubSet, fromDate, toDate, barTimeFrame);
                await foreach (var bar in alpacaDataClient.GetHistoricalBarsAsAsyncEnumerable(historicalBarsRequest, token))
                {
                    bars.Add(bar);
                }
            }
            symbolAndBars = bars.GroupBy(x => x.Symbol).ToDictionary(g => g.Key, g => g.ToList());
            return symbolAndBars;
        }

        /// <summary>
        /// Calculates the from DateTime based on current Date and BartTimeFrame
        /// </summary>
        /// <param name="barTimeFrame"></param>
        /// <param name="toDate"></param>
        /// <returns></returns>
        public async Task<DateTime> GetTimeIntervalFrom(BarTimeFrame barTimeFrame, DateTime toDate)
        {
            DateTime fromDate = toDate;
            switch (barTimeFrame.Unit) 
            {
                case BarTimeFrameUnit.Minute:
                    fromDate = toDate.AddMinutes(-barTimeFrame.Value);
                    break;
                case BarTimeFrameUnit.Hour:
                    fromDate = toDate.AddHours(-barTimeFrame.Value);
                    break;
                case BarTimeFrameUnit.Day:
                    fromDate = toDate.AddDays(-barTimeFrame.Value);
                    break;
                case BarTimeFrameUnit.Week:
                    fromDate = toDate.AddDays(-barTimeFrame.Value * 7);
                    break;
                case BarTimeFrameUnit.Month:
                    fromDate = toDate.AddMonths(-barTimeFrame.Value);
                    break;
            }
            return fromDate;
        }
