### ISSUE TITLE
[BUG]: Does not list any Crypto Assets

### ISSUE THREAD

**Issue by tcj2001** [alpacahq/alpaca-trade-api-csharp#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```cs
var selectedAssets = assets.Where(x => x.Class == AssetClass.Crypto ).Select(x => x.Symbol).ToList();
var selectedAssets1 = assets.Where(x => x.Symbol == "BTCUSD").Select(x => x.Symbol).ToList();
```

Both return zero count

**Comment by OlegRa** [comment]
@tcj2001 The underlying REST API was introduced years ago and its default behavior is a little bit unexpected nowadays. The `AssetClass` property of the `AssetRequest` type is nullable and if you don't specify anything it will request only stock assets. It was OK for years and changing this behavior can break existing code. All that I can do is just write more detailed documentation for this property. Unfortunately, you are unable to request both stocks and crypto assets in one request. You have to do two separate requests and specify the asset class explicitly. You can elevate this question to Alpaca's main team but I'm not sure they have enough time/reasons to add another endpoint just for this rare case.

**Comment by tcj2001** [comment]
Got it
