### ISSUE TITLE
Add support for Crypto FTXU Exchange

### ISSUE THREAD

**Issue by matt953** [alpacahq/alpaca-trade-api-csharp#475]
Hi,

Is it possible to add support for the FTXU exchange in the SDK. 

The FTXU exchange code is referred to in the docs.

https://alpaca.markets/docs/api-references/market-data-api/crypto-pricing-data/

It's currently the only exchange to provide market data for the new crypto symbols that have been released.

Thanks

**Comment by OlegRa** [comment]
@matt953 You can use the new `Ftx` enum member in [SDK 5.2.11](https://www.nuget.org/packages/Alpaca.Markets/5.2.11) and later. Please, test and close this issue if problem is solved.
