### ISSUE TITLE
[QUESTION]: Corporate Actions API Support

### ISSUE THREAD

**Issue by JasonAr936** [alpacahq/alpaca-trade-api-csharp#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Hi,

Is it possible to add support for the corporate actions API to the c# SDK?

This is the link to the Trading API docs for corporate actions.

[https://alpaca.markets/docs/api-references/trading-api/corporate-actions-announcements/](https://alpaca.markets/docs/api-references/trading-api/corporate-actions-announcements/) 

Thanks

**Comment by OlegRa** [comment]
@JasonAr936 The support for the requested endpoints was added into the [5.2.12](../releases/tag/sdk-5.2.12) release of SDK. Please, test it and close the issue if you are OK with the current implementation.
