### ISSUE TITLE
SockClient fails to catch errors when JSON parsing fails.

### ISSUE THREAD

**Issue by scyentyfyc** [alpacahq/alpaca-trade-api-csharp#48]
I ran into a scenario where JSON parsing failed in the SockClient, and the exception crashed my application.  The error was related to the fact that TradeUpdate.Event != OrderStatus, e.g. TradeUpdate.Event will be "fill" instead of "filled".  I believe I've fixed those scenarios in the API v02 PR, but would expect that in the event of such exceptions, that they be caught and reported via the SockClient.OnError event, rather than throwing an exception I have no way to catch.

**Comment by OlegRa** [comment]
Will check it tomorrow.

**Comment by OlegRa** [comment]
@scyentyfyc Fixed in `develop` branch, will be included in upcoming 3.0.0-beta release.

**Comment by OlegRa** [comment]
Can be tested in [3.0.1-beta](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.0.1-beta) release.

**Comment by scyentyfyc** [comment]
@OlegRa , I looked at the code, and the NatsClient was fixed up nicely.  However, the subject of this bug was the SockClient (though I see now both were similar).  to be more specific, the following code block get's called by an event, and if the `data.ToObject<JsonTradeUpdate>());` throws an exception, it doesn't get caught / handled / reported.  I know I wasn't nearly this explanatory in the initial request, I hope this helps clarify.

```
        private void handleDataReceived(
            Object sender,
            DataReceivedEventArgs e)
        {
            var message = Encoding.UTF8.GetString(e.Data);
            var root = JObject.Parse(message);

            var data = root["data"];
            var stream = root["stream"].ToString();

            switch (stream)
            {
                case "authorization":
                    handleAuthorization(
                        data.ToObject<JsonAuthResponse>());
                    break;

                case "listening":
                    Connected?.Invoke(AuthStatus.Authorized);
                    break;

                case "trade_updates":
                    handleTradeUpdates(
                        data.ToObject<JsonTradeUpdate>());
                    break;

                case "account_updates":
                    handleAccountUpdates(
                        data.ToObject<JsonAccountUpdate>());
                    break;

                default:
                    OnError?.Invoke(new InvalidOperationException(
                        $"Unexpected message type '{stream}' received."));
                    break;
            }
        }
```

**Comment by OlegRa** [comment]
@scyentyfyc I think @ttt733 will publish official 3.0.1 release soon so this fix will be included into it.
