### ISSUE TITLE
Add helper method(s) for checking session state

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#485]
One of the most widely spread patterns of the `GetClockAsync` method usage is checking the current session state. But each call of this method is time-consuming and affects the rate limit of API calls. The general idea of caching some API calls is good but requires more changes in the underlying SDK but we can implement helper methods for this particular case:

- [x] Implement the special version of the `GetClockAsync` method which will return the cached version of the original call if it's appropriate or re-request data from API if cached data is obsolete.
- [x] Implement the helper methods for quickly checking the trading/session state based on data returned by the previous method.

The original source code posted in Slack by @ManfredLange:

```cs
public async Task<bool> MarketIsOpenAsync()
{
   var now = DateTime.UtcNow;
   if(_clock == null || _clock.NextCloseUtc < now)
   {
      _clock = await AlpacaTradingClient.GetClockAsync(); // costs about 250 ms roundtrip
   }
   // Console.WriteLine($"\tNext open: {_clock.NextOpenUtc:O}. Next close: {_clock.NextCloseUtc:O}");
   return now >= _clock.NextOpenUtc && now <= _clock.NextCloseUtc;
}
```

**Comment by ooples** [comment]
@OlegRa I created a pull request just now for this issue showing my code is much faster than what you have currently and I think this will work perfectly for this library

**Comment by ooples** [comment]
@OlegRa Did you take a look at my pull request code?

**Comment by ooples** [comment]
@OlegRa Any further work I need to do to merge these changes with the api?

**Comment by OlegRa** [comment]
@ooples I'm unable to merge it into the SDK package for several reasons:

1. Alpaca tries to provide the same set of features across all SDKs. I'm not sure that even if I'll port this algorithm into JS+Python+Go these PRs will be accepted.
2. The SDK is a wrapper for Alpaca API (REST and WS) and not just a collection of useful algorithms. Your code is good but it has no relation to the Alpaca API.
3. Instead of server-side DB for trading days your code doesn't contain any exceptional cases (the 9/11-related changes are the first that comes to mind) and it would be hard to maintain such a list of exceptions if you'll add it. So it's good enough for anyone who knows its limitations but not 100% good for any use case.

I'm thinking about adding this into the Extensions package (it can contain code that violates 1st and 2nd rules) but I'm still thinking about the 3rd rule. I'm not sure that all users read the documentation and therefore adding such a method to the public package can produce a lot of questions from the consumers.
