### ISSUE TITLE
[BUG]:  Sub-penny increment does not fulfill minimum pricing criteria

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the latest prerelease for the SDK and this is a brand new error for me. Does this mean that we are supposed to use buy and sell prices with a max of 2 decimal points? 

### Expected Behavior

I would hope for a slightly clearer error if there is a max of 2 decimal points since some stock prices have bid and ask prices of 3 decimal points. My best guess is that any price over $1 has a max of 2 decimal points and anything less than $1 has a different max allowed? Can you please confirm?

### Environment

```markdown
Latest Prerelease SDK
```

### Anything else?

Wasn't able to place a sell order for the following:

Error placing Sell order: 
invalid limit_price 11.055. sub-penny increment does not fulfill minimum pricing criteria
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
invalid limit_price 11.055. sub-penny increment does not fulfill minimum pricing criteria

But this order was able to placed without an issue:
Submitted Limit Sell order for 33399 AEI shares at $0.6013

**Comment by OlegRa** [comment]
The `RestClientErrorException` in most cases is generated from server-side errors. Maybe, in a future release, I'll introduce the better exception handling with different exception types for client-side and server-side errors (with the same base class for simpler handling) but not in the 6.0 - I don't want to make any breaking changes in this release anymore.

We are unable to do anything useful with server-side limitations in the SDK code so I suggest you escalate this question to Alpaca support. AFAIR the minimal tick size is managed by exchange and can be different for different assets. Unfortunately, the Alpaca API doesn't provide this information about assets.

**Comment by OlegRa** [comment]
Comment for the public Alpaca Slack channel (quote from the SEC website):

> In general, the Rule prohibits market participants from displaying, ranking, or accepting quotations, orders, or indications of interest in any NMS stock priced in an increment smaller than $0.01 if the quotation, order, or indication of interest is priced equal to or greater than $1.00 per share. If the quotation, order, or indication of interest is priced less than $1.00 per share, the minimum pricing increment is $0.0001.
