### ISSUE TITLE
[BUG]: TimeZone conversion for Linux

### ISSUE THREAD

**Issue by logmd** [alpacahq/alpaca-trade-api-csharp#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Time conversion on UNIX (Linux docker on windows/ amazon Linux on AWS) throws an exception.
the timezone IDs are different on Windows and Linux.

### Expected Behavior

To get a response when sending a calendar request on Linux as you would on windows

### Steps To Reproduce

Execute the following on a Linux environment

```csharp
// ... set credentials here
var client = Environments.Paper.GetAlpacaTradingClient(creds);
var request = new CalendarRequest(new DateOnly(2022,05,31), new DateOnly(2022,05,31));
var result = await client.ListIntervalCalendarAsync(request);
```

based on stack trace this is what will cause the issue:

```csharp
System.TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time")
```

### Environment

- SDK Version: 6.0.3 (6.0.3.10)
- OS (version, bitness): linux, 64 bit
- .NET SDK (version): dotnet 6.0
- target process .NET version/bitness: 64 bit

### Anything else?

stack trace
```json
"cause": {
    "errorType": "TypeInitializationException",
    "errorMessage": "The type initializer for 'Alpaca.Markets.CustomTimeZone' threw an exception.",
    "stackTrace": [
      "at Alpaca.Markets.JsonCalendar.OnDeserializedMethod(StreamingContext _)"
    ],
    "cause": {
      "errorType": "TimeZoneNotFoundException",
      "errorMessage": "The time zone ID 'Eastern Standard Time' was not found on the local computer.",
      "stackTrace": [
        "at System.TimeZoneInfo.FindSystemTimeZoneById(String id)",
        "at Alpaca.Markets.CustomTimeZone..cctor()"
      ],
      "cause": {
        "errorType": "FileNotFoundException",
        "errorMessage": "Could not find file '/usr/share/zoneinfo/Eastern Standard Time'.",
        "stackTrace": [
          "at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)",
          "at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)",
          "at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)",
          "at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)",
          "at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)",
          "at System.IO.File.ReadAllBytes(String path)",
          "at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)"
        ]
      }
    }
  }
```

below is from debugging instance in the AWS Linux container:

![image](https://user-images.githubusercontent.com/5808777/170894951-6881f020-83a7-4c5d-8e4f-0933498126a8.png)
and doing the following works for Linux and returns one of the eastern standard times

```cs
System.TimeZoneInfo.FindSystemTimeZoneById("America/Tijuana");
```

**Comment by OlegRa** [comment]
@logmd I've tested this change for several months on different OS/bitness combinations. But looks like I've got the initial idea behind the `TimeZoneInfo` [changes in .NET 6.0](https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#time-zone-display-names-on-linux-and-macos) incorrectly. 
I've decided initially to use the Windows time zone identifier on all platforms. But it works only if the target Linux system has both `tzdata` and `libicu` packages installed. Most of my test systems have both these packages so it works for me. But it would be impractical to force all users to install these packages on their target systems.
I'll prepare the new version of the SDK package that will use the IANA time zone name in case of the .NET 6 runtime. AFAIU this approach should work on Windows too without any additional soft installed. I just need time for testing this change before publishing the updated release.

**Comment by OlegRa** [comment]
@logmd Could you please test the pre-release version [6.0.4-beta1](../releases/tag/sdk-6.0.4-beta1) and confirm that problem is gone in your environment? As soon as I'll receive your confirmation I prepare a normal release.

**Comment by ooples** [comment]
@OlegRa I also use Linux as a test environment and I can confirm that this new version works for my os which is Ubuntu 20.04

**Comment by logmd** [comment]
> @logmd I've tested this change for several months on different OS/bitness combinations. But looks like I've got the initial idea behind the `TimeZoneInfo` [changes in .NET 6.0](https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#time-zone-display-names-on-linux-and-macos) incorrectly. I've decided initially to use the Windows time zone identifier on all platforms. But it works only if the target Linux system has both `tzdata` and `libicu` packages installed. Most of my test systems have both these packages so it works for me. But it would be impractical to force all users to install these packages on their target systems. I'll prepare the new version of the SDK package that will use the IANA time zone name in case of the .NET 6 runtime. AFAIU this approach should work on Windows too without any additional soft installed. I just need time for testing this change before publishing the updated release.

from what i understand i think the fixes in .net wont be until .net 7 😢 (however its in preview i think)

in regards to the beta, works fine on my local docker instance now 👍 
ill put something in my lower environment (aws lambda) ill give it a test and report back
