### ISSUE TITLE
[BUG]: The server returned status code '429' when status code '101' was expected

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So it does reconnect when it loses internet connection which is why I closed the original issue but a major side effect I'm noticing now is that when it does attempt to reconnect, I'm getting these error messages very often (error count is over 100 so far). I realize this error message is for doing too many requests but is there anything we can do on the sdk side to limit this? This is the first time I have seen these error messages after testing with these most recent versions

### Expected Behavior

Should be a way to either hide these errors or try to limit their occurence

### Environment

- SDK Version: 6.0.4-beta2
- OS (version, bitness): Windows 10 x64
- .NET SDK (version): 6.0
- target process .NET version/bitness: 6.0 x64

**Comment by ooples** [comment]
@OlegRa It is just this repeated hundreds of times:

```
Alpaca data streaming client error: The server returned status code '429' when status code '101' was expected.
Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
The server returned status code '429' when status code '101' was expected.

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client

Alpaca data streaming client error: The server returned status code '429' when status code '101' was expected.
Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
The server returned status code '429' when status code '101' was expected.

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client
```

**Comment by OlegRa** [comment]
@ooples Please, test suppression logic in the [6.0.4-beta2](../releases/tag/ext-6.0.4-beta2) release of Extensions package.

**Comment by ooples** [comment]
@OlegRa It works like a dream! This is the first full day of running my program that I didn't receive a single error message so big thanks to your great work!
