### ISSUE TITLE
[FEATURE]: Add possible exceptions to Alpaca API methods

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

As is default with .net methods, you can see the following for the Console.WriteLine method which shows all possible exceptions from any method.

![image](https://user-images.githubusercontent.com/4800940/174467770-78927f7e-f8ee-4e87-a6b0-52f2a7c6dc31.png)

### Describe the solution you'd like

I would like to have possible exceptions for each alpaca API method added to the method documentation. For example, this is what I see for ListOrdersAsync

![image](https://user-images.githubusercontent.com/4800940/174467781-db14d822-1fba-4232-a431-38af43c3db53.png)

**Comment by OlegRa** [comment]
@ooples You can check how well it works after upgrading to version 6.0.5 of [SDK](../releases/tag/sdk-6.0.5) and [Extensions](../releases/tag/ext-6.0.5) packages. Both packages now contain XML documentation with exceptions information for the most public methods.
