### ISSUE TITLE
Add new authentication status

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#531]
Current `AuthStatus` enum hides all cases of unsuccessful authentications under one `Unauthorized` value. But it can confuse SDK users if they provide the correct authentication data but the server denied the connection because the same credentials were already used for the other working connection. The proposed solution - add the new ` TooManyConnections` value into the `AuthStatus` enum and use it properly inside the data streaming clients.

**Comment by ooples** [comment]
I love this concept!
