### ISSUE TITLE
[BUG]: Historical Bars Request missing parameters

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to the sdk documentation there are missing parameters: https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/historical/#bars

HistoricalBarsRequest only contains parameters for Symbol, StartDate, EndDate, and BarTimeFrame and is missing limit, page_token, adjustment, and feed so unless I'm missing something, how are we supposed to specify those parameters when creating a request to get historical bars?

### Environment

```markdown
SDK Version: 6.0.5
OS (version, bitness): Windows 10
.NET SDK (version): 6.0
target process .NET version/bitness: 6.0 x64
```

**Comment by OlegRa** [comment]
The `HistoricalBarsRequest` class provides a way for specifying all possible request parameters available on API. Some of these parameters are required (symbol, bar time frame) and it's a reason why they should be provided via a class constructor. The time interval, in fact, is optional but in most practical cases you have to specify it and it's a reason why it is provided via constructor too. Other parameters are truly optional and they are exposed in SDK as class properties with the `null` default values:

- The `adjustment` parameter can be specified via the `Adjustment` property.
- The `feed` parameter can be specified via the `Feed` property.
- The `limit` parameter can be specified via the `Pagination.Size` property.
- The `page_token` parameter can be specified via the `Pagination.Token` property.
- The `as` parameter can be specified via the `UseSymbolAsOfTheDate` property.


See the next example that uses all the available properties:

```cs
var bars = await client.ListHistoricalBarsAsync(new HistoricalBarsRequest("AAPL",
    new BarTimeFrame(3, BarTimeFrameUnit.Minute), new Interval<DateTime>(
        new DateTime(2022, 04, 08), new DateTime(2022, 04, 09)))
{
    Adjustment = Adjustment.SplitsAndDividends,
    Feed = MarkedDataFeed.Otc,
    Pagination =
    {
        Token = Guid.NewGuid().ToString(), // Just for demo - makes no sense
        Size = 100
    }
});
```

The Visual Studio (and I believe other IDEs too) provides a list of available properties via the IntelliSense hints:

![image](https://user-images.githubusercontent.com/4800940/178716463-b3c43acb-1f3c-4529-a9ac-29e4680ed61a.png)

**Comment by ooples** [comment]
@OlegRa I didn't see anything in IntelliSense hints so not sure where you went to see that info but your example helped to clear things up. I do have some quick comments and a question about the Pagination.MaxPageSize = ? vs the Pagination = { Size = ? }

What are the differences between these two variables which seem to the be the same thing and can you please edit the descriptions so it specifies what the default values are since I'm not seeing that anywhere.

**Comment by OlegRa** [comment]
1. The `MaxPageSize` is just a constant required for implementing helper extension methods that allow requesting all data from the server side as a single `IAsyncEnumerable` sequence.
2. The `Pagination` class is used for both stock/crypto data and news articles requests and these endpoints have different default page sizes. In most cases, you never specify the page size and just use the server-side defaults.
3. Property renaming is breaking change and I don't see any reason to make this renaming - extensions package [provides helper methods](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Alpaca-REST-API#pagination-support) for handling paging and in most cases, a user will not manipulate the `Pagination` object manually.
