### ISSUE TITLE
[BUG]: Historical Trades Request missing parameters

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to the sdk documentation there are missing parameters: https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/historical/#trades

HistoricalTradesRequest only contains parameters for Symbol, StartDate, and EndDate and is missing limit, page_token, and feed so unless I'm missing something, how are we supposed to specify those parameters when creating a request to get historical trades?

### Environment

```markdown
SDK Version: 6.0.5
OS (version, bitness): Windows 10
.NET SDK (version): 6.0
target process .NET version/bitness: 6.0 x64
```

**Comment by OlegRa** [comment]
See my comment in issue #532 about required/optional request parameters in SDK request types.
