### ISSUE TITLE
Nuget 3.0.1 Update to Alpaca is not correct

### ISSUE THREAD

**Issue by Ronmenator** [alpacahq/alpaca-trade-api-csharp#55]
My application used the Nuget package and this morning I updated it, but the Nuget package for 3.0.1 does not contain some of the API. e.g. Post orders, list orders, GetAccountAsync, etc...

After downloading the source repository and compiling it in my project, those functions now are available.

Don't know if the Nuget got corrupted or something is missing with it.

EDIT:

E.g.

            Client = new RestClient(key, pkey, url);
            Account = await Client.GetAccountAsync();
            var clock = await Client.GetClockAsync();

GetAccountAsync(), and GetClockAsync() is not in the Repository.

**Comment by OlegRa** [comment]
@ttt733 I've checked binaries available on NuGet and unfortunately they really doesn't contains these (and many other) methods. I'm unable to find information about AppVeyor build - please, add at least build bage into Readme.MD file for quick navigation to last build. And it would be nice if build will add release record into GitHub.

**Comment by OlegRa** [comment]
@Ronmenator Please, try to use release 3.0.2 - it should contains missed API methods.

**Comment by Ronmenator** [comment]
I will try now and revert with result

**Comment by Ronmenator** [comment]
Thank you @OlegRa, all fixed in 3.0.2
