### ISSUE TITLE
[QUESTION]: Stream subscription and request rates

### ISSUE THREAD

**Issue by Ilya171** [alpacahq/alpaca-trade-api-csharp#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Hi, i use this script to get real time price

```cs
await using var subscription1 = await client.SubscribeTradeAsync(gameObject.GetComponent<SettingsControllScr>().NameS);                
await foreach (var trade in subscription1.AsAsyncEnumerable(cancellationTokenSource.Token).ConfigureAwait(false))
{
    Debug.Log($"Trade received for the {trade.Symbol} {trade.Price} {trade.TimestampUtc} contract");
    SetPrice(trade);
} 
```
            
I want to receive the price of 5 shares at the same time, but I have a free account, so I have 200 requests per minute
That is why 200 requests do not work for all promotions for me, and some promotions do not show the price
How can I give each share 40 requests?

**Comment by OlegRa** [comment]
@Ilya171 It's not clear to me what is your exact problem. AFAIU you can subscribe to 5 symbols via WebSocket stream using the SDK and Extensions package. That's good news and till this point, I understand your situation.

But your next description about 200 requests/minute is mystical for me. The streaming connection doesn't have any rate limits and I don't understand why you speak about it at all. The rate limit is applied only for HTTP (REST) calls not to streaming (WS) data. So your code should just work as expected - on each trade you should receive an update and it will trigger the `async foreach` iteration in turn.

Of course, if your `SetPrice` do any HTTP calls these calls will be affected by rate limit rules but I'm not sure why you need any HTTP calls inside this method. Please, clarify why do you care about rate limits if we discuss the streaming conneciton.

**Comment by Ilya171** [comment]
About SetPrice:
` float v;
     void SetPrice(ITrade trade)
     {
         v = (float)trade.Price;          
     }

    public float VL()
    {
        return v;
    }`
    i use **setPrice** to initialize **v** and call **v** in another script:
    ` if(GetComponent<PriceScr>().VL()!=0 )
        { 
            if(i==0)NiceValue = GetComponent<PriceScr>().VL();
            i++;
            Value = GetComponent<PriceScr>().VL();           
        }`
        Value i use for calculate the new position of the object:
        ` if (niceValue == 0 || Value ==0) return;      // s.155 и n.156  1%=1.55  156-155/1.55=n/-10
            procent = niceValue * 1f / 100;             
            newPos.x = ((Value - NiceValue) * _minPos / procent);`
            
            
Description of my game:
I have objects that move depending on the stock price: if the price goes up, then the object goes to me, if the price goes down, it goes away from me

There are 5 such objects
The script is the same for everyone.
Case one:
I used a free account
Only 3 properties received a price
As if there was not enough signal for the other 2 objects
Second case:
I used an account for 99$/month
5 objects started moving (as if there were enough requests for everyone), BUT this is on a computer! only 3 objects worked on the phone (received the price)

**Comment by OlegRa** [comment]
I'll repeat one more time - there is no rate limit for streaming data. You can read more about the difference between subscription plans in the [documentation](https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/realtime/#subscription-plans).

In the .NET SDK if you want to connect free data (even if you have a paid subscription) you have to use the `Environments.Paper` object for constructing the `IAlpacaDataStreamingClient` instance. And if you want to connect to the full data stream you should use `Environment.Live` object instead. I know it's not obvious and maybe not easy to use but I'm unable to change it without breaking the backward compatibility so you have to keep it in mind.

I don't know the exact reason for your problem but I suggest you log all incoming messages, all `OnError` and `OnWarning` events generated by the streaming client, and analyze the difference between the computer and mobile runs.

**Comment by OlegRa** [comment]
@Ilya171 I close this issue due to the long inactivity period. If you still have problems/questions, feel free to re-open it and provide more information. Minimal code samples or steps to reproduce will be very helpful.
