### ISSUE TITLE
[QUESTION]: Have the symbols changed for crypto streaming endpoints 

### ISSUE THREAD

**Issue by markns** [alpacahq/alpaca-trade-api-csharp#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I see the documentation about the symbol change from v1beta1 to v1beta2:

> The symbol format has been changed. E.g. BTCUSD is changed to BTC/USD.

For historical queries this is working as expected:
```
{Symbol,TimeUtc,Open,High,Low,Close,Volume,Vwap,TradeCount},
{BTC/USD,19/09/2022 05:01:00,18812,18812...
```

However, I only receive data from the streaming client with the non-slashed symbol eg. BTCUSD:

```
{"i":413958052,"x":"CBSE","z":"","p":18430.91,"s":0.00104478,"c":[],"tks":"S","T":"t","S":"BTCUSD","t":"2022-09-19T09:05:09.257973Z"}
{"i":413958054,"x":"CBSE","z":"","p":18431.86,"s":0.00233386,"c":[],"tks":"S","T":"t","S":"BTCUSD","t":"2022-09-19T09:05:09.257973Z"}
{"i":413958053,"x":"CBSE","z":"","p":18431.84,"s":0.01727787,"c":[],"tks":"S","T":"t","S":"BTCUSD","t":"2022-09-19T09:05:09.257973Z"}
{"i":413958059,"x":"CBSE","z":"","p":18432.82,"s":0.001,"c":[],"tks":"S","T":"t","S":"BTCUSD","t":"2022-09-19T09:05:09.416291Z"}
```

Is this as expected? It doesn't seem to correspond with the examples in [the alpaca documentation](https://alpaca.markets/docs/api-references/market-data-api/crypto-pricing-data/realtime/#subscribe)

thanks

### Anything else?

Alpaca.Markets v6.1.3

```csharp
var alpacaCryptoStreamingClient = Environments.Live.GetAlpacaCryptoStreamingClient(new SecretKey(ApiKey, ApiSecret));
await alpacaCryptoStreamingClient.ConnectAndAuthenticateAsync();
var subscription = alpacaCryptoStreamingClient.GetTradeSubscription("BTCUSD");
subscription.Received += Console.WriteLine;
await alpacaCryptoStreamingClient.SubscribeAsync(subscription);
```

**Comment by OlegRa** [comment]
@markns I've briefly checked the code and my notes about migration from `v1beta1` to `v1beta2` endpoints. It looks like streaming for `v1beta2` was not ready at the moment of the .NET SDK release, so SDK still uses the v1beta1 endpoint for streaming. I will change it and publish updated versions of SDK later this week.

In the meantime, you can apply the following workaround:

```cs
var configuration = new AlpacaCryptoStreamingClientConfiguration()
{
    SecurityId = new SecretKey(ApiKey, ApiSecret),
    ApiEndpoint = new("wss://stream.data.alpaca.markets/v1beta2/crypto")
};
var alpacaCryptoStreamingClient = configuration.GetClient();
```

But I've never tested existing code against this endpoint so if you want to use it for real trading I think it would be better for you to wait for the official .NET SDK release.

**Comment by markns** [comment]
thanks for the prompt answer @OlegRa! I'm just testing a few things right now, so I'll apply the workaround 👍

**Comment by OlegRa** [comment]
@markns Please, just write me a short update later about your experience with the new endpoint. It will save me time for release testing. I'm a little bit overloaded with other work right now.

**Comment by markns** [comment]
Hmm, I'm afraid I'm not getting any data for either `BTC/USD` or `BTCUSD` with the following code:

```csharp
            const string symbol = "BTC/USD"; // BTCUSD
            var configuration = new AlpacaCryptoStreamingClientConfiguration()
            {
                SecurityId = new SecretKey(ApiKey, ApiSecret),
                ApiEndpoint = new Uri("wss://stream.data.alpaca.markets/v1beta2/crypto")
            };
            var alpacaCryptoStreamingClient = configuration.GetClient();
            await alpacaCryptoStreamingClient.ConnectAndAuthenticateAsync();
            var subscription = alpacaCryptoStreamingClient.GetTradeSubscription(symbol);
            subscription.Received += Console.WriteLine;
            await alpacaCryptoStreamingClient.SubscribeAsync(subscription);
```

**Comment by OlegRa** [comment]
OK. I will take a look at this problem ASAP.

**Comment by OlegRa** [comment]
@markns I've found the root cause. Unfortunately, you are unable to work around it on your side. I'll publish the updated NuGet packages late evening today or early morning tomorrow (European time) after more testing. The root cause of "missing" trades after replacing the URL is serialization format changing. In previous `v1beta1` version of stream the `x` (exchange) field is mandatory for trades/quotes/order books but in the new `v1beta2` it just does not exists.

I will publish the version with hotfix and in the next release I'll mark these properties as obsolete if needed.

**Comment by OlegRa** [comment]
@markns Please, test version [6.1.4](../releases/tag/sdk-6.1.4) - it should work better with naming and streaming.

**Comment by markns** [comment]
Working perfectly so far @OlegRa !

```csharp
        const string symbol = "BTC/USD";
        var alpacaCryptoStreamingClient = Environments.Live.GetAlpacaCryptoStreamingClient(new SecretKey(ApiKey, ApiSecret));
        await alpacaCryptoStreamingClient.ConnectAndAuthenticateAsync();
        var cancellationTokenSource = new CancellationTokenSource();
        cancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(15));
        await using var subscription = await alpacaCryptoStreamingClient.SubscribeTradeAsync(symbol);
        await foreach (var trade in subscription
                           .AsAsyncEnumerable(cancellationTokenSource.Token)
                           .ConfigureAwait(false))
            Console.WriteLine($"Trade received for the {trade.Symbol} contract");
```

```
Trade received for the BTC/USD contract
Trade received for the BTC/USD contract
Trade received for the BTC/USD contract
Trade received for the BTC/USD contract
Trade received for the BTC/USD contract
Trade received for the BTC/USD contract
```

I'll be testing more today, and will let you know if I run into any other issues. 👍
