### ISSUE TITLE
[FEATURE]: Position - Quantity Available

### ISSUE THREAD

**Issue by Stalib** [alpacahq/alpaca-trade-api-csharp#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The Alpaca Position Entity contains a qty_available property, but this does not seem to be exposed in the code. Could it be added, please?

### Describe the solution you'd like

Add the qty_available to the IPosition interface.

**Comment by OlegRa** [comment]
@Stalib Please, test it and close if the issue is resolved. The related changes are available in versions [5.3.10](../releases/tag/sdk-5.3.10) and [6.1.5](../releases/tag/sdk-6.1.5) of SDK.

**Comment by Stalib** [comment]
Tested with 6.1.5 and working as expected. Thank you.
