### ISSUE TITLE
Fix AppVeyor build issues

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#57]
For better diagnosis build result we have to do next changes on Appveyor build:

- [x]  Build `Release` configuration instead of default `Debug` configuration (add `-c Release` flag into `dotnet build` command).
- [x]  Keep NuGet packages at least for 3 days even if we do not publish them on public NuGet server (for fast checks before official releases).
- [x]  Add product release on GitHub after successful NuGet `push` command completion (not sure it's possible but would be very helpful).

 See issue #55 for more details about build result problem.

**Comment by OlegRa** [comment]
@ttt733 See my comments below:

- For second task (keep artifacts somehow) see [this](https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy) help topic. But I think if we will implement 3rd task and will add .nupkg file as release artifact it would be good enough.
- For third task you can try to reuse [this](https://www.appveyor.com/docs/deployment/github/) approach. Ideally we need this build step only in case of 'master' branch build. Version number can be re-used from Appveyor build - it's not a problem to update it after verifying package content.

**Comment by OlegRa** [comment]
@ttt733 I've tried to use automated build several times but it never publishes NuGet packages and never creates releases on GitHub. What I'm doing wrong? Please, provide step-by-step instruction on WiKi for proper release process using Appveyor build.

**Comment by OlegRa** [comment]
@ttt733 @umitanuki 
 I've managed to solve all build issues and automatically publish both NuGet package and GitHub release on my own fork for this repo. Release process will be really simple - build and publish steps will work only on tag pushing.
 I'll create PR for these changes soon and after merging it I will create new Appveyor build for this repo.

**Comment by umitanuki** [comment]
Awesome, thanks! And sorry for not being responsive. We have had a lot going on in our backend.

**Comment by OlegRa** [comment]
@umitanuki I've send information about adopting new build approach (re-generating secure tokens) to @ttt733 in email. As soon as he will fix tokens we can try to make release using new approach. I've created small Wiki [page](Prepare new release) about required steps.
