### ISSUE TITLE
[FEATURE]: Add order direction (short or long) to Order Interface

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I had a strange bug that I noticed today where I had a stock that I had a short position that I closed and then opened a long position shortly after and both orders used the same quantities. Since the order interface doesn't show negative quantity to show short positions like the positions interface does then on my end, it looks like I have two sell orders and one buy order with no way to track if the order was short or long. Can we either change the quantity to include negative values or include the order direction to help with issues like this?

**Comment by OlegRa** [comment]
Maybe I miss something but I've never heard about short and long orders. What does it mean? For me, only positions can be short or long. Orders can be bought (buy order) or sold (sell order). If you have a long position 10 and just sold 1 lot how you will name this order - short or long?

If you want to track any additional information related to the order like if it opened/closed position or just adjust its value you have to maintain a mapping between this metadata and the order id (or client order id) on your side. In this case, you can track any information related to this order and assign to it any "types" that you want.

**Comment by ooples** [comment]
@OlegRa yes you are correct about orders in general about how they are either buy or sell. You are also correct that technically you could also keep track of the order ids but a far easier method for users would be to include the order direction enum to the order interface so users have information showing whether the order is long or short. Quantity can stay the same but I place orders for around 20 accounts thousands of times and this solve many issues on my end and I'm sure would help many other users.

**Comment by OlegRa** [comment]
Maybe this additional enum is useful but I'm unable to just add it without support on the server side. This additional information should be available between sessions and it's not possible to achieve with the client-side changes only.

You can report your API change proposal on this [GitHub issues-only repo](https://github.com/alpacahq/Alpaca-API/issues) or on the [Alpaca forum](https://forum.alpaca.markets/). As soon as this proposal will be implemented on the server side I add it to .NET client SDK as well.

**Comment by ooples** [comment]
@OlegRa That is a great idea and I will go ahead and submit proposals in both areas just to be sure. I will let you know if I hear anything from them.

**Comment by ooples** [comment]
@OlegRa I did both methods and got no response from Alpaca from either end. Do you have a contact or someone I can contact directly or do you have any other suggestions for how to pursue this change?

**Comment by OlegRa** [comment]
@ooples I've sent the link for this issue to my contact in Alpaca. But he isn't responsible for these changes and just forwarded it to a more appropriate person. I'll close this issue for now - I can't do anything in SDK. You can also try to hit the Alpaca support directly via email if you really want to push it up to the CEO/CTO.
