### ISSUE TITLE
[FEATURE]: Alpaca Trading Client only works when using Paper keys

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I posted this recently on the slack channels but I'm having an issue with getting the valid assets which uses the alpaca trading client. I have a paid API unlimited subscription that I'm able to use with the live API keys to get historical data using the alpaca data client. I don't know if this was an intended design choice but I'm unable to use these same valid live API keys with the alpaca trading client to get the valid assets. I'm getting the unauthorized request error but I'm able to get these valid assets just fine if I use the code below:

```cs
public static async Task<List<IAsset>> GetValidAssets()
    {
        var assetsList = new List<IAsset>();
        var key = GetAlpacaApiKey(Environments.Paper);
        using var client = Environments.Paper.GetAlpacaTradingClient(key);
        assetsList = new List<IAsset>((await client.ListAssetsAsync(new AssetsRequest() { AssetStatus = AssetStatus.Active }).ConfigureAwait(false)).Shuffle());
 

        return assetsList;
    }
```

### Describe the solution you'd like

To add functionality like the other alpaca apis which allow you to use live or paper API keys for the alpaca trading client.

### Anything else?

I don't know if this is technically a bug or if it was intended behavior so I'm putting this in as a feature request.

**Comment by OlegRa** [comment]
The "paper" and "live" environments in SDK are just sets of the base URLs for accessing underlying REST/WS services. Alpaca data services use the same base URL for both "paper" and "live" environments and provide different data based on your API key. The trading APIs (both REST and WS) use different URLs for "paper" and "live" environments so you have to use the proper API key/secret for authorization.

Your data subscription affects both "paper" and "live" environments and it means that you can use both "paper" and "live" API keys for getting the same data. But for trading, you have to match the environment (URL) and key for proper authorization.

**Comment by ooples** [comment]
@OlegRa I get what you are seeing but for this particular account, I don't have a paper environment created and I only have the live environment.

**Comment by ooples** [comment]
I'm closing this issue because after contacting customer support again, it seems clear that it is a server side issue
