### ISSUE TITLE
What crypto exchanges are supported by Alpaca ?

### ISSUE THREAD

**Issue by Kinzowa** [alpacahq/alpaca-trade-api-csharp#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Hello,

I would like to know what crypto exchanges are supported by Alpaca. Do you also support crypto derivative markets like perp ? or do you aggregate liquidity from multiple exchange ?

Couldn't found answers to these questions in Alpaca website..

Regards

**Comment by OlegRa** [comment]
@Kinzowa The Alpaca crypto offering is still in beta status and everything is changing rapidly. AFAIR, initially, API provides a bridge for ErisX, FTX, and Coinbase exchanges but it looks like right now they handle it differently. I think it would be better to ask this question on the Alpaca forum or directly via email support.
