### ISSUE TITLE
GetBarSetAsync datetime parameters ignored

### ISSUE THREAD

**Issue by jameswhollister** [alpacahq/alpaca-trade-api-csharp#61]
Appears the way that datetime parameters are getting added aren't working on the latest api. One example is GetBarSetAsync

The Alpaca docs state that dates should be formatted as '2019-04-15T09:30:00-04:00'

Currently it's passed in another format and ends up being ignored by the api.

**Comment by OlegRa** [comment]
@ttt733 Could you please test it with your latest changes in PR #63 and if it solved, close this issue and publish updated version on NuGet?

**Comment by OlegRa** [comment]
@jameswhollister Sorry for delay, James. Are this problem still actual for you? Unfortunately, I'm unable to reproduce it on my side. Code like [this](https://github.com/alpacahq/alpaca-trade-api-csharp/blob/3af5d02b9a6338b1f1a91cf888932c40a7d1c542/Alpaca.Markets.Tests/RestClientGeneralTest.cs#L137) just works fine for me. If you will provide sample code which demonstrates issue I will try to figure out rott cause.

**Comment by OlegRa** [comment]
@jameswhollister I close it now. If you still have this problem, please, provide code sample which demonstrates error and re-open this issue.
