### ISSUE TITLE
[BUG]: Alpaca.Markets.AccountActivityType.Fee is Missing

### ISSUE THREAD

**Issue by pratttrader** [alpacahq/alpaca-trade-api-csharp#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using v4.0.30319.  The FEE type is missing from the AcccountActivityType enum.   Maybe included in a newer version.  Need this to complete taxes so if there is a hard value that I can use, let me know.  I tried RefTafFee, PassThruCharge...with nothing returned.   Customer Support told me that regulatory fees should be returned using the FEE Activity Type.  

### Environment

```markdown
- SDK Version: v4.0.30319
- OS (version, bitness): Win10 64
- .NET SDK (version): 4.7.2
- target process .NET version/bitness:
```

**Comment by OlegRa** [comment]
@pratttrader I'll update the `AccountActivityType` enum according to the [latest Alpaca documentation](https://alpaca.markets/docs/api-references/trading-api/account-activities/#activity-types) soon. But I'm unsure which version of the Alpaca .NET SDK you use. I can fix this problem in 5.4.x (LTS) and 6.2.x (current) versions but not in 4.0.x - this version does not supported anymore. Please review the [full list of available versions](https://www.nuget.org/packages/Alpaca.Markets/7.0.0-alpha3#versions-body-tab) on NuGet.

**Comment by OlegRa** [comment]
@pratttrader I've checked the current `AccountAcitvityType` enum values and see only one item that was missed - crypto fee mapping. The normal fee (`FEE` value in requests/responses) should be mapped to the `AccountActivityType.RefTafFee` (not the best name but I'm unable to change it immediately without breaking code for many users) member.

Could you please share a small code snippet that demonstrates how you use the `AccountActivitiesRequest` class and `ListAccountActivitiesAsync` method in your code? I expect something like this:

```cs
var fees = await client.ListAccountActivitiesAsync(new AccountActivitiesRequest(AccountActivityType.RefTafFee));
```

**Comment by pratttrader** [comment]
Ok, thanks, I updated to v6.1.11 and RefTafFee does work.  I'm good with that.
