### ISSUE TITLE
[BUG]: order_id is missing in IAccountActivity interface

### ISSUE THREAD

**Issue by Shidzy2** [alpacahq/alpaca-trade-api-csharp#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- SDK Version: 
- OS (version, bitness): 
- .NET SDK (version):
- target process .NET version/bitness:
```

**Comment by OlegRa** [comment]
@Shidzy2, you can test the fix in version [6.2.0](../releases/tag/sdk-6.2.0) available on NuGet.
