### ISSUE TITLE
Errors on Console when Building

### ISSUE THREAD

**Issue by Wingspear** [alpacahq/alpaca-trade-api-csharp#62]
<img width="922" alt="screenshot" src="https://user-images.githubusercontent.com/27274272/58494398-da712080-8129-11e9-9854-8144646713ee.PNG">

**Comment by OlegRa** [comment]
@Wingspear Please, attach full build log from Output window and specify which version of Visual Studio do you use.

**Comment by OlegRa** [comment]
There is no updates related to this issue for more than 2 weeks. I'll close it now. If you (@Wingspear) still experience this problem, reopen it and provide required information.
