### ISSUE TITLE
Bid and Ask for a symbol

### ISSUE THREAD

**Issue by Slacquer** [alpacahq/alpaca-trade-api-csharp#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I see several python examples on the net for figuring out a symbols current bid and ask, but I do not see a GetQuote or similar method for this.  I'm I just looking in the wrong place?

SORRY helps if i was using the DataClient....

**Comment by OlegRa** [comment]
@Slacquer I thought it was obvious, but looks like it doesn't:

- [IAlpacaDataClient.GetLatestQuoteAsync](IAlpacaDataClient) - returns the latest quote for the single instrument
- [IAlpacaDataClientListLatestQuotesAsync](IAlpacaDataClient) - returns the latest quotes for the list of instruments

You can also try to use similar methods for snapshots - each snapshot contains all the latest data (quote, trade, and bar).
