### ISSUE TITLE
Add wildcard support for trades & quotes

### ISSUE THREAD

**Issue by IsaackRasmussen** [alpacahq/alpaca-trade-api-csharp#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I know this has been up before, including a similar interface from myself.

I looked into the code and it looks like it only supports wildcards for Minute Bars, which I can confirm works. Subscribing to wildcard trades and quotes results in no events.
But it works fine with my subscription through a raw websocket.

Is it by intention that its not supported by the library?

And thanks for the great work

**Comment by OlegRa** [comment]
@IsaackRasmussen Thanks a lot for this issue. Previously, Alpaca streaming API supported wildcards only for minute bars. But AFAIU, this limitation was recently updated for the SIP (paid) connection. I'll add support for these changes into SDK but for testing, I need your help. Next week I'll publish the alpha version of SDK and provide you with the version number for testing this feature not only from my side.

**Comment by IsaackRasmussen** [comment]
That's also my understanding and I only discovered it by accident.

Let me know when its ready to test. Thanks

**Comment by OlegRa** [comment]
@IsaackRasmussen You can test discussed changes in pre-release version [7.0.0-alpha4](../releases/tag/sdk-7.0.0-alpha4) available on NuGet. I'm working on backporting these changes into 6.x releases as well.

**Comment by IsaackRasmussen** [comment]
I guess I was too slow :) Thanks @OlegRa

**Comment by OlegRa** [comment]
@IsaackRasmussen The last commit is just backporting streaming changes from 7.0.x into 6.2.x and doesn't relate to bid/ask exchange codes serialization in streaming.
