### ISSUE TITLE
[BUG]: RealTime Stock Stream Not Working In 6.2.1

### ISSUE THREAD

**Issue by ARStudios** [alpacahq/alpaca-trade-api-csharp#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to the 6.2.1 NuGet package the real-time stream for stock prices stopped working. No result or error. Downgrading to the earlier version resolved the issue. 

### Environment

- SDK Version: 6.2.1

**Comment by OlegRa** [comment]
@ARStudios, unfortunately, I'm unable to reproduce this problem on my side - all types of stock subscriptions (quotes, trades, bars, etc.) work fine in the 6.2.1 version of SDK. Please, provide more information about this problem. Maybe you try to get data outside of trading hours?

**Comment by OlegRa** [comment]
@ARStudios I'll close this issue as inactive soon. If you still have this problem, please, provide more information and answer my questions.
