### ISSUE TITLE
[BUG]: solution not compiling

### ISSUE THREAD

**Issue by koolinoor** [alpacahq/alpaca-trade-api-csharp#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

downloaded source
opened it with VS2019 
changed prj: 
    <TargetFrameworks>net5</TargetFrameworks>
    <RestoreLockedMode>false</RestoreLockedMode>

it does load the packages; 
but i get about 442 errors

### Expected Behavior

compile

### Environment

```markdown
- OS (version, bitness): win10
- .NET SDK (version):net5
- target process .NET version/bitness:net5
```

**Comment by OlegRa** [comment]
@koolinoor - the README file states explicitly that you need .NET 7.0 (and above) SDK for building code from this repository. Visual Studio 2019 doesn't support this version of .NET SDK so you have to upgrade to Visual Studio 2022. The latest SDK provides the latest C# lanugage version as well as better error diagnostics in a compiler. You can use NuGet packages directly from .NET 5.0 (or even .NET 3.1) applications - just add appropriate package references to your projects.
