### ISSUE TITLE
Stream Aggregates Incorrect End Time 

### ISSUE THREAD

**Issue by sghitch** [alpacahq/alpaca-trade-api-csharp#65]
Line 58 of JsonStreamAgg:
`EndTime = DateTime.SpecifyKind(
                DateTimeOffset.FromUnixTimeMilliseconds(StartTimeOffset)
                    .DateTime, DateTimeKind.Utc);`

Should reference EndTimeOffset instead of StartTimeOffset. Happy to submit a PR for this

**Comment by OlegRa** [comment]
Hi @sghitch, it would be very helpful. I'll review and merge it ASAP. Please, make PR for `develop` branch.

**Comment by sghitch** [comment]
@OlegRa I've got it queued, but am getting a 403 error, I assume I need access?

**Comment by OlegRa** [comment]
@sghitch Sorry for delay, you have to fork this repo and create PR from your fork into this (upstream) repo.

**Comment by OlegRa** [comment]
@sghitch  Please test it using version [3.0.6](https://www.nuget.org/packages/Alpaca.Markets/3.0.6) and re-open if problem still exists.
