### ISSUE TITLE
[BUG]: Getting announcements leads to JsonSerializationException

### ISSUE THREAD

**Issue by KevinDeBeer** [alpacahq/alpaca-trade-api-csharp#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I call ListAnnouncementsAsync with:
- CorporateAction.Merger
- StartDate of 2023-08-01
- EndDate of 2023-08-03

The following exception is thrown:
Required property 'record_date' expects a value but got null.

### Expected Behavior

IAnnouncement should be able to have null as a value for RecordDate.
RecordDate is null quite often, as can be seen on:
https://docs.alpaca.markets/reference/get-v2-corporate_actions-announcements

With the following parameters:
ca_types: Merger
since: 2023-08-01
until: 2023-08-03

### Steps To Reproduce

```markdown
Call GetAnnouncementAsync or ListAnnouncementsAsync with above mentioned values.
```

### Environment

```markdown
- SDK Version: Latest
- OS (version, bitness): Windows 11 Pro 64 bit.
- .NET SDK (version): 6.0.x, 7.0.x
- target process .NET version/bitness: .NET 7.0 64 bit.
```

**Comment by OlegRa** [comment]
@KevinDeBeer, please, test SDK package version [6.2.2](https://www.nuget.org/packages/Alpaca.Markets/6.2.2) available on NuGet.

**Comment by KevinDeBeer** [comment]
@OlegRa, works as expected. Thanks for the release!
