### ISSUE TITLE
The new Aggregate function date parameters not inclusive

### ISSUE THREAD

**Issue by Ronmenator** [alpacahq/alpaca-trade-api-csharp#67]
The new Aggregate function to retrieve Candle data from the Polygon server is not returning the current candle, it only always returns up to the TODATE exclusive. See, https://api.polygon.io/v2/aggs/ticker/ENT/range/1/day/2019-06-10/2019-06-19?unadjusted=false&apiKey= use your own API key. There is no way to retrieve today's 1day Candle. If you change the parameters to 1 hour, you can get today's data, but now you are pulling way more data from the server than what is required to calculate a single days candle.

**Comment by OlegRa** [comment]
Trevor (@ttt733), could you please check this issue? AFAIU API returns only closed bars so today bar will be available only after session close, right?

**Comment by OlegRa** [comment]
@Ronmenator I'll close it for now. This problem is not specific for .NET SDK - ask this question to Alpaca support directly.
