### ISSUE TITLE
Create CI/CD build for NuGet packages

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#7]
Automate build process - test, pack, sign (optional), publish on NuGet and GitHub

**Comment by umitanuki** [comment]
We can set up CircleCI under alpacahq

**Comment by ttt733** [comment]
@OlegRa - can the testing, packing, and publishing be done in a Linux environment? I only had luck building the project on a Windows environment, which CircleCI does not seem to support. Have been looking into other solutions, but figured I would ask.

**Comment by OlegRa** [comment]
@OlegRa - you can build only .NET Core targets on Linux environment. For building .NET Framework binaries you have to use Windows environment. Try Azure DevOps (former VS Online) - AFAIK free services provides ability to build any VS-based project using latest versions of Visual Studio and SDKs.

**Comment by ttt733** [comment]
Right now we're going to try going with Appveyor - free for open source projects and supports NuGet builds, tests etc. on Windows environments.
