### ISSUE TITLE
Change DateTimeHelper implementation/usage

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#71]
Change DateTimeHelper class implementation and move all conditional logic into this class for more simple support and QuantConnect merging.

**Comment by sghitch** [comment]
Quotes started arriving with millisecond timestamps again for me today. Did we ever get an answer from Polygon about the expected behavior?

**Comment by umitanuki** [comment]
Yes millisecond is what it should be.

**Comment by OlegRa** [comment]
@umitanuki So, we have to roll-back last fix related to nanoseconds handling in such messages?

**Comment by umitanuki** [comment]
Yes

**Comment by OlegRa** [comment]
@umitanuki @sghitch I've just published release 3.0.7 on NuGet with fix for nano/milliseconds handling in stream quotes.

**Comment by OlegRa** [comment]
@sghitch I'll close issue now. If you still experience same problems with latest versions of SDK - re-open it and provide more information (environment/contract/.NET version).
