### ISSUE TITLE
Inconsistent crypto symbol naming

### ISSUE THREAD

**Issue by Chacoon3** [alpacahq/alpaca-trade-api-csharp#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The format of crypto symbols in the `IPosition` object, as returned by the function `ListPositionsAsync`, is inconsistent with the format of crypto symbols used elsewhere.  In other functions, the crypto symbols are in the format of `XXX/USD` but in the `IPosition` object the crypto symbols are in the format of `XXXUSD` without a slash. 

### Expected Behavior

The crypto symbols in the IPosition object should be also in the format of `XXX/USD`, thus being consistent with other use cases, otherwise, it can lead to critical bugs in client programs which are using the current C# SDK.

### Steps To Reproduce

In an account with open crypto positions, call the function `ListPositionsAsync()` on `IAlpacaTradingClient`, then look up the property `Symbol` of the `IPosition` objects.

### Environment

- SDK Version: 7.0
- OS (version, bitness): Win11
- .NET SDK (version): 8.0

### Anything else?

Inconsistency also exists in the `GetPositionAsync()`. I think this SDK should only have one format to represent crypto symbols, but currently, there are at least two.

**Comment by OlegRa** [comment]
@Chacoon3 The SDK just converts JSON data from underlying Alpaca REST/WS API messages into .NET objects. The `XXXUSD` crypto naming format is an old one used by the first beta version of Alpaca's crypto API. If you opened this position a long time ago it can still handle the old symbol name (it's just a guess) or maybe SDK should use another version of REST endpoints for getting more consistent data. In any case I'll try to reproduce it on my side first.

**Comment by OlegRa** [comment]
@Chacoon3 I can confirm this strange behavior of the underlying REST API. The .NET SDK is just a wrapper around this underlying API so this problem should be reported/solved not here. You can report this issue on the Alpaca forum or using [this GitHub repo](https://github.com/alpacahq/Alpaca-API/issues) created specifically for API issues reporting.

**Comment by Chacoon3** [comment]
> @Chacoon3 I can confirm this strange behavior of the underlying REST API. The .NET SDK is just a wrapper around this underlying API so this problem should be reported/solved not here. You can report this issue on the Alpaca forum or using [this GitHub repo](https://github.com/alpacahq/Alpaca-API/issues) created specifically for API issues reporting.

Hi OlegRa,

Thank you for your help! I will report this issue to the REST API team.

Best,
