### ISSUE TITLE
[BUG]: ListAssetsAsync quit returning on paper or live.

### ISSUE THREAD

**Issue by homer14** [alpacahq/alpaca-trade-api-csharp#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following never returns from live or paper. This seems to have started today. I see the packets fly and a connection made and then an endless keepalive as it never finishes.

```cs
alpacaClient.ListAssetsAsync(new AssetsRequest { AssetStatus = AssetStatus.Active });
```

![image](https://github.com/alpacahq/alpaca-trade-api-csharp/assets/146207223/27d069f9-9707-4170-a6ec-7444bb750571)

### Expected Behavior

it returns the list of assets.

### Steps To Reproduce

```cs
IAlpacaTradingClient alpacaClient = global::Alpaca.Markets.Environments.Live.GetAlpacaTradingClient(new SecretKey(Common.ALPACA_KEY_ID, Common.ALPACA_SECRET_KEY));

IReadOnlyList<IAsset> activeAssets= await alpacaClient.ListAssetsAsync(new AssetsRequest { AssetStatus = AssetStatus.Active });
```

### Environment

- SDK Version: 7
- OS (version, bitness): Win 10 64bit
- .NET SDK (version): 7

### Anything else?

i like toitles

**Comment by OlegRa** [comment]
@homer14 , please test version [7.0.1](https://www.nuget.org/packages/Alpaca.Markets/7.0.1) available on NuGet - it should work better for this use case.

**Comment by homer14** [comment]
> @homer14 , please test version [7.0.1](https://www.nuget.org/packages/Alpaca.Markets/7.0.1) available on NuGet - it should work better for this use case.

fixed. ty.
