### ISSUE TITLE
[BUG]: ListAssetsAsync Error converting value "options_enabled" to type 'Alpaca.Markets.AssetAttributes'. 

### ISSUE THREAD

**Issue by homer14** [alpacahq/alpaca-trade-api-csharp#717]
### Is there an existing issue for this?

NOTE: This may be related to issues #714 and #716.

### Current Behavior

When I grabbed active assets a week or so ago, it seemed this error appeared 10 times or so. [EDIT] Now it appears too many times to count. 

```cs
Newtonsoft.Json.JsonSerializationException: 'Error converting value "options_enabled" to type 'Alpaca.Markets.AssetAttributes'. Path '[736].attributes[0]', line 1, position 237521.'
```

![image](https://github.com/alpacahq/alpaca-trade-api-csharp/assets/146207223/71806ae5-2020-4739-ac46-2f12aa755b15)

### Expected Behavior

no errors grabbing assets. 

### Steps To Reproduce

```cs
IAlpacaTradingClient alpacaClient = global::Alpaca.Markets.Environments.Live.GetAlpacaTradingClient(new SecretKey(Common.ALPACA_KEY_ID, Common.ALPACA_SECRET_KEY));

IReadOnlyList<IAsset> activeAssets = await alpacaClient.ListAssetsAsync(new AssetsRequest { AssetStatus = AssetStatus.Active });
```

### Environment

- SDK Version: 7
- OS (version, bitness): Win 10 64bit
- .NET SDK (version): 7

### Anything else?

i like toitles, go lions!

**Comment by OlegRa** [comment]
@homer14 , please test version [7.0.1](https://www.nuget.org/packages/Alpaca.Markets/7.0.1) available on NuGet - it should work better for this use case.

**Comment by homer14** [comment]
> @homer14 , please test version [7.0.1](https://www.nuget.org/packages/Alpaca.Markets/7.0.1) available on NuGet - it should work better for this use case.

Fixed. ty.
