### ISSUE TITLE
How do I submit a day limit order?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I am looking at the Alpaca.Markets.OrderSideExtensions class and its Limit(Alpaca.Markets.OrderSide, string, Alpaca.Markets.OrderQuantity, decimal) method in latest version which is 7.0.1 as shown below:

<img width="896" alt="image" src="https://github.com/alpacahq/alpaca-trade-api-csharp/assets/10700224/a9f17529-5a9c-4533-b44d-8b3bd1e520f6">

This method does not have a way to specify time in force. This feature is shown on Alpaca web site as shown below:

<img width="289" alt="image" src="https://github.com/alpacahq/alpaca-trade-api-csharp/assets/10700224/56eec431-8c5e-4976-8f27-e18b909ffd72">

Is this C# library issue or the Alpaca REST API issue?

**Comment by OlegRa** [comment]
According to .NET SDK [Wiki](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Order-Placement#fluent-interface-methods):

> The [Alpaca.Markets.OrderBase](https://olegra.github.io/Alpaca.Markets/api/Alpaca.Markets.OrderBase.html) class has some properties that initialized with default values. You can use property setters for changing these default values or extension methods provided by SDK. These extension methods are implemented as fluent interface methods and it allows you to pass fully configured order request into the PostOrderAsync method without creating the temporary object:
> 
> The [WithDuration](https://olegra.github.io/Alpaca.Markets/api/Alpaca.Markets.OrderBaseExtensions.html#Alpaca_Markets_OrderBaseExtensions_WithDuration__1___0_Alpaca_Markets_TimeInForce_) method sets the [Duration](https://olegra.github.io/Alpaca.Markets/api/Alpaca.Markets.OrderBase.html#Alpaca_Markets_OrderBase_Duration) property value.
> 

So you can create the order object in place like this:

```cs
await client.PostOrderAsync(LimitOrder.Buy("AAPL", 10, 1000M).WithDuration(TimeInForce.Day));
```

or just use the `Duration` property of the `OrderBase` type.

**Comment by rudeGit** [comment]
I see. Thanks for the reply.

**Comment by asulwer** [comment]
i am not reopening this issue.  this should be documented somewhere other than in an issue
