### ISSUE TITLE
[BUG]: Third partly Exception thrown.

### ISSUE THREAD

**Issue by kwcoffee1** [alpacahq/alpaca-trade-api-csharp#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run paper asset method:

```cs
var assets = await client.ListAssetsAsync(new AssetsRequest { AssetStatus = AssetStatus.Active });
```
I get a list of:

```cs
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
```

### Expected Behavior

I expect a list of assets to be returned.

### Steps To Reproduce

I ran the code method snippet in the UsageExamples project.

### Environment

- SDK Version: 7.0.1
- OS (version, bitness): Windows 11, 64-bit
- .NET SDK (version): .NET 8.0
- target process .NET version/bitness: .NET 8.0

**Comment by OlegRa** [comment]
@kwcoffee1 Have you checked it with the version [7.0.2](https://www.nuget.org/packages/Alpaca.Markets/7.0.2) available on NuGet from yesterday? It looks very similar to #728 and most probably it's a duplicate.

**Comment by OlegRa** [comment]
I close it after 3 weeks of inactivity. @kwcoffee1, if you are still experiencing this problem in the latest version of SDK, feel free to re-open this issue.
