### ISSUE TITLE
Format of after and until parameter of ListOrdersAsync

### ISSUE THREAD

**Issue by xutao650** [alpacahq/alpaca-trade-api-csharp#73]
Hi
Thank you for offerring this wonderfull api to us.
I am using "ListOrdersAsync" to fetch orders. But when I specify after and until parameter.
The service return an exception with error code "422".
Could you please help to figure it out?

**Comment by OlegRa** [comment]
@xutao650 Proposed fix is under review now (see PR #74 for details) but you can try it using pre-release version of Alpaca NuGet package available [here](https://www.nuget.org/packages/Alpaca.Markets/3.1.0-alpha).

**Comment by xutao650** [comment]
Hi
Thank you for such a quick response.
I am using the pre-release version now and the bug has been fixed.
Thank you again.
