### ISSUE TITLE
[BUG]: HistoricalAuctionReq will return no data at all if there is one date in the range without auctions

### ISSUE THREAD

**Issue by IvoTops** [alpacahq/alpaca-trade-api-csharp#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A HistoricalAuctionsRequest will throw an error if there is a single date without a close auction in the range. 
This makes the call unusable if you do not know exactly on which days there have been auctions and alpaca has the data.

The error comes from the json parsing;

```cs
Required property 'c' expects a value but got null. Path 'auctions[1893]', line 1, position 578089.
```

### Expected Behavior

A HistoricalAuctionsRequest will not include auction data for days where it is missing, but return all the other days where it has valid data

### Steps To Reproduce

Perform the request for AAPL from 1-1-2010 to 1-1-2030

```cs
var req = new HistoricalAuctionsRequest(ticker, start,stop);
await foreach (var ha in _alpacaDataAPI.GetHistoricalAuctionsAsAsyncEnumerable(req)) .....
```

### Environment

- SDK Version: 7.0.x
- OS (version, bitness): Windows 11
- .NET SDK (version): 8.x
- target process .NET version/bitness:8.02

**Comment by OlegRa** [comment]
Thank you @IvoTops for reporting this issue. The root cause is not in the returned data itself but in JSON deserialization.
Unfortunately, the new Alpaca documentation doesn't contain any information about JSON output's field types and optional/mandatory states (schema) so we have to learn this by try.
I'll mark this `c` field (and maybe other fields) as optional and will publish a new 7.0.4 release later today.

**Comment by OlegRa** [comment]
@IvoTops, please test the fix in version [7.0.4](https://www.nuget.org/packages/Alpaca.Markets/7.0.4) available on NuGet and close this issue if the problem is solved.

**Comment by IvoTops** [comment]
@OlegRa I do now get a reply with 7.0.4, but it is always limited to 1000 items. And I cannot influence that pagination limit from the C# request?

**Comment by OlegRa** [comment]
@IvoTops I've tried the next code snippet:

```cs
var req = new HistoricalAuctionsRequest(
    "AAPL", new DateTime(2010, 1, 1), new DateTime(2030, 1,1))
    .WithPageSize(10);
await foreach (var ha in client.GetHistoricalAuctionsAsAsyncEnumerable(req))
{
    Console.WriteLine(ha);
}
```

And it returns the same data regardless of the page size that I use (10 or 100). The `ListHistoricalAuctionsAsync` method returns only one page and you have to implement paging manually but in the Extensions package, you can find helper methods pagination in different styles.

**Comment by IvoTops** [comment]
@OlegRa That is counter-intuitive, but I will see if I can get it to work so I get all of the auctions

**Comment by IvoTops** [comment]
No more time to put into this, sorry. I will close the issue as we now do get the data even if it is limited to the first 1000 without extra work.
