### ISSUE TITLE
[BUG]: Can't submit stop loss order for option trading

### ISSUE THREAD

**Issue by hoangvu07s** [alpacahq/alpaca-trade-api-csharp#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Alpaca.Markets version 7.0.6 and When I submit a stop-loss order with option symbol. I am receiving an error message: **"code":42210000,“message”:“invalid options order_type”"**

### Expected Behavior

It should submit a stop loss order with the option symbol successfully. Note that this bug did not occur before.

### Steps To Reproduce

```markdown
var client = Environments.Paper
  .GetAlpacaTradingClient(new SecretKey(KEY_ID, SECRET_KEY));

var stopLossOrder = new NewOrderRequest( "AMZN240517P00185000", 1, OrderSide.Sell, OrderType.Stop, TimeInForce.Day )
{
  OrderClass = OrderClass.Simple,
  StopPrice = 10.25m
} ;

var order =  await client.PostOrderAsync( stopLossOrder) ;
```

### Environment

```markdown
- SDK Version: 7.0.6
- OS (version, bitness): windows 11
- .NET SDK (version): 4.8
- target process .NET version/bitness: 4.8
```

**Comment by OlegRa** [comment]
@hoangvu07s This error was reported by Alpaca REST API, not by SDK. Most probably, this is an API limitation related to options support. For instance, cryptocurrency contracts [support](https://docs.alpaca.markets/docs/crypto-orders) only market, limit, and stop limit orders. There is no exact list of supported order types for options but according to [this page](https://docs.alpaca.markets/docs/options-orders), only market and limit are valid in the current API.

I'll try figuring this out with the Alpaca team and update you later.

**Comment by OlegRa** [comment]
Confirmed by the Alpaca team - these order types were temporarily disabled on the paper environment:

> Our production venues are not supporting stop and stop-limit orders, so we stopped the order types support in the paper environment as well. 
Maybe in the future, we will support those order types
