### ISSUE TITLE
[FEATURE]: Adding Option Market Data Streaming

### ISSUE THREAD

**Issue by Chacoon3** [alpacahq/alpaca-trade-api-csharp#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I have viewed the project source codes and it appears the SDK currently does not support the streaming of option market data. I hope option data streaming could be offered in near future as it can be quite helpful to option traders.

### Describe the solution you'd like

1. Following your existing design pattern, I suggest to develop a new class for option streaming client that implements the IStreamingDataClient interface.

2. Option snapshot is very important to option traders. It would be very helpful if the option snapshot can also be streamed.

**Comment by OlegRa** [comment]
I close it as a duplicate for #752
