### ISSUE TITLE
How to compile and build the Alpaca.Market project

### ISSUE THREAD

**Issue by kwcoffee1** [alpacahq/alpaca-trade-api-csharp#761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Hello,
I search the WIKI and FAX files... but did not find an asker.

I'm having problems compiling project Alpaca.Market out-of-the-box. Thefollowing is a sample of the error messages I'm getting. I deleted the package.lock.json before compile, but more is required. Can you please give me a step-by-step instructions.

Symbol 'static Alpaca.Markets.BarTimeFrame.operator !=(Alpaca.Markets.BarTimeFrame left, Alpaca.Markets.BarTimeFrame right) -> bool' is not part of the declared public API

Symbol '~override Alpaca.Markets.OpenClose.ToString() -> string' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

Symbol 'static Alpaca.Markets.OpenClose.operator !=(Alpaca.Markets.OpenClose left, Alpaca.Markets.OpenClose right) -> bool' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

**Comment by OlegRa** [comment]
@kwcoffee1 As you can see from the GitHub workflow, you only need a .NET 8 SDK installed on your computer to compile code from this repository. I've checked it on a lightweight Ubuntu container, and it works fine. You probably try to build code using an old .NET SDK that doesn't support the latest C# language features like record structures.

**Comment by kwcoffee1** [comment]
Thanks very much, your suggestion fixed the majority of the errors. Now I'm getting 50 are so errors as followings:
Thanks,
King

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	RS0016	Symbol '~override Alpaca.Markets.TrailOffset.ToString() -> string' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)	Alpaca.Markets (net8.0)	C:\Users\kcoff\Desktop\alpaca-trade-api-csharp-develop\Alpaca.Markets\Orders\TrailOffset.cs	6

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	RS0016	Symbol '~override Alpaca.Markets.ReceiveResult.ToString() -> string' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)	Alpaca.Markets (net8.0)	C:\Users\kcoff\Desktop\alpaca-trade-api-csharp-develop\Alpaca.Markets\WebSocket\ReceiveResult.cs	12		
	
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	RS0016	Symbol '~override Alpaca.Markets.PositionQuantity.ToString() -> string' is not part of the declared public API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)	Alpaca.Markets (net8.0)	C:\Users\kcoff\Desktop\alpaca-trade-api-csharp-develop\Alpaca.Markets\Helpers\PositionQuantity.cs	6

**Comment by OlegRa** [comment]
@kwcoffee1 I've tried to reproduce your issue on the different platforms (again), but everything works fine for me. Please specify which version of the .NET SDK you use and what your development OS is. Also, can you confirm that you use the latest `develop` branch without updating anything, including dependent NuGet packages?

**Comment by kwcoffee1** [comment]
Hi,
I downloaded the latest version of Alpaca-Market API
My .Net-SDK is NET8.0
My OS is Windows 11
[cid:27d27a16-b634-4c2f-86d7-8b9acaed0fea]

________________________________

**Comment by kwcoffee1** [comment]
I kept the default project build types (formerly I change the Alpaca.Market and Alpaca.Market.Extension to .Net8.0) and changed WarningAsErrorTag to false. All the compiler errors when away.

Thank you for your time and effort.
