### ISSUE TITLE
[BUG]: VWAP and Volume data is incorrect

### ISSUE THREAD

**Issue by ushahx** [alpacahq/alpaca-trade-api-csharp#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The VWAP values are not accurate  for any stocks. I see a difference of $0.50 to almost $1.00 in many of them. I am comparing values I see in Think of Swim (ToS) platform with Schwab. Upon further investigation the volumes for each 1min, 5min or other bars are so different that the VWAP will never match. For e.g. AAPL on 11/06/2024
12:35pm PST Alpaca volume - 337,149, ToS-226,913 - Alpaca VWAP-223.81 , Tos VWAP -224.24
12:40pm PST Alpaca volume - 457,523, ToS-319,192 - Alpaca VWAP- 223.60, Tos VWAP - 224.23
12:45pm PST Alpaca volume - 516,647, ToS-368,013 - Alpaca VWAP- 223.49, Tos VWAP - 224.22
12:50pm PST Alpaca volume - 958,917, ToS-706,643 - Alpaca VWAP- 223.38, Tos VWAP -224.20
12:55pm PST Alpaca volume - 2,451,091 ToS-1,906,234 - Alpaca VWAP- 222.67, Tos VWAP -224.1

### Environment

```markdown
- SDK Version: 7.12
- OS (version, bitness): Windows 11
- .NET SDK (version): 7.12
- target process .NET version/bitness: .NET Core 8
```

**Comment by OlegRa** [comment]
@ushahx This issue concerns data quality, which I can't help you with. This SDK is just a wrapper around underlying Alpaca-backed code, and it would be better if you asked this question on the official Alpaca forum.

This difference is most likely the result of applying correction trades on bars. Not all data providers do it according to exchange rules, so the result can vary. But I'm not an expert in this area; it's just my guess.
