### ISSUE TITLE
GetBarSetAsync fails with 'code' missing from JsonError parsing

### ISSUE THREAD

**Issue by mercalli** [alpacahq/alpaca-trade-api-csharp#84]
**Alpaca.Markets Package Version**: 3.1.1

**Issue**: When attempting to call GetBarSetAsync a json deserialization error is thrown. Error message states that the required 'code' property is not set, this seems to be swallowing the actual error being thrown, since the message isn't being deserialized properly.

**Error Message**: Required property 'code' not found in JSON. Path '', line 1, position 34.

**Reproduction Code Sample**:

```
using Alpaca.Markets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public static class Program
    {
       private static readonly string KEY_ID = "your_key_id";
        private static readonly string SECRET_KEY = "your_secret_key";
        public static async Task Main(string[] args)
        {
            var restClient = new RestClient(keyId: KEY_ID, secretKey: SECRET_KEY, alpacaRestApi: "https://paper-api.alpaca.markets", apiVersion: 2);
            try
            {
                Console.WriteLine(restClient.GetClockAsync().Result.IsOpen); //Works fine

                var symbs = new List<string> { "AAPL" };
                var bars = await restClient.GetBarSetAsync(symbs, TimeFrame.Day, 5); // Fails here

                var startPrice = bars.First().Value.First().Open;
                var endPrice = bars.Last().Value.Last().Close;
                var percentChange = (endPrice - startPrice) / startPrice * 100;

                Console.WriteLine($"AAPL moved {percentChange} over the last 5 days.");
            }
            catch(Exception ex)
            {
                    Console.WriteLine(ex.Message);
              }
            Console.Read();
        }
    }
}
```

**Comment by thedudebond** [comment]
Same here.

**Comment by OlegRa** [comment]
@mercalli @thedudebond Could you please test version 3.1.2 of SDK and close this issue if this problem disappears.

**Comment by thedudebond** [comment]
This is working for me now. However, I get the same error when calling RestClient.GetLastQuoteAsync with the same symbol. Looking at the method summary, seems like this would require access to Polygon and should probably have a better message.

**Comment by OlegRa** [comment]
@thedudebond I've already created another issue (#86 ) about proper generic HTTP errors handling.

**Comment by mercalli** [comment]
I can confirm 3.1.2 fixed the issue. Thanks for the quick turn around on this :+1:
