### ISSUE TITLE
sell_short not identified exception in OrderSide enum during PostOrderAsync client call

### ISSUE THREAD

**Issue by apasumarthi1999** [alpacahq/alpaca-trade-api-csharp#95]
Hi,

I'm trying out the short sell on paper account. I'm receiving the following exception.

**sell_short not identified exception in OrderSide enum during PostOrderAsync client call**

Appreciate if you can please resolve and release new NuGet package as soon as possible.

**Comment by OlegRa** [comment]
@ttt733 Trevor, I'm unable to find information about 'sell_short' order side in official API documentation. Could you please, check this issue from back-end side?

**Comment by ttt733** [comment]
I mentioned this in a comment on the PR, but this is due to a backend issue with Alpaca. We've identified the code change that needs to be made and will be deploying a fix outside of market hours.

**Comment by OlegRa** [comment]
Will be fixed on backend soon. No changes in client SDK's required. See comment for PR #101 for more details.
