### ISSUE TITLE
Not receiving Trade Fill event on short sell

### ISSUE THREAD

**Issue by apasumarthi1999** [alpacahq/alpaca-trade-api-csharp#96]
Hi,

I'm trying out the short sell on my paper account. I'm not receiving any trade fill events after I call PostOrderAsync (which throws sell_short enum exception, but I found a dirty workaround until you fix it).

However, I see that the short sell order is placed in my portfolio.

**Comment by OlegRa** [comment]
@ttt733 Trevor, I'm unable to find information about 'sell_short' order side in official API documentation. Could you please, check this issue from back-end side?

**Comment by apasumarthi1999** [comment]
Alpaca has recently allowed short selling. We can do short selling by placing a sell order without having a long order for the symbol. In this case the alpaca api is returning sell_short value for OrderSide enum. And in this c# SDK, OrderSide has only buy and sell enum values, so it is throwing exception that sell_short could not be converted to OrderSide enum.

Hope you can try short selling on a alpaca paper account and see the issue for yourself and fix it accordingly.

**Comment by ttt733** [comment]
I mentioned this in a comment on the PR, but this is due to a backend issue with Alpaca. We've identified the code change that needs to be made and will be deploying a fix outside of market hours.

**Comment by OlegRa** [comment]
Will be fixed on backend soon. No changes in client SDK's required. See comment for PR #101 for more details.
